export const suitNames = {
  'Major Arcana': 'suit.major',
  'Wands': 'suit.wands',
  'Cups': 'suit.cups',
  'Swords': 'suit.swords',
  'Pentacles': 'suit.pentacles'
};
export const orientationNames = { upright: 'orientation.upright', reversed: 'orientation.reversed' };
export const tendencyNames = { yes: 'tendency.yes', no: 'tendency.no', unclear: 'tendency.unclear' };
export function getCardImageUrl(card, ext = 'jpg', width = null) {
  if (!card || !card.nameKey) return null;
  return width ? `img/cards/${width}/${card.nameKey}.${ext}` : `img/cards/${card.nameKey}.${ext}`;
}
export const fullTarotCards = [
  { name: "愚者", suit: "Major Arcana", number: "0", englishName: "The Fool", nameKey: "fool" },
  { name: "魔術師", suit: "Major Arcana", number: "I", englishName: "The Magician", nameKey: "magician" },
  { name: "女祭司", suit: "Major Arcana", number: "II", englishName: "The High Priestess", nameKey: "high_priestess" },
  { name: "皇后", suit: "Major Arcana", number: "III", englishName: "The Empress", nameKey: "empress" },
  { name: "皇帝", suit: "Major Arcana", number: "IV", englishName: "The Emperor", nameKey: "emperor" },
  { name: "教皇", suit: "Major Arcana", number: "V", englishName: "The Hierophant", nameKey: "hierophant" },
  { name: "戀人", suit: "Major Arcana", number: "VI", englishName: "The Lovers", nameKey: "lovers" },
  { name: "戰車", suit: "Major Arcana", number: "VII", englishName: "The Chariot", nameKey: "chariot" },
  { name: "力量", suit: "Major Arcana", number: "VIII", englishName: "Strength", nameKey: "strength" },
  { name: "隱士", suit: "Major Arcana", number: "IX", englishName: "The Hermit", nameKey: "hermit" },
  { name: "命運之輪", suit: "Major Arcana", number: "X", englishName: "Wheel of Fortune", nameKey: "wheel_of_fortune" },
  { name: "正義", suit: "Major Arcana", number: "XI", englishName: "Justice", nameKey: "justice" },
  { name: "倒吊人", suit: "Major Arcana", number: "XII", englishName: "The Hanged Man", nameKey: "hanged_man" },
  { name: "死神", suit: "Major Arcana", number: "XIII", englishName: "Death", nameKey: "death" },
  { name: "節制", suit: "Major Arcana", number: "XIV", englishName: "Temperance", nameKey: "temperance" },
  { name: "惡魔", suit: "Major Arcana", number: "XV", englishName: "The Devil", nameKey: "devil" },
  { name: "高塔", suit: "Major Arcana", number: "XVI", englishName: "The Tower", nameKey: "tower" },
  { name: "星星", suit: "Major Arcana", number: "XVII", englishName: "The Star", nameKey: "star" },
  { name: "月亮", suit: "Major Arcana", number: "XVIII", englishName: "The Moon", nameKey: "moon" },
  { name: "太陽", suit: "Major Arcana", number: "XIX", englishName: "The Sun", nameKey: "sun" },
  { name: "審判", suit: "Major Arcana", number: "XX", englishName: "Judgement", nameKey: "judgement" },
  { name: "世界", suit: "Major Arcana", number: "XXI", englishName: "The World", nameKey: "world" },
  { name: "權杖一", suit: "Wands", number: "Ace", englishName: "Ace of Wands", nameKey: "ace_of_wands" },
  { name: "權杖二", suit: "Wands", number: "Two", englishName: "Two of Wands", nameKey: "two_of_wands" },
  { name: "權杖三", suit: "Wands", number: "Three", englishName: "Three of Wands", nameKey: "three_of_wands" },
  { name: "權杖四", suit: "Wands", number: "Four", englishName: "Four of Wands", nameKey: "four_of_wands" },
  { name: "權杖五", suit: "Wands", number: "Five", englishName: "Five of Wands", nameKey: "five_of_wands" },
  { name: "權杖六", suit: "Wands", number: "Six", englishName: "Six of Wands", nameKey: "six_of_wands" },
  { name: "權杖七", suit: "Wands", number: "Seven", englishName: "Seven of Wands", nameKey: "seven_of_wands" },
  { name: "權杖八", suit: "Wands", number: "Eight", englishName: "Eight of Wands", nameKey: "eight_of_wands" },
  { name: "權杖九", suit: "Wands", number: "Nine", englishName: "Nine of Wands", nameKey: "nine_of_wands" },
  { name: "權杖十", suit: "Wands", number: "Ten", englishName: "Ten of Wands", nameKey: "ten_of_wands" },
  { name: "權杖侍者", suit: "Wands", number: "Page", englishName: "Page of Wands", nameKey: "page_of_wands" },
  { name: "權杖騎士", suit: "Wands", number: "Knight", englishName: "Knight of Wands", nameKey: "knight_of_wands" },
  { name: "權杖皇后", suit: "Wands", number: "Queen", englishName: "Queen of Wands", nameKey: "queen_of_wands" },
  { name: "權杖國王", suit: "Wands", number: "King", englishName: "King of Wands", nameKey: "king_of_wands" },
  { name: "聖杯一", suit: "Cups", number: "Ace", englishName: "Ace of Cups", nameKey: "ace_of_cups" },
  { name: "聖杯二", suit: "Cups", number: "Two", englishName: "Two of Cups", nameKey: "two_of_cups" },
  { name: "聖杯三", suit: "Cups", number: "Three", englishName: "Three of Cups", nameKey: "three_of_cups" },
  { name: "聖杯四", suit: "Cups", number: "Four", englishName: "Four of Cups", nameKey: "four_of_cups" },
  { name: "聖杯五", suit: "Cups", number: "Five", englishName: "Five of Cups", nameKey: "five_of_cups" },
  { name: "聖杯六", suit: "Cups", number: "Six", englishName: "Six of Cups", nameKey: "six_of_cups" },
  { name: "聖杯七", suit: "Cups", number: "Seven", englishName: "Seven of Cups", nameKey: "seven_of_cups" },
  { name: "聖杯八", suit: "Cups", number: "Eight", englishName: "Eight of Cups", nameKey: "eight_of_cups" },
  { name: "聖杯九", suit: "Cups", number: "Nine", englishName: "Nine of Cups", nameKey: "nine_of_cups" },
  { name: "聖杯十", suit: "Cups", number: "Ten", englishName: "Ten of Cups", nameKey: "ten_of_cups" },
  { name: "聖杯侍者", suit: "Cups", number: "Page", englishName: "Page of Cups", nameKey: "page_of_cups" },
  { name: "聖杯騎士", suit: "Cups", number: "Knight", englishName: "Knight of Cups", nameKey: "knight_of_cups" },
  { name: "聖杯皇后", suit: "Cups", number: "Queen", englishName: "Queen of Cups", nameKey: "queen_of_cups" },
  { name: "聖杯國王", suit: "Cups", number: "King", englishName: "King of Cups", nameKey: "king_of_cups" },
  { name: "寶劍一", suit: "Swords", number: "Ace", englishName: "Ace of Swords", nameKey: "ace_of_swords" },
  { name: "寶劍二", suit: "Swords", number: "Two", englishName: "Two of Swords", nameKey: "two_of_swords" },
  { name: "寶劍三", suit: "Swords", number: "Three", englishName: "Three of Swords", nameKey: "three_of_swords" },
  { name: "寶劍四", suit: "Swords", number: "Four", englishName: "Four of Swords", nameKey: "four_of_swords" },
  { name: "寶劍五", suit: "Swords", number: "Five", englishName: "Five of Swords", nameKey: "five_of_swords" },
  { name: "寶劍六", suit: "Swords", number: "Six", englishName: "Six of Swords", nameKey: "six_of_swords" },
  { name: "寶劍七", suit: "Swords", number: "Seven", englishName: "Seven of Swords", nameKey: "seven_of_swords" },
  { name: "寶劍八", suit: "Swords", number: "Eight", englishName: "Eight of Swords", nameKey: "eight_of_swords" },
  { name: "寶劍九", suit: "Swords", number: "Nine", englishName: "Nine of Swords", nameKey: "nine_of_swords" },
  { name: "寶劍十", suit: "Swords", number: "Ten", englishName: "Ten of Swords", nameKey: "ten_of_swords" },
  { name: "寶劍侍者", suit: "Swords", number: "Page", englishName: "Page of Swords", nameKey: "page_of_swords" },
  { name: "寶劍騎士", suit: "Swords", number: "Knight", englishName: "Knight of Swords", nameKey: "knight_of_swords" },
  { name: "寶劍皇后", suit: "Swords", number: "Queen", englishName: "Queen of Swords", nameKey: "queen_of_swords" },
  { name: "寶劍國王", suit: "Swords", number: "King", englishName: "King of Swords", nameKey: "king_of_swords" },
  { name: "錢幣一", suit: "Pentacles", number: "Ace", englishName: "Ace of Pentacles", nameKey: "ace_of_pentacles" },
  { name: "錢幣二", suit: "Pentacles", number: "Two", englishName: "Two of Pentacles", nameKey: "two_of_pentacles" },
  { name: "錢幣三", suit: "Pentacles", number: "Three", englishName: "Three of Pentacles", nameKey: "three_of_pentacles" },
  { name: "錢幣四", suit: "Pentacles", number: "Four", englishName: "Four of Pentacles", nameKey: "four_of_pentacles" },
  { name: "錢幣五", suit: "Pentacles", number: "Five", englishName: "Five of Pentacles", nameKey: "five_of_pentacles" },
  { name: "錢幣六", suit: "Pentacles", number: "Six", englishName: "Six of Pentacles", nameKey: "six_of_pentacles" },
  { name: "錢幣七", suit: "Pentacles", number: "Seven", englishName: "Seven of Pentacles", nameKey: "seven_of_pentacles" },
  { name: "錢幣八", suit: "Pentacles", number: "Eight", englishName: "Eight of Pentacles", nameKey: "eight_of_pentacles" },
  { name: "錢幣九", suit: "Pentacles", number: "Nine", englishName: "Nine of Pentacles", nameKey: "nine_of_pentacles" },
  { name: "錢幣十", suit: "Pentacles", number: "Ten", englishName: "Ten of Pentacles", nameKey: "ten_of_pentacles" },
  { name: "錢幣侍者", suit: "Pentacles", number: "Page", englishName: "Page of Pentacles", nameKey: "page_of_pentacles" },
  { name: "錢幣騎士", suit: "Pentacles", number: "Knight", englishName: "Knight of Pentacles", nameKey: "knight_of_pentacles" },
  { name: "錢幣皇后", suit: "Pentacles", number: "Queen", englishName: "Queen of Pentacles", nameKey: "queen_of_pentacles" },
  { name: "錢幣國王", suit: "Pentacles", number: "King", englishName: "King of Pentacles", nameKey: "king_of_pentacles" }
];
export const majorArcana = fullTarotCards.slice(0, 22);
export const minorArcana = fullTarotCards.slice(22);
export const courtCards = fullTarotCards.filter(c => ['Page', 'Knight', 'Queen', 'King'].includes(c.number));
export const numberedCards = fullTarotCards.filter(c => !['Page', 'Knight', 'Queen', 'King'].includes(c.number) && c.suit !== 'Major Arcana');
export const spreads = {
  single: { positions: ['spread.single.pos.0'], description: 'spread.single.desc' },
  three: { positions: ['spread.three.pos.0', 'spread.three.pos.1', 'spread.three.pos.2'], description: 'spread.three.desc' },
  mbs: { positions: ['spread.mbs.pos.0', 'spread.mbs.pos.1', 'spread.mbs.pos.2'], description: 'spread.mbs.desc' },
  path: { positions: ['spread.path.pos.0', 'spread.path.pos.1', 'spread.path.pos.2', 'spread.path.pos.3'], description: 'spread.path.desc' },
  twoChoice: { positions: ['spread.twoChoice.pos.0', 'spread.twoChoice.pos.1', 'spread.twoChoice.pos.2', 'spread.twoChoice.pos.3', 'spread.twoChoice.pos.4'], description: 'spread.twoChoice.desc' },
  prosCons: { positions: ['spread.prosCons.pos.0', 'spread.prosCons.pos.1', 'spread.prosCons.pos.2', 'spread.prosCons.pos.3', 'spread.prosCons.pos.4'], description: 'spread.prosCons.desc' },
  goal: { positions: ['spread.goal.pos.0', 'spread.goal.pos.1', 'spread.goal.pos.2', 'spread.goal.pos.3', 'spread.goal.pos.4'], description: 'spread.goal.desc' },
  relationship: { positions: ['spread.relationship.pos.0', 'spread.relationship.pos.1', 'spread.relationship.pos.2', 'spread.relationship.pos.3', 'spread.relationship.pos.4'], description: 'spread.relationship.desc' },
  weekly: { positions: ['spread.weekly.pos.0', 'spread.weekly.pos.1', 'spread.weekly.pos.2', 'spread.weekly.pos.3', 'spread.weekly.pos.4', 'spread.weekly.pos.5', 'spread.weekly.pos.6', 'spread.weekly.pos.7'], description: 'spread.weekly.desc' },
  monthly: { positions: ['spread.monthly.pos.0', 'spread.monthly.pos.1', 'spread.monthly.pos.2', 'spread.monthly.pos.3', 'spread.monthly.pos.4'], description: 'spread.monthly.desc' },
  quarterly: { positions: ['spread.quarterly.pos.0', 'spread.quarterly.pos.1', 'spread.quarterly.pos.2', 'spread.quarterly.pos.3'], description: 'spread.quarterly.desc' },
  yearly: { positions: ['spread.yearly.pos.0', 'spread.yearly.pos.1', 'spread.yearly.pos.2', 'spread.yearly.pos.3', 'spread.yearly.pos.4', 'spread.yearly.pos.5', 'spread.yearly.pos.6', 'spread.yearly.pos.7', 'spread.yearly.pos.8', 'spread.yearly.pos.9', 'spread.yearly.pos.10', 'spread.yearly.pos.11', 'spread.yearly.pos.12'], description: 'spread.yearly.desc' },
  chakra: { positions: ['spread.chakra.pos.0', 'spread.chakra.pos.1', 'spread.chakra.pos.2', 'spread.chakra.pos.3', 'spread.chakra.pos.4', 'spread.chakra.pos.5', 'spread.chakra.pos.6'], description: 'spread.chakra.desc' },
  elements: { positions: ['spread.elements.pos.0', 'spread.elements.pos.1', 'spread.elements.pos.2', 'spread.elements.pos.3', 'spread.elements.pos.4'], description: 'spread.elements.desc' },
  celtic: { positions: ['spread.celtic.pos.0', 'spread.celtic.pos.1', 'spread.celtic.pos.2', 'spread.celtic.pos.3', 'spread.celtic.pos.4', 'spread.celtic.pos.5', 'spread.celtic.pos.6', 'spread.celtic.pos.7', 'spread.celtic.pos.8', 'spread.celtic.pos.9'], description: 'spread.celtic.desc' },
  yesno: { positions: ['spread.yesno.pos.0', 'spread.yesno.pos.1', 'spread.yesno.pos.2'], description: 'spread.yesno.desc' },
  newmoon: { positions: ['spread.newmoon.pos.0', 'spread.newmoon.pos.1', 'spread.newmoon.pos.2', 'spread.newmoon.pos.3', 'spread.newmoon.pos.4'], description: 'spread.newmoon.desc' },
  fullmoon: { positions: ['spread.fullmoon.pos.0', 'spread.fullmoon.pos.1', 'spread.fullmoon.pos.2', 'spread.fullmoon.pos.3', 'spread.fullmoon.pos.4'], description: 'spread.fullmoon.desc' },
  feelings: { positions: ['spread.feelings.pos.0', 'spread.feelings.pos.1', 'spread.feelings.pos.2', 'spread.feelings.pos.3', 'spread.feelings.pos.4'], description: 'spread.feelings.desc' },
  loveCross: { positions: ['spread.loveCross.pos.0', 'spread.loveCross.pos.1', 'spread.loveCross.pos.2', 'spread.loveCross.pos.3', 'spread.loveCross.pos.4', 'spread.loveCross.pos.5'], description: 'spread.loveCross.desc' },
  conflict: { positions: ['spread.conflict.pos.0', 'spread.conflict.pos.1', 'spread.conflict.pos.2', 'spread.conflict.pos.3', 'spread.conflict.pos.4'], description: 'spread.conflict.desc' },
  career: { positions: ['spread.career.pos.0', 'spread.career.pos.1', 'spread.career.pos.2', 'spread.career.pos.3', 'spread.career.pos.4', 'spread.career.pos.5'], description: 'spread.career.desc' },
  wealth: { positions: ['spread.wealth.pos.0', 'spread.wealth.pos.1', 'spread.wealth.pos.2', 'spread.wealth.pos.3', 'spread.wealth.pos.4'], description: 'spread.wealth.desc' },
  selfDiscovery: { positions: ['spread.selfDiscovery.pos.0', 'spread.selfDiscovery.pos.1', 'spread.selfDiscovery.pos.2', 'spread.selfDiscovery.pos.3', 'spread.selfDiscovery.pos.4'], description: 'spread.selfDiscovery.desc' },
  shadow: { positions: ['spread.shadow.pos.0', 'spread.shadow.pos.1', 'spread.shadow.pos.2', 'spread.shadow.pos.3', 'spread.shadow.pos.4'], description: 'spread.shadow.desc' },
  dream: { positions: ['spread.dream.pos.0', 'spread.dream.pos.1', 'spread.dream.pos.2', 'spread.dream.pos.3'], description: 'spread.dream.desc' },
  horseshoe: { positions: ['spread.horseshoe.pos.0', 'spread.horseshoe.pos.1', 'spread.horseshoe.pos.2', 'spread.horseshoe.pos.3', 'spread.horseshoe.pos.4', 'spread.horseshoe.pos.5', 'spread.horseshoe.pos.6'], description: 'spread.horseshoe.desc' },
  treeOfLife: { positions: ['spread.treeOfLife.pos.0', 'spread.treeOfLife.pos.1', 'spread.treeOfLife.pos.2', 'spread.treeOfLife.pos.3', 'spread.treeOfLife.pos.4', 'spread.treeOfLife.pos.5', 'spread.treeOfLife.pos.6', 'spread.treeOfLife.pos.7', 'spread.treeOfLife.pos.8', 'spread.treeOfLife.pos.9'], description: 'spread.treeOfLife.desc' },
  astroHouses: { positions: ['spread.astroHouses.pos.0', 'spread.astroHouses.pos.1', 'spread.astroHouses.pos.2', 'spread.astroHouses.pos.3', 'spread.astroHouses.pos.4', 'spread.astroHouses.pos.5', 'spread.astroHouses.pos.6', 'spread.astroHouses.pos.7', 'spread.astroHouses.pos.8', 'spread.astroHouses.pos.9', 'spread.astroHouses.pos.10', 'spread.astroHouses.pos.11'], description: 'spread.astroHouses.desc' }
};
export const commonTags = ['工作', '感情', '健康', '財運', '學業', '人際', '靈性', '決策'];
export const spreadLayouts = {
  celtic: { cols: 4, cells: [
    { r: 2, c: 2 },
    { r: 2, c: 2, rot: 90 },
    { r: 3, c: 2 },
    { r: 2, c: 1 },
    { r: 1, c: 2 },
    { r: 2, c: 3 },
    { r: 1, c: 4 },
    { r: 2, c: 4 },
    { r: 3, c: 4 },
    { r: 4, c: 4 }
  ] },
  horseshoe: { cols: 7, cells: [
    { r: 3, c: 1 },
    { r: 2, c: 2 },
    { r: 1, c: 3 },
    { r: 1, c: 4 },
    { r: 1, c: 5 },
    { r: 2, c: 6 },
    { r: 3, c: 7 }
  ] },
  twoChoice: { cols: 3, cells: [
    { r: 3, c: 2 },
    { r: 2, c: 1 },
    { r: 2, c: 3 },
    { r: 1, c: 1 },
    { r: 1, c: 3 }
  ] },
  prosCons: { cols: 3, cells: [
    { r: 1, c: 1 },
    { r: 2, c: 1 },
    { r: 1, c: 3 },
    { r: 2, c: 3 },
    { r: 1, c: 2, rs: 2 }
  ] },
  loveCross: { cols: 4, cells: [
    { r: 2, c: 1 },
    { r: 2, c: 3 },
    { r: 2, c: 2 },
    { r: 3, c: 2 },
    { r: 1, c: 2 },
    { r: 2, c: 4 }
  ] }
};
