export const uiStrings = {
  zh: {
    'app.title': '塔羅占卜',
    'app.name': '塔羅',
    'app.themeToggle.toDark': '切換至深色主題',
    'app.themeToggle.toLight': '切換至淺色主題',
    'app.themeToggle.title': '切換主題（T）',
    'app.langSwitch.label': '切換語言：{lang}',
    'app.skipToMain': '跳到主要內容',
    'app.hero.title': '探索內心的指引',
    'app.hero.subtitle': '帶著一個具體的問題抽牌，再對照牌位與牌義讀出答案。',
    'app.share.text': '查看我的占卜結果',
    'app.share.imageFooter': '僅供參考 · 塔羅占卜工具',
    'footer.about.title': '關於',
    'footer.about.desc': '以偉特塔羅為本的牌義、牌陣與學習工具。占卜記錄只存在你的裝置上。',
    'footer.info.title': '資訊',
    'footer.link.about': '關於本站',
    'footer.link.privacy': '隱私政策',
    'footer.copyright': '塔羅占卜工具 · 僅供參考使用',
    'tab.list': '主要分頁',
    'tab.reading': '占卜',
    'tab.history': '記錄',
    'tab.statistics': '統計',
    'tab.database': '資料庫',
    'tab.learn': '學習',
    'tab.settings': '設定',
    'pager.label': '逐張解讀的牌位',
    'pager.prev': '上一張',
    'pager.next': '下一張',
    'pager.nextTo': '下一張：{name}',
    'pager.count': '{n} / {total}',
    'pager.slide': '第 {n} 張，共 {total} 張',
    'pager.status': '第 {n} 張，共 {total} 張：{pos}，{name}（{ori}）',
    'pager.hint': '左右滑動換一張',
    'hero.swipe': '向上滑動，抽出{spread}',
    'hero.tiles.more': '更多',
    'hero.tiles.moreLabel': '更多牌陣',
    'reading.daily.title': '每日一牌 · {m}月{d}日',
    'reading.question.label': '你的問題',
    'reading.question.placeholder': '例如：目前最需要專注的方向？',
    'reading.deck.label': '牌組',
    'reading.spread.label': '牌陣',
    'reading.spreadInfo.title': '關於此牌陣',
    'reading.spreadInfo.positions': '牌位說明',
    'reading.results.title': '你的占卜',
    'reading.detail.title': '逐張解讀',
    'reading.detail.text': '{ori}牌義',
    'reading.detail.more': '看卡片詳情',
    'reading.detail.more.label': '看卡片詳情：{name}（{ori}）',
    'reading.detail.expandAll': '全部展開',
    'reading.detail.collapseAll': '全部收合',
    'reading.copy.keywords': '關鍵詞：{kw}',
    'reading.detail.role': '在這個位置',
    'reading.copy.role': '在這個位置：{text}',
    'reading.busy': '占卜中…',
    'pick.title': '憑直覺選牌',
    'pick.hint': '靜心想著你的問題，選出 <strong>{n}</strong> 張牌',
    'pick.progress': '已選 {n} / {total}',
    'pick.cardBack': '第 {n} 張牌背',
    'pick.cardPicked': '第 {n} 張牌背，已選為第 {order} 張',
    'pick.random': '隨機快選',
    'pick.reshuffle': '重新洗牌',
    'deck.full': '完整牌組（78 張）',
    'deck.major': '大阿卡納（22 張）',
    'deck.minor': '小阿卡納（56 張）',
    'deck.court': '宮廷牌（16 張）',
    'deck.numbered': '數字牌（40 張）',
    'spread.group.basic': '基礎指引',
    'spread.group.time': '時間運勢',
    'spread.group.love': '感情與人際',
    'spread.group.career': '抉擇與事業',
    'spread.group.self': '內在探索',
    'spread.group.advanced': '進階經典',
    'spread.bottom': '底牌',
    'spread.bottom.desc': '洗牌後壓在整疊最下面、沒有進入牌陣的那張，常當作整件事底下的背景基調。',
    'spread.unknown': '未知牌陣',
    'spread.picker.title': '選擇牌陣',
    'spread.picker.count': '{n} 張',
    'spread.single.name': '單張牌指引',
    'spread.single.label': '單張牌',
    'spread.single.desc': '只抽一張，適合每日指引，或一個已經聚焦的具體問題。',
    'spread.single.pos.0': '核心指引',
    'spread.single.pos.0.desc': '對你問題的直接回應，也就是此刻最該留意的主題。',
    'spread.yesno.name': '是非指引',
    'spread.yesno.label': '是非指引',
    'spread.yesno.desc': '針對「會不會」「該不該」的問題。本站不替三張牌合算答案：點開每張牌，在「情境」分頁看它的是非傾向，再把三個位置放在一起判斷。',
    'spread.yesno.pos.0': '支持的力量',
    'spread.yesno.pos.0.desc': '有利於「是」的因素：你手上的資源、時機或助力。',
    'spread.yesno.pos.1': '阻礙的力量',
    'spread.yesno.pos.1.desc': '不利於「是」的因素：卡住的地方、風險或你的顧慮。重點是它能不能被處理，而不只是它存不存在。',
    'spread.yesno.pos.2': '結果傾向',
    'spread.yesno.pos.2.desc': '照目前的情況走下去，事情大致偏向哪一邊。以這張牌的是非傾向為主，再用前兩張判斷這個傾向穩不穩。',
    'spread.three.name': '聖三角',
    'spread.three.label': '聖三角',
    'spread.three.desc': '最常用的三張牌時間線：一件事從哪裡來、正走到哪裡、接下來往哪裡去。',
    'spread.three.pos.0': '過去',
    'spread.three.pos.0.desc': '已經發生、至今仍在影響這件事的經歷或決定。讀它是為了理解現況從何而來。',
    'spread.three.pos.1': '現在',
    'spread.three.pos.1.desc': '你此刻的處境與眼前的主題，是三張牌的重心。',
    'spread.three.pos.2': '未來',
    'spread.three.pos.2.desc': '照目前的方向發展下去最可能的走向，不是定局；不喜歡這張牌，就回頭看「現在」有什麼可以改。',
    'spread.mbs.name': '身心靈牌陣',
    'spread.mbs.label': '身心靈',
    'spread.mbs.desc': '從心態、身體、靈性三個層面看你目前的狀態：找出哪一層失衡，再看它怎麼牽動另外兩層。',
    'spread.mbs.pos.0': '心態',
    'spread.mbs.pos.0.desc': '你的想法、情緒與壓力，以及你怎麼看待自己的處境。',
    'spread.mbs.pos.1': '身體',
    'spread.mbs.pos.1.desc': '體力、作息與身體發出的訊號。逆位常是提醒你休息或照顧被忽略的需要；身體不適請以就醫為準。',
    'spread.mbs.pos.2': '靈性',
    'spread.mbs.pos.2.desc': '你和意義感、信念或內在平靜的連結：什麼能讓你重新感到踏實。',
    'spread.path.name': '抉擇之路',
    'spread.path.label': '抉擇之路',
    'spread.path.desc': '面對一個決定或一段要走的路時用：先看清問題，再看卡在哪裡、該往哪走，以及照這個方向走下去的結果。',
    'spread.path.pos.0': '問題',
    'spread.path.pos.0.desc': '這件事真正的核心。它有時和你問的不一樣，那正是值得注意的地方。',
    'spread.path.pos.1': '挑戰',
    'spread.path.pos.1.desc': '眼前最主要的阻力，可能來自外在環境，也可能是你自己的習慣或顧慮。',
    'spread.path.pos.2': '方向',
    'spread.path.pos.2.desc': '牌建議你採取的態度或行動。正位就照著做；逆位提醒你先修正這個方向裡過度或不足的部分。',
    'spread.path.pos.3': '結果',
    'spread.path.pos.3.desc': '照「方向」的建議走下去最可能的結果。',
    'spread.weekly.name': '週運勢',
    'spread.weekly.label': '週運勢',
    'spread.weekly.desc': '一張整週主題，加上週一到週日每天一張。先讀主題，再看每天的牌怎麼呼應或偏離它。',
    'spread.weekly.pos.0': '主題',
    'spread.weekly.pos.0.desc': '這一週的基調與最該留意的事；每天的牌都放在它底下讀。',
    'spread.weekly.pos.1': '週一',
    'spread.weekly.pos.2': '週二',
    'spread.weekly.pos.3': '週三',
    'spread.weekly.pos.4': '週四',
    'spread.weekly.pos.5': '週五',
    'spread.weekly.pos.6': '週六',
    'spread.weekly.pos.7': '週日',
    'spread.monthly.name': '月運勢',
    'spread.monthly.label': '月運勢',
    'spread.monthly.desc': '一張本月主題，加上四週各一張；第四週的牌也涵蓋月底剩下的日子。',
    'spread.monthly.pos.0': '本月主題',
    'spread.monthly.pos.0.desc': '這個月的整體走向與重點；四週的牌都放在它底下讀。',
    'spread.monthly.pos.1': '第一週',
    'spread.monthly.pos.2': '第二週',
    'spread.monthly.pos.3': '第三週',
    'spread.monthly.pos.4': '第四週',
    'spread.quarterly.name': '四季展望',
    'spread.quarterly.label': '四季展望',
    'spread.quarterly.desc': '看接下來一年的四季，各抽一張：還沒過完的季節讀今年，已經過去的季節讀明年。',
    'spread.quarterly.pos.0': '春季（3–5 月）',
    'spread.quarterly.pos.1': '夏季（6–8 月）',
    'spread.quarterly.pos.2': '秋季（9–11 月）',
    'spread.quarterly.pos.3': '冬季（12–2 月）',
    'spread.yearly.name': '年度主題',
    'spread.yearly.label': '年度主題',
    'spread.yearly.desc': '一張年度總主題，加上一月到十二月各一張。適合在年初做，年中可以回頭對照。',
    'spread.yearly.pos.0': '總主題',
    'spread.yearly.pos.0.desc': '這一年的核心課題與整體走向；各月的牌是它在不同時段的展開。',
    'spread.yearly.pos.1': '一月',
    'spread.yearly.pos.2': '二月',
    'spread.yearly.pos.3': '三月',
    'spread.yearly.pos.4': '四月',
    'spread.yearly.pos.5': '五月',
    'spread.yearly.pos.6': '六月',
    'spread.yearly.pos.7': '七月',
    'spread.yearly.pos.8': '八月',
    'spread.yearly.pos.9': '九月',
    'spread.yearly.pos.10': '十月',
    'spread.yearly.pos.11': '十一月',
    'spread.yearly.pos.12': '十二月',
    'spread.newmoon.name': '新月啟程',
    'spread.newmoon.label': '新月啟程',
    'spread.newmoon.desc': '在新月前後做，為接下來約一個月（到下一次新月）設定意圖，並找出實現它需要的資源與該放下的東西。',
    'spread.newmoon.pos.0': '新月意圖',
    'spread.newmoon.pos.0.desc': '這個週期最值得投入的目標或方向。若和你原本想的不同，先想想牌為什麼這樣提示。',
    'spread.newmoon.pos.1': '內在資源',
    'spread.newmoon.pos.1.desc': '你已經具備、可以拿來用的能力或特質。',
    'spread.newmoon.pos.2': '外在助力',
    'spread.newmoon.pos.2.desc': '環境裡可以借力的人、機會或條件。',
    'spread.newmoon.pos.3': '需要放下',
    'spread.newmoon.pos.3.desc': '會拖住你的習慣、想法或關係，這個週期先把它放下。',
    'spread.newmoon.pos.4': '顯化方向',
    'spread.newmoon.pos.4.desc': '把意圖落實的具體做法，也就是接下來該踏出的第一步。',
    'spread.fullmoon.name': '滿月釋放',
    'spread.fullmoon.label': '滿月釋放',
    'spread.fullmoon.desc': '在滿月前後做，回顧從上次新月到現在的這段週期：完成了什麼、還沒完成什麼、該放下什麼。',
    'spread.fullmoon.pos.0': '已然圓滿',
    'spread.fullmoon.pos.0.desc': '這個週期已經完成或開花結果的事，先肯定它。',
    'spread.fullmoon.pos.1': '未竟之事',
    'spread.fullmoon.pos.1.desc': '還沒完成的部分：看它是需要再努力，還是該調整期待。',
    'spread.fullmoon.pos.2': '需要釋放',
    'spread.fullmoon.pos.2.desc': '該放下的情緒、執著或負擔，放下後才有空間迎接下一個週期。',
    'spread.fullmoon.pos.3': '收穫果實',
    'spread.fullmoon.pos.3.desc': '這個週期留給你的東西：不一定是看得見的成果，更常是學到的一課或新長出的能力。',
    'spread.fullmoon.pos.4': '下一步',
    'spread.fullmoon.pos.4.desc': '帶著這次的收穫進入下一個週期時，最該做的事。',
    'spread.relationship.name': '關係牌陣',
    'spread.relationship.label': '關係',
    'spread.relationship.desc': '看一段關係（伴侶、家人、朋友或同事都可以）裡雙方各自的看法、目前的狀態、主要的考驗與發展的可能。',
    'spread.relationship.pos.0': '你的觀點',
    'spread.relationship.pos.0.desc': '你怎麼看這段關係，以及你在其中的感受與期待。',
    'spread.relationship.pos.1': '對方觀點',
    'spread.relationship.pos.1.desc': '對方可能的感受與立場。這是牌給的角度，不等於讀心，最好再用實際的溝通確認。',
    'spread.relationship.pos.2': '現況',
    'spread.relationship.pos.2.desc': '這段關係此刻的狀態與兩人互動的基調。',
    'spread.relationship.pos.3': '挑戰',
    'spread.relationship.pos.3.desc': '關係裡最需要面對的問題或摩擦點。',
    'spread.relationship.pos.4': '潛力',
    'spread.relationship.pos.4.desc': '如果雙方都願意經營，這段關係能發展成的樣子。',
    'spread.feelings.name': '對方心意',
    'spread.feelings.label': '對方心意',
    'spread.feelings.desc': '從表面態度到內心感受，逐層看對方對你的心意。牌呈現的是可能性，不是讀心；真正的答案仍要從互動與溝通裡得到。',
    'spread.feelings.pos.0': '表面態度',
    'spread.feelings.pos.0.desc': '對方表現在外、你看得到的態度。',
    'spread.feelings.pos.1': '內心真實感受',
    'spread.feelings.pos.1.desc': '對方心裡可能的感受；可能和表面態度一致，也可能不同。',
    'spread.feelings.pos.2': '對關係的期待',
    'spread.feelings.pos.2.desc': '對方希望這段關係變成什麼樣子。',
    'spread.feelings.pos.3': '猶豫與顧慮',
    'spread.feelings.pos.3.desc': '讓對方遲疑或保留的原因。',
    'spread.feelings.pos.4': '可能的行動',
    'spread.feelings.pos.4.desc': '對方接下來比較可能採取的行動或態度。',
    'spread.loveCross.name': '愛情十字',
    'spread.loveCross.label': '愛情十字',
    'spread.loveCross.desc': '六張牌排成十字：左右是你與對方，中間是關係本身，上方是助力、下方是阻礙，最右邊是發展方向。',
    'spread.loveCross.pos.0': '你的狀態',
    'spread.loveCross.pos.0.desc': '你目前在感情裡的心態與處境。',
    'spread.loveCross.pos.1': '對方的狀態',
    'spread.loveCross.pos.1.desc': '對方目前的心態與處境；單身時可以讀成你正在吸引、或你期待遇見的對象。',
    'spread.loveCross.pos.2': '關係現況',
    'spread.loveCross.pos.2.desc': '兩人之間此刻的互動與連結。',
    'spread.loveCross.pos.3': '關係的阻礙',
    'spread.loveCross.pos.3.desc': '妨礙關係發展的因素，可能來自外在，也可能來自你們其中一方。',
    'spread.loveCross.pos.4': '關係的助力',
    'spread.loveCross.pos.4.desc': '讓關係更好的因素，值得刻意培養。',
    'spread.loveCross.pos.5': '發展方向',
    'spread.loveCross.pos.5.desc': '照目前的互動走下去，這段關係最可能的走向。',
    'spread.conflict.name': '衝突化解',
    'spread.conflict.label': '衝突化解',
    'spread.conflict.desc': '梳理一次人際衝突：根源在哪裡、雙方各自在意什麼、還有什麼共同點，以及化解的方法。',
    'spread.conflict.pos.0': '衝突的根源',
    'spread.conflict.pos.0.desc': '表面爭執底下真正的原因。',
    'spread.conflict.pos.1': '你的立場',
    'spread.conflict.pos.1.desc': '你在意的是什麼，以及你可能沒看到的盲點。',
    'spread.conflict.pos.2': '對方的立場',
    'spread.conflict.pos.2.desc': '對方在意的是什麼。用這張牌去理解對方，而不是證明對方錯了。',
    'spread.conflict.pos.3': '彼此的共同點',
    'spread.conflict.pos.3.desc': '雙方都在乎、可以當作和解起點的東西。',
    'spread.conflict.pos.4': '化解之道',
    'spread.conflict.pos.4.desc': '具體可以採取的做法或態度。',
    'spread.twoChoice.name': '二擇一',
    'spread.twoChoice.label': '二擇一',
    'spread.twoChoice.desc': '比較兩個選項：最下方是現況，左邊一列是選項 A、右邊一列是選項 B，各自由下往上是過程與結果。結果要和過程一起看：結果好的選項，過程不一定輕鬆。',
    'spread.twoChoice.pos.0': '現況',
    'spread.twoChoice.pos.0.desc': '你做決定時的處境與心態。',
    'spread.twoChoice.pos.1': '選項 A 的過程',
    'spread.twoChoice.pos.1.desc': '選 A 這條路要經歷什麼：順不順、要付出多少。',
    'spread.twoChoice.pos.2': '選項 B 的過程',
    'spread.twoChoice.pos.2.desc': '選 B 這條路要經歷什麼，和 A 的過程對照著讀。',
    'spread.twoChoice.pos.3': '選項 A 的結果',
    'spread.twoChoice.pos.3.desc': '選 A 最可能的結果。',
    'spread.twoChoice.pos.4': '選項 B 的結果',
    'spread.twoChoice.pos.4.desc': '選 B 最可能的結果。',
    'spread.prosCons.name': '優劣分析',
    'spread.prosCons.label': '優劣分析',
    'spread.prosCons.desc': '把兩個選項的優缺點並排：左邊是選項 A，右邊是選項 B，中間一張是做決定時最該放在心上的提示。',
    'spread.prosCons.pos.0': '選項 A 的優點',
    'spread.prosCons.pos.0.desc': '選 A 能得到的好處。',
    'spread.prosCons.pos.1': '選項 A 的缺點',
    'spread.prosCons.pos.1.desc': '選 A 要承擔的代價或風險。',
    'spread.prosCons.pos.2': '選項 B 的優點',
    'spread.prosCons.pos.2.desc': '選 B 能得到的好處。',
    'spread.prosCons.pos.3': '選項 B 的缺點',
    'spread.prosCons.pos.3.desc': '選 B 要承擔的代價或風險。',
    'spread.prosCons.pos.4': '核心提示',
    'spread.prosCons.pos.4.desc': '做這個決定時最該放在心上的事，往往點出你真正在意的是什麼。',
    'spread.goal.name': '目標達成牌陣',
    'spread.goal.label': '目標達成',
    'spread.goal.desc': '針對一個具體的目標：看它的核心、阻礙、可用的資源、該採取的步驟，以及照做之後的結果。',
    'spread.goal.pos.0': '核心',
    'spread.goal.pos.0.desc': '這個目標對你真正的意義，或它成敗的關鍵。',
    'spread.goal.pos.1': '阻礙',
    'spread.goal.pos.1.desc': '最可能讓你卡住的事。',
    'spread.goal.pos.2': '資源',
    'spread.goal.pos.2.desc': '你可以運用的能力、人脈或條件。',
    'spread.goal.pos.3': '步驟',
    'spread.goal.pos.3.desc': '接下來最該採取的具體行動。',
    'spread.goal.pos.4': '結果',
    'spread.goal.pos.4.desc': '照「步驟」的建議走下去最可能的結果。',
    'spread.career.name': '職涯發展',
    'spread.career.label': '職涯發展',
    'spread.career.desc': '檢視目前的工作或職涯方向：現況、你的優勢與盲點、外在的機會與挑戰，最後是具體建議。',
    'spread.career.pos.0': '職涯現況',
    'spread.career.pos.0.desc': '你在工作上的處境與心態。',
    'spread.career.pos.1': '你的優勢',
    'spread.career.pos.1.desc': '可以多加發揮的能力或特質。',
    'spread.career.pos.2': '你的盲點',
    'spread.career.pos.2.desc': '你沒注意到、或習慣忽略的弱點。',
    'spread.career.pos.3': '外在機會',
    'spread.career.pos.3.desc': '環境裡值得把握的機會。',
    'spread.career.pos.4': '潛在挑戰',
    'spread.career.pos.4.desc': '可能出現的阻力或風險，先做準備。',
    'spread.career.pos.5': '發展建議',
    'spread.career.pos.5.desc': '綜合前五張，牌建議你下一步怎麼做。',
    'spread.wealth.name': '財富流動',
    'spread.wealth.label': '財富流動',
    'spread.wealth.desc': '看你和金錢的關係：錢從哪裡來、從哪裡流失、有什麼機會。牌談的是態度與做法，不涉及任何具體的投資標的。',
    'spread.wealth.pos.0': '財務現況',
    'spread.wealth.pos.0.desc': '目前的財務狀態，以及你對錢的感受。',
    'spread.wealth.pos.1': '財富的來源',
    'spread.wealth.pos.1.desc': '目前或可能的收入來源，或你賺錢的強項。',
    'spread.wealth.pos.2': '金錢的流失',
    'spread.wealth.pos.2.desc': '錢花在哪裡、漏在哪裡，包括習慣與情緒性的消費。',
    'spread.wealth.pos.3': '財務機會',
    'spread.wealth.pos.3.desc': '值得留意的增加收入或改善財務的機會。',
    'spread.wealth.pos.4': '理財建議',
    'spread.wealth.pos.4.desc': '牌建議你對金錢採取的態度或做法。',
    'spread.chakra.name': '脈輪牌陣',
    'spread.chakra.label': '脈輪',
    'spread.chakra.desc': '依印度瑜伽傳統的七個脈輪，由下而上各抽一張，看哪個層面順暢、哪個受阻。脈輪不屬於塔羅傳統，這是現代常見的結合用法。',
    'spread.chakra.pos.0': '海底輪',
    'spread.chakra.pos.0.desc': '安全感與現實基礎：錢、住所、身體是否讓你感到踏實。',
    'spread.chakra.pos.1': '臍輪',
    'spread.chakra.pos.1.desc': '情緒、慾望、創造力，以及享受生活的能力。',
    'spread.chakra.pos.2': '太陽神經叢輪',
    'spread.chakra.pos.2.desc': '自信、意志與行動力：你能不能為自己做決定。',
    'spread.chakra.pos.3': '心輪',
    'spread.chakra.pos.3.desc': '愛、慈悲與人際連結，也包括你怎麼對待自己。',
    'spread.chakra.pos.4': '喉輪',
    'spread.chakra.pos.4.desc': '表達與溝通：說出真話、被聽見的能力。',
    'spread.chakra.pos.5': '眉心輪',
    'spread.chakra.pos.5.desc': '直覺、洞察，以及看清事情的能力。',
    'spread.chakra.pos.6': '頂輪',
    'spread.chakra.pos.6.desc': '意義感、信仰，以及和更大整體的連結。',
    'spread.elements.name': '五元素牌陣',
    'spread.elements.label': '五元素',
    'spread.elements.desc': '火、水、風、土四元素各對應一個花色的領域，再加上把它們整合起來的「靈」，看你生活裡哪一塊充足、哪一塊匱乏。',
    'spread.elements.pos.0': '火',
    'spread.elements.pos.0.desc': '行動、熱情與意志（權杖的領域）：你有沒有動力去做想做的事。',
    'spread.elements.pos.1': '水',
    'spread.elements.pos.1.desc': '情感、關係與直覺（聖杯的領域）：你的感受是否流動、有沒有被照顧。',
    'spread.elements.pos.2': '風',
    'spread.elements.pos.2.desc': '思考、溝通與判斷（寶劍的領域）：你的想法清不清楚、有沒有被困住。',
    'spread.elements.pos.3': '土',
    'spread.elements.pos.3.desc': '金錢、工作與身體（錢幣的領域）：生活的現實基礎穩不穩。',
    'spread.elements.pos.4': '靈',
    'spread.elements.pos.4.desc': '把四者整合起來的核心：此刻什麼讓你覺得完整、有方向。',
    'spread.selfDiscovery.name': '自我探索',
    'spread.selfDiscovery.label': '自我探索',
    'spread.selfDiscovery.desc': '比較你意識到的自己與潛意識裡的自己，找出內在真正的需要與被忽略的部分，再看怎麼把它們整合起來。',
    'spread.selfDiscovery.pos.0': '表意識的你',
    'spread.selfDiscovery.pos.0.desc': '你認為的自己，也是你習慣呈現給別人的樣子。',
    'spread.selfDiscovery.pos.1': '潛意識的你',
    'spread.selfDiscovery.pos.1.desc': '你沒意識到、卻一直在影響你的動機與感受。它和第一張的落差，就是這個牌陣的重點。',
    'spread.selfDiscovery.pos.2': '內在的需要',
    'spread.selfDiscovery.pos.2.desc': '你此刻真正需要的東西，不一定是你以為想要的。',
    'spread.selfDiscovery.pos.3': '被忽略的自己',
    'spread.selfDiscovery.pos.3.desc': '被你壓抑或遺忘的特質、才能或渴望。',
    'spread.selfDiscovery.pos.4': '整合之道',
    'spread.selfDiscovery.pos.4.desc': '把以上幾面整合起來的方法或下一步。',
    'spread.shadow.name': '陰影功課',
    'spread.shadow.label': '陰影功課',
    'spread.shadow.desc': '借用榮格的「陰影」概念：那些你不願承認、卻一直影響你的特質。先看清它的樣子與來源，再找接納與轉化的方式。觸及創傷時，建議與專業諮商師一起進行。',
    'spread.shadow.pos.0': '陰影的面貌',
    'spread.shadow.pos.0.desc': '你不願面對的特質，常常也是你在別人身上特別看不慣的那一點。',
    'spread.shadow.pos.1': '陰影的成因',
    'spread.shadow.pos.1.desc': '它從哪裡來：過去的經驗、成長環境，或某種恐懼。',
    'spread.shadow.pos.2': '它如何影響你',
    'spread.shadow.pos.2.desc': '這個陰影目前在生活裡造成的影響或反覆出現的模式。',
    'spread.shadow.pos.3': '接納的鑰匙',
    'spread.shadow.pos.3.desc': '幫助你承認並接納它的態度或觀點。',
    'spread.shadow.pos.4': '轉化的力量',
    'spread.shadow.pos.4.desc': '接納之後，這個特質可以轉化成的力量或天賦。',
    'spread.dream.name': '夢境解析',
    'spread.dream.label': '夢境解析',
    'spread.dream.desc': '先把夢的內容寫下來再抽牌：看夢的主題、潛意識想提醒什麼、它和現實的關聯，以及醒來後可以怎麼回應。',
    'spread.dream.pos.0': '夢境主題',
    'spread.dream.pos.0.desc': '這個夢的核心主題或情緒。',
    'spread.dream.pos.1': '潛意識訊息',
    'spread.dream.pos.1.desc': '夢背後想提醒你的事。',
    'spread.dream.pos.2': '與現實的關聯',
    'spread.dream.pos.2.desc': '夢反映的是生活裡哪一件事或哪一段關係。',
    'spread.dream.pos.3': '夢的指引',
    'spread.dream.pos.3.desc': '醒來之後可以採取的行動或調整。',
    'spread.celtic.name': '凱爾特十字',
    'spread.celtic.label': '凱爾特十字',
    'spread.celtic.desc': '偉特在《圖像塔羅之鑰》（1911）記載的十張牌陣，適合一個明確的問題。本站用現代常見的編號：第 3 張在下、第 4 張在左、第 5 張在上、第 6 張在右。偉特原書是第 3 張在上、第 4 張在下，第 5、6 張依「指示者」（代表問卜者的那張牌）的人物面向，放在他背後與面前。編號不同，各位置的意義相同。右側一列四張由下往上排。',
    'spread.celtic.pos.0': '現況',
    'spread.celtic.pos.0.desc': '放在中央：你目前的處境，以及籠罩這件事的整體氣氛。',
    'spread.celtic.pos.1': '阻礙',
    'spread.celtic.pos.1.desc': '橫壓在第一張上：阻力或對立的力量。偉特說若這是一張吉牌，表示阻力不大，或某件本身是好事的東西在這件事上反而幫不上忙。',
    'spread.celtic.pos.2': '根基',
    'spread.celtic.pos.2.desc': '放在下方：這件事的基礎與遠因，已經成為事實、你只能以它為起點的部分。',
    'spread.celtic.pos.3': '過去',
    'spread.celtic.pos.3.desc': '放在左邊：剛過去、或正在消退的影響。',
    'spread.celtic.pos.4': '目標',
    'spread.celtic.pos.4.desc': '放在上方：你意識上追求的目標，或在目前條件下最好能達到、但還沒實現的結果。',
    'spread.celtic.pos.5': '未來',
    'spread.celtic.pos.5.desc': '放在右邊：即將發生、在近期起作用的影響。',
    'spread.celtic.pos.6': '態度',
    'spread.celtic.pos.6.desc': '右側一列最下方：你自己在這件事裡的態度與位置。',
    'spread.celtic.pos.7': '環境',
    'spread.celtic.pos.7.desc': '由下往上第二張：身邊的人與環境對這件事的影響。',
    'spread.celtic.pos.8': '希望與恐懼',
    'spread.celtic.pos.8.desc': '由下往上第三張：你對這件事的期待與擔心，兩者常是同一件事的兩面。',
    'spread.celtic.pos.9': '結果',
    'spread.celtic.pos.9.desc': '最上方：綜合前九張，事情最可能的結局。若這張看不出結論，偉特的做法是拿它當新的指示者重排一次；在本站可以把它的主題寫進問題，另做一次占卜。',
    'spread.horseshoe.name': '馬蹄鐵牌陣',
    'spread.horseshoe.label': '馬蹄鐵',
    'spread.horseshoe.desc': '七張牌排成拱形，從左下讀到右下：過去、現在、隱藏的影響，拱頂是眼前的障礙，再到周遭環境、建議與結果。',
    'spread.horseshoe.pos.0': '過去',
    'spread.horseshoe.pos.0.desc': '影響這件事的過往經驗或事件。',
    'spread.horseshoe.pos.1': '現在',
    'spread.horseshoe.pos.1.desc': '目前的狀態與你面對的處境。',
    'spread.horseshoe.pos.2': '隱藏的影響',
    'spread.horseshoe.pos.2.desc': '你沒察覺到、卻正在起作用的因素。',
    'spread.horseshoe.pos.3': '眼前的障礙',
    'spread.horseshoe.pos.3.desc': '位在拱頂：目前最需要克服的困難，也是整個牌陣的轉折點。',
    'spread.horseshoe.pos.4': '周遭環境',
    'spread.horseshoe.pos.4.desc': '身邊的人與環境對這件事的態度與影響。',
    'spread.horseshoe.pos.5': '建議',
    'spread.horseshoe.pos.5.desc': '牌建議你採取的行動或態度。',
    'spread.horseshoe.pos.6': '結果',
    'spread.horseshoe.pos.6.desc': '照建議去做，事情最可能的結果。',
    'spread.treeOfLife.name': '生命之樹',
    'spread.treeOfLife.label': '生命之樹',
    'spread.treeOfLife.desc': '依卡巴拉生命之樹的十個質點排出，每個質點對應生命的一個層面，從最高的靈性（王冠）一路落到現實生活（王國）。適合做整體的人生檢視，不適合單一的是非問題。',
    'spread.treeOfLife.pos.0': '王冠・靈性核心',
    'spread.treeOfLife.pos.0.desc': '最高的目標與靈性方向：你這一生想成為什麼。',
    'spread.treeOfLife.pos.1': '智慧・創造的動力',
    'spread.treeOfLife.pos.1.desc': '推動你的原始動力與靈感，事情最初的火花。',
    'spread.treeOfLife.pos.2': '理解・結構與限制',
    'spread.treeOfLife.pos.2.desc': '讓想法成形的結構、責任與限制，也包括你必須接受的現實。',
    'spread.treeOfLife.pos.3': '仁慈・給予與成長',
    'spread.treeOfLife.pos.3.desc': '你得到的支持與擴展的機會，以及你怎麼慷慨待人。',
    'spread.treeOfLife.pos.4': '嚴厲・紀律與割捨',
    'spread.treeOfLife.pos.4.desc': '需要的紀律與界線，或必須面對的衝突與割捨。',
    'spread.treeOfLife.pos.5': '美・內在平衡',
    'spread.treeOfLife.pos.5.desc': '整棵樹的中心：你的自我認同，也是各種力量取得平衡的地方。',
    'spread.treeOfLife.pos.6': '勝利・情感與慾望',
    'spread.treeOfLife.pos.6.desc': '情感、慾望，以及讓你堅持下去的動力。',
    'spread.treeOfLife.pos.7': '榮耀・思考與溝通',
    'spread.treeOfLife.pos.7.desc': '理性、溝通與學習：你怎麼分析與表達。',
    'spread.treeOfLife.pos.8': '根基・潛意識與習慣',
    'spread.treeOfLife.pos.8.desc': '潛意識、夢與日常習慣，支撐一切的底層模式。',
    'spread.treeOfLife.pos.9': '王國・現實生活',
    'spread.treeOfLife.pos.9.desc': '一切落到現實的樣子：身體、家庭、工作與物質環境。',
    'spread.astroHouses.name': '占星十二宮',
    'spread.astroHouses.label': '占星十二宮',
    'spread.astroHouses.desc': '十二張牌對應占星的十二宮，每一宮代表一個生活領域，適合鳥瞰近期生活各方面的狀態。',
    'spread.astroHouses.pos.0': '第一宮・自我',
    'spread.astroHouses.pos.0.desc': '你給人的第一印象、個人狀態與新的開始。',
    'spread.astroHouses.pos.1': '第二宮・財務',
    'spread.astroHouses.pos.1.desc': '收入、財產，以及你重視的價值。',
    'spread.astroHouses.pos.2': '第三宮・溝通',
    'spread.astroHouses.pos.2.desc': '溝通、學習、短程往來，以及和兄弟姊妹、鄰居的關係。',
    'spread.astroHouses.pos.3': '第四宮・家庭',
    'spread.astroHouses.pos.3.desc': '家庭、居所與內心的根基。',
    'spread.astroHouses.pos.4': '第五宮・創造',
    'spread.astroHouses.pos.4.desc': '創作、戀愛、娛樂，以及和子女的關係。',
    'spread.astroHouses.pos.5': '第六宮・健康',
    'spread.astroHouses.pos.5.desc': '日常工作、作息與健康習慣。',
    'spread.astroHouses.pos.6': '第七宮・伴侶',
    'spread.astroHouses.pos.6.desc': '伴侶、合作對象與一對一的關係。',
    'spread.astroHouses.pos.7': '第八宮・轉化',
    'spread.astroHouses.pos.7.desc': '共有的資源、親密關係、危機與深層的轉變。',
    'spread.astroHouses.pos.8': '第九宮・信念',
    'spread.astroHouses.pos.8.desc': '信仰與人生觀、高等教育、遠行與異國事物。',
    'spread.astroHouses.pos.9': '第十宮・事業',
    'spread.astroHouses.pos.9.desc': '事業、社會地位與公開形象。',
    'spread.astroHouses.pos.10': '第十一宮・人際',
    'spread.astroHouses.pos.10.desc': '朋友、社群，以及你對未來的願景。',
    'spread.astroHouses.pos.11': '第十二宮・潛意識',
    'spread.astroHouses.pos.11.desc': '潛意識、隱藏的事、獨處與休養。',
    'suit.major': '大阿卡納',
    'suit.wands': '權杖',
    'suit.cups': '聖杯',
    'suit.swords': '寶劍',
    'suit.pentacles': '錢幣',
    'orientation.upright': '正位',
    'orientation.reversed': '逆位',
    'tendency.yes': '傾向是',
    'tendency.no': '傾向否',
    'tendency.unclear': '不明朗',
    'history.title': '占卜記錄',
    'history.filter.allSpreads': '所有牌陣',
    'history.filter.allTags': '所有標籤',
    'history.filter.favorite': '只看收藏',
    'history.clear': '清除記錄',
    'history.empty': '尚無符合條件的記錄',
    'history.none': '還沒有占卜記錄',
    'history.none.cta': '開始占卜',
    'history.item.note': '筆記：',
    'history.item.favorite': '收藏',
    'history.item.open': '查看結果：{spread}，{time}',
    'stats.title': '統計分析',
    'stats.empty': '尚無統計資料',
    'stats.readings.title': '占卜次數',
    'stats.readings.unit': '次',
    'stats.cards.title': '總抽牌數',
    'stats.cards.unit': '張',
    'stats.uprightPct.title': '正位比例',
    'stats.reversedPct.title': '逆位比例',
    'stats.orientation.unit': '{n} 張',
    'stats.favorites.title': '收藏數量',
    'stats.favorites.unit': '個收藏',
    'stats.avg.title': '平均每次',
    'stats.avg.unit': '張牌',
    'stats.trend.title': '近 12 個月占卜趨勢',
    'stats.trend.bar': '{month}：{n} 次',
    'stats.suits.title': '花色分布',
    'stats.topSpreads.title': '常用牌陣',
    'stats.topCards.title': '最常抽到的牌',
    'stats.item.count': '{n} 次（{pct}%）',
    'stats.legend.item': '{suit}：{n} 張（{pct}%）',
    'db.title': '資料庫',
    'db.search.placeholder': '搜尋牌名、關鍵詞或牌義…',
    'db.search.label': '搜尋牌卡',
    'db.search.count': '找到 {n} 張牌',
    'db.deckHistory.offline': '知識庫需要網路才能載入，連上網路後重新整理頁面即可。',
    'db.seg.label': '資料庫內容',
    'db.seg.cards': '牌卡',
    'db.seg.library': '知識庫',
    'db.filter.kind': '依類別篩選',
    'db.filter.suit': '依花色篩選',
    'db.filter.all': '全部',
    'db.filter.pip': '數字牌',
    'db.filter.court': '宮廷牌',
    'db.hit.keyword': '正位關鍵詞',
    'db.hit.keywordReversed': '逆位關鍵詞',
    'db.hit.upright': '正位牌義',
    'db.hit.reversed': '逆位牌義',
    'db.hit.symbolism': '牌面描述',
    'db.hit.origin': '源流',
    'db.hit.waite': '偉特 1911 原文語詞',
    'db.hit.waiteAdd': '偉特 1911 補充牌義',
    'db.hit.mofa': 'mofatarot 關鍵詞',
    'db.library.cards': '出現在這些牌',
    'db.seg.symbols': '符號',
    'db.symbols.listTitle': '所有符號',
    'db.symbols.intro': '點一個符號，看它畫在哪些牌上、畫在哪裡。',
    'db.symbols.count': '{n} 張',
    'db.symbols.button': '{title}，{n} 張牌',
    'db.symbols.detail': '畫著{title}的牌',
    'db.symbols.offline': '符號索引需要網路才能載入，連上網路後重新整理頁面即可。',
    'db.filter.corr': '對應',
    'db.hit.alias': '別名',
    'db.hit.names': '其他牌系的名稱',
    'db.hit.symbol': '畫面上的符號',
    'db.hit.study': '學業',
    'db.hit.growth': '成長',
    'db.hit.positions': '放在不同牌位',
    'db.hit.journal': '書寫提問',
    'db.hit.related': '相關的牌',
    'history.filter.spreadLabel': '依牌陣篩選',
    'history.filter.tagLabel': '依標籤篩選',
    'note.label': '筆記內容',
    'db.empty': '尚無符合條件的牌卡',
    'learn.title': '學習',
    'learn.mode.flash': '閃卡',
    'learn.mode.quiz': '測驗',
    'learn.mode.label': '學習方式',
    'learn.scope.label': '學習範圍',
    'learn.scope.all': '全部 78 張',
    'learn.mastery.title': '熟練度',
    'learn.mastery.count': '已掌握 {n} / {total}',
    'learn.mastery.cell': '{name} · 熟練度 {lv}/{max}',
    'learn.mastery.legend': '熟練度圖例',
    'learn.mastery.legend.low': '生疏',
    'learn.mastery.legend.high': '熟練',
    'learn.reset': '重設學習進度',
    'learn.empty.noMeaning': '此範圍沒有可用的牌義，請換一個範圍。',
    'learn.empty.tooFew': '此範圍牌數不足以出題，請換一個範圍。',
    'learn.streak.days': '連續 {n} 天',
    'learn.streak.idle': '今天還沒練習',
    'learn.streak.best': '最佳紀錄 {n} 天',
    'learn.streak.none': '練一張閃卡或答一題測驗就開始計算',
    'learn.streak.continue': '{best} · 今天再練一次就能延續',
    'learn.flash.hint': '點一下看牌義',
    'learn.flash.hard': '還不熟',
    'learn.flash.easy': '記得了',
    'learn.flash.more': '繼續閱讀',
    'learn.flash.less': '收合',
    'learn.flash.progress': '本輪已看 {n} 張',
    'learn.quiz.progress': '第 {n} / {total} 題',
    'learn.quiz.promptArt': '這張牌正位的關鍵詞是？',
    'learn.quiz.promptKeywords': '這組正位關鍵詞屬於哪張牌？',
    'learn.quiz.promptCard': '「{name}」正位的關鍵詞是？',
    'learn.quiz.promptKeywordsReversed': '這組逆位關鍵詞屬於哪張牌？',
    'learn.quiz.promptCardReversed': '「{name}」逆位的關鍵詞是？',
    'learn.quiz.mark.correct': '正確答案',
    'learn.quiz.mark.chosen': '你的答案',
    'learn.quiz.feedback.correct': '答對了',
    'learn.quiz.feedback.wrong': '答錯，正確答案是：{answer}',
    'learn.quiz.explain.pickCard': '你選的是{name}，它的{ori}關鍵詞是：{keywords}。',
    'learn.quiz.explain.pickSet': '你選的是{name}{ori}的關鍵詞。',
    'learn.quiz.viewCard': '看卡片詳情',
    'learn.quiz.next': '下一題',
    'learn.quiz.toResult': '看結果',
    'learn.quiz.score': '答對 {n} / {total}',
    'learn.quiz.rate': '正確率 {pct}%',
    'learn.quiz.reviewTitle': '再複習這幾張',
    'learn.quiz.reviewReversed': '{name}（逆位）',
    'learn.quiz.perfect': '全部答對，這個範圍你已經很熟了。',
    'learn.quiz.again': '再來一輪',
    'learn.quiz.toFlash': '回到閃卡',
    'settings.title': '設定',
    'settings.theme.title': '外觀主題',
    'settings.theme.auto': '跟隨系統',
    'settings.theme.light': '淺色模式',
    'settings.theme.dark': '深色模式',
    'settings.theme.neon': '霓虹占卜館',
    'settings.theme.neon.desc': '深夜藍黑與霓虹光，線稿模式的牌依花色發光',
    'settings.theme.neon.descTemplate': '霓虹外觀只在「簡約」版型；其他版型會以深色模式顯示',
    'settings.template.title': '版型',
    'settings.template.minimal': '簡約',
    'settings.template.minimal.desc': '原本的版面：上方分頁列，黑白色調',
    'settings.template.aurora': '星夜玻璃',
    'settings.template.aurora.desc': '夜藍與淡紫、霧面玻璃與柔金，下方浮動導覽列',
    'settings.template.editorial': '現代編輯',
    'settings.template.editorial.desc': '冷灰與墨黑、一抹朱紅，雜誌式大標題與方塊版面',
    'settings.template.immersive': '沉浸手勢',
    'settings.template.immersive.desc': '鼠尾草綠，牌堆當首頁：向上滑動抽牌，左右滑動換牌',
    'settings.visual.title': '視覺樣式',
    'settings.visual.text': '純文字模式（預設）',
    'settings.visual.text.desc': '只顯示牌名、正逆位與關鍵詞，不載入圖片。',
    'settings.visual.api': '牌圖模式',
    'settings.visual.api.desc': '1909 年版偉特牌的原始牌圖（公有領域）。看過的牌圖會留在裝置上，離線也能顯示。',
    'settings.visual.line': '線稿模式',
    'settings.visual.name.text': '純文字模式',
    'settings.visual.name.api': '牌圖模式',
    'settings.visual.name.line': '線稿模式',
    'settings.visual.line.desc': '本站自繪的 78 張彩色插畫，構圖依循偉特牌。',
    'settings.pref.title': '顯示偏好',
    'settings.pref.interactiveDraw': '互動選牌',
    'settings.pref.interactiveDraw.desc': '占卜時親手從牌堆中選牌；關閉則直接翻出結果',
    'settings.pref.spreadInfo': '顯示牌陣說明',
    'settings.pref.spreadInfo.desc': '在牌陣選單與「關於此牌陣」顯示牌陣說明與牌位讀法（逐張解讀照常列出牌位讀法）',
    'settings.pref.shortcuts': '啟用鍵盤快捷鍵',
    'settings.pref.shortcuts.desc': '空白鍵＝開始占卜　T＝切換主題　1–6＝切換分頁',
    'settings.pref.haptics': '觸覺回饋',
    'settings.pref.haptics.desc': '抽牌與翻牌時輕輕震動（裝置支援時）',
    'settings.data.title': '資料管理',
    'settings.data.stats': '目前共 {n} 筆占卜記錄（上限 {max} 筆），約佔 {kb} KB 儲存空間。',
    'settings.data.export': '匯出資料',
    'settings.data.import': '匯入資料',
    'settings.data.clearAll': '清除所有資料',
    'shichen.unknown': '不詳',
    'shichen.0': '子　23:00–01:00',
    'shichen.1': '丑　01:00–03:00',
    'shichen.2': '寅　03:00–05:00',
    'shichen.3': '卯　05:00–07:00',
    'shichen.4': '辰　07:00–09:00',
    'shichen.5': '巳　09:00–11:00',
    'shichen.6': '午　11:00–13:00',
    'shichen.7': '未　13:00–15:00',
    'shichen.8': '申　15:00–17:00',
    'shichen.9': '酉　17:00–19:00',
    'shichen.10': '戌　19:00–21:00',
    'shichen.11': '亥　21:00–23:00',
    'profile.title': '個人化',
    'profile.birthday.label': '你的生日',
    'profile.shichen.label': '出生時辰',
    'profile.desc': '用生日與出生時辰算出你的五張個人牌，顯示在占卜分頁上方。生日與時辰只存在這台裝置。',
    'profile.clear': '清除生日',
    'profile.empty': '尚未設定生日',
    'profile.preview.item': '{pos}：{name} {ori}',
    'profile.pos.origin': '源',
    'profile.pos.inheritance': '承',
    'profile.pos.self': '身',
    'profile.pos.legacy': '續',
    'profile.pos.return': '歸',
    'profile.note.deal.title': '這五張牌怎麼來的',
    'profile.note.deal.text': '用你的生日與出生時辰，從 78 張牌裡不放回地發出五張，每張各有正位或逆位。同一組生日與時辰永遠得到同樣的五張；不同的日期或時辰（「不詳」也算一種）各得一組，不會有兩組完全相同。五張依序是——源：你的起點與根源；承：你從家庭或過去承接下來的東西；身：現在的你；續：你想延續、留給別人的東西；歸：你最終想走向的地方。',
    'profile.note.frame.title': '源、承、身、續、歸是本站自訂的',
    'profile.note.frame.text': '這五個位置不出自任何塔羅或命理傳統，是本站設計的讀牌框架。五個位置同等重要，沒有主次之分。',
    'profile.note.shichen.title': '時辰只用來計時',
    'profile.note.shichen.text': '十二時辰是中國傳統的計時法，一個時辰兩小時。八字（四柱）也用它定出時柱，但本站只借用計時，不套用八字的柱義與命理解釋。子時跨過午夜，本站不做早子時、晚子時的換日：日期就是你填的那一天。',
    'profile.note.legacy.title': '與常見的「生日牌」算法不同',
    'profile.note.legacy.text': 'Mary K. Greer 在《Tarot for Your Self》（1984）推廣的生日牌，是把出生的月、日、年相加，再把各位數反覆相加化簡，得出大阿卡納裡的「人格牌」與「靈魂牌」，所以很多人會得到同一組。本站不做數字化簡，而是照上面的方式從全部 78 張裡發牌。',
    'profile.note.closing': '同樣的五張牌會一直跟著你，適合在不同時期回頭重讀，看看自己對它們的理解有什麼改變。',
    'card.loading': '載入中…',
    'card.imageFailed': '圖片暫時無法載入',
    'card.sub': '{en} · {suit} · {number}',
    'card.sub.minor': '{en} · {suit}',
    'card.sub.drawn': '{sub} · 本次抽到{ori}',
    'card.meaning.drawn': '（本次抽到）',
    'card.seg.label': '卡片內容',
    'card.seg.meaning': '牌義',
    'card.seg.icon': '圖義',
    'card.seg.context': '情境',
    'card.seg.lore': '源流',
    'card.viewArt': '放大檢視「{name}」的牌面',
    'card.viewer.title': '{name}的牌面',
    'card.depth.title': '深度解說',
    'card.symbolism.title': '牌面描述',
    'card.icon.title': '符號解讀',
    'card.image.upright': '正位圖面',
    'card.image.reversed': '逆位圖面',
    'card.context.title': '情境牌義',
    'card.context.love': '感情',
    'card.context.career': '事業',
    'card.context.wealth': '財務',
    'card.context.wellbeing': '身心',
    'card.context.study': '學業',
    'card.context.growth': '成長',
    'card.positions.title': '放在不同牌位',
    'card.positions.advice': '建議',
    'card.positions.obstacle': '阻礙',
    'card.positions.outcome': '結果',
    'card.journal.label': '書寫提問',
    'refs.related.title': '相關的牌',
    'refs.kind.similar': '相似',
    'refs.kind.contrast': '對照',
    'refs.kind.sequence': '延續',
    'refs.kind.pair': '呼應',
    'refs.names.title': '其他牌系的名稱',
    'refs.names.marseille': '馬賽牌',
    'refs.names.thoth': '托特牌',
    'refs.names.italian': '義大利古名',
    'refs.names.aliases': '中文常見別名',
    'refs.names.thothNumbered': '{name}（{n}）',
    'refs.names.thothAlt': '另一種對法：{name}',
    'refs.names.help': '說明',
    'refs.timing.label': '對應日期',
    'refs.timing.range': '約 {from}–{to}（{what}）',
    'refs.timing.date': '{m} 月 {d} 日',
    'refs.timing.febEnd': '2 月底',
    'refs.timing.decan': '{planet}在{sign}的旬',
    'refs.symbols.title': '畫面上的符號',
    'refs.symbols.rwsOnly': '（僅原版牌圖）',
    'refs.symbols.lineOnly': '（僅線稿牌組）',
    'compare.open': '比較',
    'compare.open.label': '拿{name}和另一張牌比較',
    'compare.title': '比較兩張牌',
    'compare.filter.label': '搜尋第二張牌',
    'compare.filter.placeholder': '輸入牌名、英文名或別名…',
    'compare.filter.count': '{n} 張牌符合',
    'compare.pick.label': '第二張牌',
    'compare.pick.none': '請選擇',
    'compare.empty': '選好第二張牌，兩張的重點會並排列出。',
    'compare.row.keywords': '關鍵詞',
    'compare.row.yesno': '是非傾向',
    'compare.row.attr': '元素與對應',
    'compare.row.names': '其他牌系的名稱',
    'compare.row.timing': '對應日期',
    'compare.row.symbols': '共同的符號',
    'compare.row.related': '兩張牌的關係',
    'compare.none': '無',
    'compare.symbols.none': '沒有共同的符號',
    'compare.related.none': '兩張牌沒有被列為相關的牌。',
    'compare.related.dir': '從{from}看：',
    'compare.loadFailed': '部分資料需要網路才能載入。',
    'card.context.yesno': '是非',
    'card.reflection.label': '反思',
    'card.lore.empty': '這張牌的源流資料尚未收錄。',
    'card.origin.title': '這張牌的源流',
    'card.lore.more': '延伸閱讀',
    'card.lore.more.note': '同類牌共用的背景收在資料庫的知識庫；點選會關閉卡片詳情，前往那一段。',
    'card.lore.related': '同樣的符號也出現在',
    'card.sources.lead': '以上各組語詞的出處與差異：',
    'card.sources.link': '來源說明',
    'error.chunkOffline': '需要網路，請重新整理',
    'about.title': '關於本站',
    'about.intro': '以偉特塔羅（Rider–Waite–Smith，1909）為本的占卜與學習工具。牌義綜合偉特《圖像塔羅之鑰》（1911）與現代主流讀法。卡片詳情另外並列「偉特 1911 原文語詞」「偉特 1911 補充牌義」「mofatarot 關鍵詞」，以及黃金黎明與 Thierens（1930）兩套對應系統，各自分開列出、不合併成一套；它們的出處與差異寫在資料庫的知識庫裡。牌圖模式用的是 1909 年版的原始牌圖，屬公有領域，隨網站提供、不連外。占卜結果僅供參考，不能取代醫療、法律或財務等專業意見。',
    'about.changelog.empty': '尚無更新紀錄。',
    'privacy.title': '隱私政策',
    'privacy.noCollect': '不收集任何個人資料，也不需要帳號',
    'privacy.noTracking': '不使用任何分析或追蹤工具',
    'privacy.localOnly': '占卜記錄、筆記、生日與學習進度只存在這台裝置的瀏覽器裡；清除網站資料會一併刪除，需要時請先在設定裡匯出備份',
    'privacy.shareLink': '分享連結裡的問題放在網址 # 後面：瀏覽器開啟連結時只在本機讀取，不會傳到網站的伺服器；不過收到連結的人看得到你的問題',
    'insight.panel.title': '綜合觀察',
    'insight.panel.note': '標題後的百分比，是「完全隨機抽牌時，出現這種或更極端情況」的機率（有些項目要同時比較多種可能，列的是校正後的上限），低於 5% 才會列出；後面附的是常見的塔羅讀法，僅供參考。',
    'insight.prob.is': '是 {p}',
    'insight.prob.atMost': '不超過 {p}',
    'insight.prob.below': '低於 0.1%',
    'insight.major.tag': '大阿卡納密集 · {p}',
    'insight.major.text': '{n} 張牌裡有 {k} 張大阿卡納：{cards}。這副 {N} 張的牌組有 {K} 張大阿卡納，平均只會抽到 {exp} 張；抽到這麼多或更多的機率{prob}。',
    'insight.suit.tag': '{suit}主導 · {p}',
    'insight.suit.text': '{n} 張牌裡有 {k} 張{suit}：{cards}。純隨機抽到這麼集中的機率{prob}（已按四個花色校正）。',
    'insight.reversed.tag': '逆位偏多 · {p}',
    'insight.reversed.text': '{n} 張裡有 {k} 張逆位。每張牌正逆位的機會各半，逆位這麼多或更多的機率{prob}。',
    'insight.upright.tag': '正位偏多 · {p}',
    'insight.upright.text': '{n} 張裡有 {k} 張正位。每張牌正逆位的機會各半，正位這麼多或更多的機率{prob}。',
    'insight.hint.major': '大阿卡納多，傳統上表示牽涉的是人生層次的課題或轉折，不只是日常瑣事；讀的時候先看大阿卡納定下的方向，再用小阿卡納補細節。',
    'insight.hint.suit': '{suit}屬{element}元素，管的是{faculty}：問題多半落在這個領域。',
    'insight.hint.reversed': '逆位多，常見的讀法是事情受阻、延遲，或能量轉向內在、還沒表現出來；先找出卡住的地方，不必當成凶兆。',
    'insight.hint.upright': '正位多，表示牌的能量大多順暢、直接地表現出來，事情比較照牌面的意思發展。',
    'insight.hint.court': '宮廷牌多，表示「人」是重點：可能是牽涉其中的人，也可能是你正在扮演的角色或該採取的態度。',
    'insight.hint.pip': '數字牌多，表示事情多半落在日常、具體的層次，靠實際的步驟就能推動。',
    'insight.recur.tag': '{n} 張{ori}{rank}',
    'insight.recur.text': '這次有 {n} 張{ori}的{rank}：{cards}。偉特《圖像塔羅之鑰》（1911）第三部第五節列出同一點數或階級重複出現時的意義，這個組合是「{term}」。',
    'insight.recur.text.both': '這次有 {n} 張{ori}的{rank}：{cards}。偉特《圖像塔羅之鑰》（1911）第三部第五節的讀法是「{term}」；Foli《Fortune-Telling by Cards》（1915）第四章的讀法是「{foli}」——Foli 的規則原本是給一般撲克牌用的，兩者可以對照著看。',
    'rank.label.ace': '一號牌',
    'rank.label.two': '二號牌',
    'rank.label.three': '三號牌',
    'rank.label.four': '四號牌',
    'rank.label.five': '五號牌',
    'rank.label.six': '六號牌',
    'rank.label.seven': '七號牌',
    'rank.label.eight': '八號牌',
    'rank.label.nine': '九號牌',
    'rank.label.ten': '十號牌',
    'rank.label.page': '侍者',
    'rank.label.knight': '騎士',
    'rank.label.queen': '皇后',
    'rank.label.king': '國王',
    'waite.recur.natural.king.4': '大榮譽',
    'waite.recur.natural.king.3': '商議',
    'waite.recur.natural.king.2': '小忠告',
    'waite.recur.natural.queen.4': '大爭論',
    'waite.recur.natural.queen.3': '受女性欺瞞',
    'waite.recur.natural.queen.2': '真誠的朋友',
    'waite.recur.natural.knight.4': '嚴肅的事',
    'waite.recur.natural.knight.3': '熱烈的辯論',
    'waite.recur.natural.knight.2': '親密',
    'waite.recur.natural.page.4': '危險的疾病',
    'waite.recur.natural.page.3': '爭執',
    'waite.recur.natural.page.2': '不安',
    'waite.recur.natural.ten.4': '定罪',
    'waite.recur.natural.ten.3': '新的處境',
    'waite.recur.natural.ten.2': '改變',
    'waite.recur.natural.nine.4': '一位好朋友',
    'waite.recur.natural.nine.3': '成功',
    'waite.recur.natural.nine.2': '收受',
    'waite.recur.natural.eight.4': '挫折',
    'waite.recur.natural.eight.3': '婚姻',
    'waite.recur.natural.eight.2': '新的知識',
    'waite.recur.natural.seven.4': '密謀',
    'waite.recur.natural.seven.3': '體弱',
    'waite.recur.natural.seven.2': '消息',
    'waite.recur.natural.six.4': '豐盛',
    'waite.recur.natural.six.3': '成功',
    'waite.recur.natural.six.2': '易怒',
    'waite.recur.natural.five.4': '規律',
    'waite.recur.natural.five.3': '決心',
    'waite.recur.natural.five.2': '守夜',
    'waite.recur.natural.four.4': '近在眼前的旅程',
    'waite.recur.natural.four.3': '一個值得反覆思索的主題',
    'waite.recur.natural.four.2': '失眠',
    'waite.recur.natural.three.4': '進展',
    'waite.recur.natural.three.3': '合一',
    'waite.recur.natural.three.2': '平靜',
    'waite.recur.natural.two.4': '爭端',
    'waite.recur.natural.two.3': '安全',
    'waite.recur.natural.two.2': '和諧一致',
    'waite.recur.natural.ace.4': '有利的機緣',
    'waite.recur.natural.ace.3': '小小的成功',
    'waite.recur.natural.ace.2': '詭計',
    'waite.recur.reversed.king.4': '迅捷',
    'waite.recur.reversed.king.3': '商務往來',
    'waite.recur.reversed.king.2': '計畫',
    'waite.recur.reversed.queen.4': '壞的同伴',
    'waite.recur.reversed.queen.3': '暴食',
    'waite.recur.reversed.queen.2': '工作',
    'waite.recur.reversed.knight.4': '結盟',
    'waite.recur.reversed.knight.3': '一場決鬥，或當面的衝突',
    'waite.recur.reversed.knight.2': '易受影響',
    'waite.recur.reversed.page.4': '匱乏',
    'waite.recur.reversed.page.3': '怠惰',
    'waite.recur.reversed.page.2': '交際',
    'waite.recur.reversed.ten.4': '事件發生',
    'waite.recur.reversed.ten.3': '失望',
    'waite.recur.reversed.ten.2': '期待得到印證',
    'waite.recur.reversed.nine.4': '放高利貸',
    'waite.recur.reversed.nine.3': '輕率',
    'waite.recur.reversed.nine.2': '小額獲利',
    'waite.recur.reversed.eight.4': '錯誤',
    'waite.recur.reversed.eight.3': '一場熱鬧的場面',
    'waite.recur.reversed.eight.2': '不幸',
    'waite.recur.reversed.seven.4': '好爭吵的人',
    'waite.recur.reversed.seven.3': '喜悅',
    'waite.recur.reversed.seven.2': '名聲不佳的女子',
    'waite.recur.reversed.six.4': '掛慮',
    'waite.recur.reversed.six.3': '滿足',
    'waite.recur.reversed.six.2': '垮台',
    'waite.recur.reversed.five.4': '秩序',
    'waite.recur.reversed.five.3': '猶豫',
    'waite.recur.reversed.five.2': '挫折',
    'waite.recur.reversed.four.4': '外出走動',
    'waite.recur.reversed.four.3': '不安',
    'waite.recur.reversed.four.2': '爭執',
    'waite.recur.reversed.three.4': '大成功',
    'waite.recur.reversed.three.3': '寧靜',
    'waite.recur.reversed.three.2': '安全無虞',
    'waite.recur.reversed.two.4': '和解',
    'waite.recur.reversed.two.3': '憂懼',
    'waite.recur.reversed.two.2': '不信任',
    'waite.recur.reversed.ace.4': '不名譽',
    'waite.recur.reversed.ace.3': '放蕩',
    'waite.recur.reversed.ace.2': '敵人',
    'foli.recur.natural.ace.4': '危險、破財、與朋友離散、感情上的麻煩，某些情況下還有牢獄之災',
    'foli.recur.natural.ace.3': '一時的麻煩，由好消息化解',
    'foli.recur.natural.king.4': '榮銜、擢升、好職位',
    'foli.recur.natural.king.2': '生意上的合作',
    'foli.recur.natural.queen.3': '友善的造訪',
    'foli.recur.reversed.queen.3': '醜聞、流言',
    'foli.recur.natural.queen.2': '交換瑣碎的私語、祕密被洩露、朋友間的會面',
    'foli.recur.natural.ten.4': '好運、財富',
    'foli.recur.natural.ten.2': '意外的好運',
    'foli.recur.natural.nine.4': '意外之事成真',
    'foli.recur.natural.nine.3': '健康、財富、幸福',
    'foli.recur.natural.nine.2': '興旺與滿足、遺囑文件',
    'foli.recur.reversed.nine.2': '小煩惱',
    'foli.recur.reversed.eight.4': '不受擾動的安定',
    'foli.recur.natural.eight.3': '新的家庭關係、有意成婚的正當心意',
    'foli.recur.reversed.eight.3': '調情、放蕩與愚行',
    'foli.recur.natural.eight.2': '輕浮的享樂、一時的戀慕、意料之外的發展',
    'foli.recur.natural.seven.4': '算計與圈套、爭執與對立',
    'foli.recur.natural.seven.3': '健康不佳、悔恨',
    'foli.recur.natural.seven.2': '兩情相悅、一件意外的事',
    'foli.recur.reversed.seven.2': '不忠、欺瞞或悔恨',
    'insight.class.court.tag': '宮廷牌密集 · {p}',
    'insight.class.court.text': '{n} 張牌裡有 {k} 張宮廷牌：{cards}。這副 {N} 張的牌組有 {K} 張宮廷牌，平均只會抽到 {exp} 張；抽到這麼多或更多的機率{prob}。',
    'insight.class.pip.tag': '數字牌密集 · {p}',
    'insight.class.pip.text': '{n} 張牌裡有 {k} 張數字牌。這副 {N} 張的牌組有 {K} 張數字牌，平均會抽到 {exp} 張；抽到這麼多或更多的機率{prob}。',
    'insight.quality.tag': '{quality}星座 · {p}',
    'insight.quality.text': '你抽到的大阿卡納裡，有 {k} 張在 Thierens（《General Book of the Tarot》，1930）的系統裡對應到星座，而且全是{quality}星座。他的十二張星座牌每種性質各 4 張，隨機抽到的星座牌全屬同一種性質（不限哪一種）的機率{prob}。{qdesc}這是 Thierens 自己的對應，與本站採用的黃金黎明系統不同，只當作另一個角度。',
    'quality.cardinal': '開創',
    'quality.fixed': '固定',
    'quality.mutable': '變動',
    'quality.cardinal.desc': '開創星座主導起頭與開拓：事情多半處在要你主動開始的階段。',
    'quality.fixed.desc': '固定星座主導維持與堅持：事情往往需要耐力，也可能卡在不肯改變。',
    'quality.mutable.desc': '變動星座主導調整與轉換：事情多半正在變化，彈性比堅持更重要。',
    'mofa.terms.title': 'mofatarot 關鍵詞',
    'waite.terms.title': '偉特 1911 原文語詞',
    'waite.terms.upright': '正位',
    'waite.terms.reversed': '逆位',
    'waite.additional.title': '偉特 1911 補充牌義',
    'court.looks.title': '這張牌常指向的人',
    'court.looks.wands': '髮色金黃或赤褐、膚色白皙、藍眼',
    'court.looks.cups': '髮色淺褐或暗金、灰眼或藍眼',
    'court.looks.swords': '髮色深褐、榛色或灰眼、膚色偏暗',
    'court.looks.pentacles': '髮色深褐或黑、深色眼睛、膚色偏黃或黝黑',
    'court.looks.note': '偉特挑選「指示者」時用的外貌對照；現代讀法多看性情與角色。',
    'suit.faculty.wands': '行動、熱情、意志',
    'suit.faculty.cups': '情感、關係、直覺',
    'suit.faculty.swords': '思考、溝通、判斷',
    'suit.faculty.pentacles': '金錢、工作、身體',
    'systems.title': '對應系統',
    'systems.std.source': '標準系統（本站預設）',
    'systems.std.note': '元素、稱號、旬位與質點出自黃金黎明一系（《T 之書》、《777》）；面向是本站的概括，撲克花色是通行的對照。',
    'systems.guide.lead': '各欄的意思：',
    'systems.guide.link': '對應系統怎麼讀',
    'systems.std.note.court': '黃金黎明替宮廷牌另配的位階元素與旬位，這裡不採用，只列花色本身的對應。',
    'systems.std.note.major': '黃金黎明的大阿卡納對應（《T 之書》、《777》）；字母的中文名只是音譯。',
    'systems.thierens.source': 'Thierens 1930',
    'systems.thierens.note': '宮位與星座是 Thierens 自己的排法，和標準系統的旬位無關。',
    'systems.thierens.note.major': 'Thierens 自己的大阿卡納星象對應，沿用正義 VIII、力量 XI 的舊序，從魔術師的牡羊座依序排下。',
    'systems.thierens.note.clash': 'Thierens 給這個花色配的元素和標準系統不同；本站牌義依標準系統。',
    'systems.label.element': '元素',
    'systems.label.faculty': '面向',
    'systems.label.french': '撲克花色',
    'systems.label.planet': '行星',
    'systems.label.sign': '星座',
    'systems.label.house': '宮位',
    'systems.label.quality': '性質',
    'systems.label.triplicity': '星座元素',
    'systems.label.letter': '字母',
    'systems.label.tree': '生命之樹',
    'systems.label.decan': '旬位',
    'systems.label.gdTitle': '稱號',
    'systems.house': '第 {n} 宮',
    'systems.letter': '{letter} {name}（{zh}）',
    'systems.path': '第 {n} 條路徑',
    'systems.decan': '{planet}在{sign}',
    'systems.attr.fireSpirit': '火（也對應靈）',
    'systems.attr.saturnEarth': '土星（也對應土元素）',
    'systems.sephira.1': '第一質點・王冠（Kether）：原動天',
    'systems.sephira.2': '第二質點・智慧（Chokmah）：黃道帶',
    'systems.sephira.3': '第三質點・理解（Binah）：土星',
    'systems.sephira.4': '第四質點・仁慈（Chesed）：木星',
    'systems.sephira.5': '第五質點・嚴厲（Geburah）：火星',
    'systems.sephira.6': '第六質點・美（Tiphareth）：太陽',
    'systems.sephira.7': '第七質點・勝利（Netzach）：金星',
    'systems.sephira.8': '第八質點・榮耀（Hod）：水星',
    'systems.sephira.9': '第九質點・根基（Yesod）：月亮',
    'systems.sephira.10': '第十質點・王國（Malkuth）：地球（四元素）',
    'systems.gdTitle.ace_of_wands': '火之力量的根源（Root of the Powers of Fire）',
    'systems.gdTitle.two_of_wands': '統治之主（Lord of Dominion）',
    'systems.gdTitle.three_of_wands': '穩固力量之主（Lord of Established Strength）',
    'systems.gdTitle.four_of_wands': '圓滿工作之主（Lord of Perfected Work）',
    'systems.gdTitle.five_of_wands': '爭鬥之主（Lord of Strife）',
    'systems.gdTitle.six_of_wands': '勝利之主（Lord of Victory）',
    'systems.gdTitle.seven_of_wands': '勇氣之主（Lord of Valour）',
    'systems.gdTitle.eight_of_wands': '迅捷之主（Lord of Swiftness）',
    'systems.gdTitle.nine_of_wands': '強大力量之主（Lord of Great Strength）',
    'systems.gdTitle.ten_of_wands': '壓迫之主（Lord of Oppression）',
    'systems.gdTitle.ace_of_cups': '水之力量的根源（Root of the Powers of Water）',
    'systems.gdTitle.two_of_cups': '愛之主（Lord of Love）',
    'systems.gdTitle.three_of_cups': '豐盛之主（Lord of Abundance）',
    'systems.gdTitle.four_of_cups': '混雜歡愉之主（Lord of Blended Pleasure）',
    'systems.gdTitle.five_of_cups': '歡愉中的失落之主（Lord of Loss in Pleasure）',
    'systems.gdTitle.six_of_cups': '歡愉之主（Lord of Pleasure）',
    'systems.gdTitle.seven_of_cups': '虛幻成功之主（Lord of Illusionary Success）',
    'systems.gdTitle.eight_of_cups': '放棄成功之主（Lord of Abandoned Success）',
    'systems.gdTitle.nine_of_cups': '物質幸福之主（Lord of Material Happiness）',
    'systems.gdTitle.ten_of_cups': '圓滿成功之主（Lord of Perfected Success）',
    'systems.gdTitle.ace_of_swords': '風之力量的根源（Root of the Powers of Air）',
    'systems.gdTitle.two_of_swords': '恢復和平之主（Lord of Peace Restored）',
    'systems.gdTitle.three_of_swords': '悲傷之主（Lord of Sorrow）',
    'systems.gdTitle.four_of_swords': '爭鬥後的休憩之主（Lord of Rest from Strife）',
    'systems.gdTitle.five_of_swords': '挫敗之主（Lord of Defeat）',
    'systems.gdTitle.six_of_swords': '應得成功之主（Lord of Earned Success）',
    'systems.gdTitle.seven_of_swords': '不穩努力之主（Lord of Unstable Effort）',
    'systems.gdTitle.eight_of_swords': '力量縮減之主（Lord of Shortened Force）',
    'systems.gdTitle.nine_of_swords': '絕望與殘酷之主（Lord of Despair and Cruelty）',
    'systems.gdTitle.ten_of_swords': '毀滅之主（Lord of Ruin）',
    'systems.gdTitle.ace_of_pentacles': '土之力量的根源（Root of the Powers of Earth）',
    'systems.gdTitle.two_of_pentacles': '和諧變化之主（Lord of Harmonious Change）',
    'systems.gdTitle.three_of_pentacles': '物質工作之主（Lord of Material Works）',
    'systems.gdTitle.four_of_pentacles': '塵世權力之主（Lord of Earthly Power）',
    'systems.gdTitle.five_of_pentacles': '物質困境之主（Lord of Material Trouble）',
    'systems.gdTitle.six_of_pentacles': '物質成功之主（Lord of Material Success）',
    'systems.gdTitle.seven_of_pentacles': '未竟成功之主（Lord of Success Unfulfilled）',
    'systems.gdTitle.eight_of_pentacles': '審慎之主（Lord of Prudence）',
    'systems.gdTitle.nine_of_pentacles': '物質收穫之主（Lord of Material Gain）',
    'systems.gdTitle.ten_of_pentacles': '財富之主（Lord of Wealth）',
    'element.fire': '火',
    'element.water': '水',
    'element.air': '風',
    'element.earth': '土',
    'french.clubs': '梅花',
    'french.hearts': '紅心',
    'french.spades': '黑桃',
    'french.diamonds': '方塊',
    'planet.saturn': '土星',
    'planet.jupiter': '木星',
    'planet.mars': '火星',
    'planet.sun': '太陽',
    'planet.venus': '金星',
    'planet.mercury': '水星',
    'planet.moon': '月亮',
    'planet.earth': '地球',
    'planet.uranus': '天王星',
    'planet.neptune': '海王星',
    'sign.aries': '牡羊座',
    'sign.taurus': '金牛座',
    'sign.gemini': '雙子座',
    'sign.cancer': '巨蟹座',
    'sign.leo': '獅子座',
    'sign.virgo': '處女座',
    'sign.libra': '天秤座',
    'sign.scorpio': '天蠍座',
    'sign.sagittarius': '射手座',
    'sign.capricorn': '摩羯座',
    'sign.aquarius': '水瓶座',
    'sign.pisces': '雙魚座',
    'insight.echo.tag': '共同語詞 · {term}',
    'insight.echo.text': '{cards}都帶著「{term}」這個語詞；整副 {N} 張牌裡只有 {K} 張有它。（出處：{src}）',
    'insight.echo.text.multi': '{cards}都帶著這些語詞：{term}。其中最少見的是「{best}」，整副 {N} 張牌裡只有 {K} 張有它。（出處：{src}）',
    'insight.echo.text.multiSrc': '{cards}在 {m} 個來源裡都有相同的語詞：{parts}。',
    'insight.echo.part': '「{terms}」（{src}）',
    'insight.echo.net.tag': '語詞交會 · {hub}',
    'insight.echo.net.text': '{hub}和其他幾張牌都有共同的語詞：{links}。它是這次牌面的交會點，可以從它讀起。',
    'insight.echo.net.link': '與{others}共享{parts}',
    'insight.echo.net.extra': '{cards}另外共享{parts}',
    'insight.card.pos': '{name}（{ori}・{pos}）',
    'insight.card.bottom': '底牌{name}（{ori}）',
    'insight.profile.tag': '牌面剖面',
    'insight.profile.text': '{n} 張牌：大阿卡納 {maj}、宮廷牌 {court}、數字牌 {pip}，逆位 {rev} 張；小阿卡納的元素：{els}。',
    'insight.profile.text.noMinors': '{n} 張牌全是大阿卡納，逆位 {rev} 張。',
    'insight.profile.el': '{el} {k}',
    'insight.axis.tag': '{p1}×{p2}',
    'insight.axis.rank.text': '「{p1}」與「{p2}」抽到同一個數字或階級：{c1}、{c2}都是{rank}。這兩個位置本來就該對照著讀；數字或階級相同，表示兩端處在同一個發展階段，差別在花色，也就是落在不同的領域。',
    'insight.axis.suit.tag': '時間線同花色',
    'insight.axis.suit.text': '時間軸上的三張牌（過去、現在、未來）都是{suit}：{cards}。事情一路沒有離開這個領域，變的是走到哪個階段，可以比較三張牌的點數或階級來看。',
    'insight.axis.suit.merge': '而且過去、現在、未來三個位置都是{suit}：事情一路沒有離開這個領域，可以比較這三張的點數或階級，看它走到哪個階段。',
    'insight.axis.suit.merge.exact': '這三張正好佔滿過去、現在、未來：事情一路沒有離開這個領域，可以比較它們的點數或階級，看它走到哪個階段。',
    'insight.echo.card': '{name}（{ori}）',
    'insight.echo.pair': '{zh}（{en}）',
    'insight.echo.src.ours': '本站正逆位關鍵詞',
    'insight.echo.src.mofa': 'mofatarot 正逆位關鍵詞',
    'insight.echo.src.waite': '偉特 1911 原文語詞',
    'insight.echo.src.add': '偉特 1911 補充牌義',
    'insight.balanced.tag': '無顯著偏向',
    'insight.balanced.text': '花色、大阿卡納、宮廷牌與數字牌的比例、正逆位、同點數或階級的重複、共同語詞與位置對照都檢查過了，這次的牌面沒有特別的集中或重複，直接看每張牌在各自位置上的意思即可。',
    'insight.balanced.small': '（只有 {n} 張牌時，本來就很少出現明顯的集中。）',
    'insight.bottom.tag': '底牌基調',
    'insight.bottom.text': '底牌{name}（{ori}）不單獨論吉凶：讀完各張牌後，回頭想想它代表的{kw}，是不是一直在這件事底下起作用。',
    'insight.bottom.text.noKeywords': '底牌{name}（{ori}）不單獨論吉凶：讀完各張牌後，回頭想想它的主題是不是一直在這件事底下起作用。',
    'pattern.panel.title': '模式洞察',
    'pattern.panel.sub': '來自你的 {n} 次占卜',
    'pattern.panel.note': '依你全部的占卜記錄計算，只算牌陣裡抽出的牌，不含底牌。標出的機率是完全隨機時出現這種或更極端分布的機率（同時比較多個花色、標籤或多種牌時是校正後的上限），低於 5% 才列出；後面附的讀法僅供參考。',
    'pattern.none.tag': '尚未開始',
    'pattern.none.text': '占卜記錄滿 5 次後，這裡會開始分析你長期抽到的牌。',
    'pattern.building.tag': '尚在累積',
    'pattern.building.text': '再占卜 {n} 次，這裡就會開始分析你的長期記錄：哪個花色特別常出現、某個標籤底下的牌有什麼傾向、哪張牌一再出現。',
    'pattern.dominant.tag': '{suit}長期主導',
    'pattern.dominant.text': '你的 {total} 張牌裡有 {k} 張{suit}（{pct}%，平均應是 {exp} 張）。純隨機出現這麼集中的機率{prob}（已按四個花色校正）。',
    'pattern.tag.tag': '標籤「{name}」',
    'pattern.tag.text': '你標記為「{name}」的 {n} 次占卜共 {m} 張牌，其中{suit}佔 {k} 張（{pct}%）。純隨機出現這麼集中的機率{prob}（已按花色與標籤的數量校正）。',
    'pattern.reversed.high.tag': '逆位偏多',
    'pattern.reversed.high.text': '長期 {total} 張牌裡有 {k} 張逆位（{pct}%）。每張牌正逆位的機會各半，逆位這麼多或更多的機率{prob}。',
    'pattern.reversed.low.tag': '逆位偏少',
    'pattern.reversed.low.text': '長期 {total} 張牌裡只有 {k} 張逆位（{pct}%）。每張牌正逆位的機會各半，逆位這麼少或更少的機率{prob}。',
    'pattern.regular.tag': '常客牌',
    'pattern.regular.text': '{name}在你的 {total} 張牌裡出現了 {n} 次。照你用過的牌組隨機發牌，{size} 種牌裡「任何一張」出現到這個次數的機率{prob}。它的關鍵詞：{kw}。這張牌一再出現，它的主題值得你花時間多想一想。',
    'pattern.regular.kw': '{kw}（{ori}）',
    'pattern.regular.text.noKeywords': '{name}在你的 {total} 張牌裡出現了 {n} 次。照你用過的牌組隨機發牌，{size} 種牌裡「任何一張」出現到這個次數的機率{prob}。這張牌一再出現，它的主題值得你花時間多想一想。',
    'pattern.major.high.tag': '大阿卡納偏多',
    'pattern.major.high.text': '你的 {total} 張牌裡有 {k} 張大阿卡納（{pct}%，平均應是 {exp} 張）。純隨機出現這麼多或更多的機率{prob}。',
    'pattern.major.low.tag': '大阿卡納偏少',
    'pattern.major.low.text': '你的 {total} 張牌裡只有 {k} 張大阿卡納（{pct}%，平均應是 {exp} 張）。純隨機出現這麼少或更少的機率{prob}。大阿卡納少，表示你問的事多半落在日常層次，主要靠你自己的具體選擇推動。',
    'pattern.pace.tag': '節奏變快',
    'pattern.pace.text': '最近 30 天你占卜了 {n} 次，前一個 30 天是 {prev} 次。如果是在反覆追問同一件事，不妨先停一停，回頭讀上一次的牌：短時間內為同一個問題重抽，答案往往彼此矛盾，反而更難判斷。',
    'pattern.flat.tag': '無顯著偏向',
    'pattern.flat.text': '花色、大阿卡納比例、正逆位、常客牌與標籤交叉都檢查過了，你的長期分布都在隨機範圍內，沒有特別的集中。',
    'btn.startReading': '開始占卜',
    'btn.share': '分享',
    'btn.copyResults': '複製結果',
    'btn.shareImage': '生成分享圖',
    'btn.print': '列印',
    'btn.note': '筆記',
    'btn.tag': '標籤',
    'btn.delete': '刪除',
    'btn.cancel': '取消',
    'btn.save': '儲存',
    'btn.add': '儲存',
    'btn.confirm': '確定',
    'btn.close': '關閉',
    'btn.reload': '重新整理',
    'note.title': '編輯筆記',
    'note.placeholder': '寫下你的感受與想法…',
    'tag.title': '編輯標籤',
    'tag.common': '常用標籤',
    'tag.custom': '自訂標籤',
    'tag.placeholder': '輸入標籤名稱…',
    'confirm.clearAll.title': '清除所有資料',
    'confirm.clearAll.message': '將刪除這台裝置上的全部占卜記錄、筆記、偏好設定、生日與學習進度，且無法復原。建議先匯出備份。',
    'confirm.clearAll.ok': '全部清除',
    'confirm.import.title': '匯入記錄',
    'confirm.import.message': '將匯入 {n} 筆記錄，取代目前的 {current} 筆記錄。',
    'confirm.import.messageEmpty': '將匯入 {n} 筆記錄。',
    'confirm.import.extras': '檔案裡的偏好設定、學習進度與生日，也會取代這台裝置上現有的資料。',
    'confirm.import.ok': '匯入',
    'confirm.delete.title': '刪除記錄',
    'confirm.delete.message': '確定要刪除此占卜記錄嗎？',
    'confirm.delete.ok': '刪除',
    'confirm.clearHistory.title': '清除所有記錄',
    'confirm.clearHistory.message': '將刪除全部 {n} 筆占卜記錄，包含筆記與標籤。此動作無法復原。',
    'confirm.clearHistory.ok': '全部刪除',
    'confirm.learnReset.title': '重設學習進度',
    'confirm.learnReset.message': '熟練度與連續天數都會歸零，且無法復原。',
    'confirm.learnReset.ok': '重設',
    'toast.deckTooSmall': '牌組數量不足',
    'toast.copied': '已複製到剪貼簿',
    'toast.copyFailed': '複製失敗',
    'toast.linkCopied': '連結已複製',
    'toast.noReading': '請先進行占卜',
    'toast.shareImageDone': '分享圖已下載',
    'toast.shareImageFailed': '分享圖生成失敗',
    'toast.visualStyle': '已切換至{name}',
    'toast.favorited': '已加入收藏',
    'toast.unfavorited': '已取消收藏',
    'toast.deleted': '已刪除記錄',
    'toast.historyCleared': '已清除所有記錄',
    'toast.noteSaved': '筆記已儲存',
    'toast.tagUpdated': '標籤已更新',
    'toast.exported': '資料已匯出',
    'toast.imported': '已匯入 {n} 筆記錄',
    'toast.imported.withPrefs': '已匯入 {n} 筆記錄，以及 {prefs} 項設定與學習資料',
    'toast.importBadFormat': '檔案格式錯誤',
    'toast.importParseFailed': '檔案解析失敗',
    'toast.importEmpty': '檔案裡沒有可用的占卜記錄，已取消匯入',
    'toast.historyTrimmed': '記錄超過 {max} 筆，已移除最舊的 {n} 筆（優先保留收藏與有筆記的）',
    'toast.historyEmpty': '目前沒有可清除的記錄',
    'toast.storageFull': '無法寫入瀏覽器的儲存空間（可能已滿或網站資料被封鎖），這次的變更不會保留',
    'toast.badShareLink': '分享連結的參數有誤，已略過無法使用的部分',
    'toast.updateAvailable': '新版本可用',
    'toast.deckLoadFailed': '線稿牌組載入失敗，已改回原本的樣式',
    'toast.imagesOffline': '目前離線，沒看過的牌圖要連上網路才能顯示',
    'toast.learnReset': '學習進度已重設',
    'toast.birthdayInvalid': '生日格式不正確',
    'toast.birthdayFuture': '生日不能是未來的日期',
    'toast.birthdayCleared': '已清除生日',
    'toast.profileUpdated': '已更新你的個人牌'
  }
};
