export const uiStrings = {
  zh: {
    'app.title': '塔羅占卜',
    'app.docTitle': '免費塔羅牌占卜：牌義查詢、35 種牌陣與每日一牌｜The Final Star',
    'app.name': '塔羅',
    'app.themeToggle.toDark': '切換至深色主題',
    'app.themeToggle.toLight': '切換至淺色主題',
    'app.themeToggle.title': '切換主題（T）',
    'app.langSwitch.label': '切換語言：{lang}',
    'app.skipToMain': '跳到主要內容',
    'app.hero.title': '探索內心的指引',
    'app.hero.subtitle': '帶著一個具體的問題抽牌，再對照牌位與牌義讀出答案。',
    'app.share.text': '查看我的占卜結果',
    'app.share.imageFooter': '僅供參考 · 塔羅占卜工具',
    'footer.about.title': '關於',
    'footer.about.desc': '以偉特塔羅為本的牌義、牌陣與學習工具。占卜記錄只存在你的裝置上。',
    'footer.info.title': '資訊',
    'footer.link.about': '關於本站',
    'footer.link.privacy': '隱私政策',
    'footer.copyright': '塔羅占卜工具 · 僅供參考使用',
    'tab.list': '主要分頁',
    'tab.reading': '占卜',
    'tab.history': '記錄',
    'tab.statistics': '統計',
    'tab.database': '資料庫',
    'tab.learn': '學習',
    'tab.settings': '設定',
    'pager.label': '逐張解讀的牌位',
    'pager.prev': '上一張',
    'pager.next': '下一張',
    'pager.nextTo': '下一張：{name}',
    'pager.count': '{n} / {total}',
    'pager.slide': '第 {n} 張，共 {total} 張',
    'pager.status': '第 {n} 張，共 {total} 張：{pos}，{name}（{ori}）',
    'pager.hint': '左右滑動換一張',
    'hero.swipe': '向上滑動，抽出{spread}',
    'hero.tiles.more': '更多',
    'hero.tiles.moreLabel': '更多牌陣',
    'reading.daily.title': '每日一牌 · {m}月{d}日',
    'reading.question.label': '你的問題',
    'reading.question.placeholder': '例如：目前最需要專注的方向？',
    'reading.deck.label': '牌組',
    'reading.topic.label': '主題',
    'topic.none': '不指定主題',
    'topic.group.love': '感情',
    'topic.group.career': '事業',
    'topic.group.wealth': '財務',
    'topic.group.other': '其他',
    'topic.love': '感情（整體）',
    'topic.loveNew': '曖昧與新對象',
    'topic.loveCouple': '交往中或婚姻',
    'topic.loveFeelings': '對方的想法',
    'topic.loveReunion': '復合',
    'topic.career': '工作（整體）',
    'topic.careerSeek': '求職與面試',
    'topic.careerChange': '轉職與創業',
    'topic.wealth': '財務（整體）',
    'topic.wealthInvest': '投資與理財',
    'topic.wellbeing': '身心',
    'topic.study': '學業與考試',
    'topic.growth': '自我成長',
    'reading.detail.topic': '{topic}',
    'reading.detail.yesno': '是非傾向',
    'reading.copy.topic': '{topic}：{text}',
    'reading.copy.yesno': '是非傾向：{tendency}，{note}',
    'reading.meta.topic': '主題：{topic}',
    'reading.spread.label': '牌陣',
    'reading.spreadInfo.title': '關於此牌陣',
    'reading.spreadInfo.positions': '牌位說明',
    'reading.spreadInfo.howTo': '牌位之間怎麼讀',
    'reading.spreadInfo.examples': '適合問的問題',
    'reading.spreadInfo.useExample': '把「{q}」填進問題欄',
    'reading.results.title': '你的占卜',
    'reading.detail.title': '逐張解讀',
    'reading.detail.text': '{ori}牌義',
    'reading.detail.more': '看卡片詳情',
    'reading.detail.more.label': '看卡片詳情：{name}（{ori}）',
    'reading.detail.expandAll': '全部展開',
    'reading.detail.collapseAll': '全部收合',
    'reading.copy.keywords': '關鍵詞：{kw}',
    'reading.detail.role': '在這個位置',
    'reading.copy.role': '在這個位置：{text}',
    'reading.busy': '占卜中…',
    'pick.title': '憑直覺選牌',
    'pick.hint': '靜心想著你的問題，選出 <strong>{n}</strong> 張牌',
    'pick.progress': '已選 {n} / {total}',
    'pick.cardBack': '第 {n} 張牌背',
    'pick.cardPicked': '第 {n} 張牌背，已選為第 {order} 張',
    'pick.random': '隨機快選',
    'pick.reshuffle': '重新洗牌',
    'deck.full': '完整牌組（78 張）',
    'deck.major': '大阿卡納（22 張）',
    'deck.minor': '小阿卡納（56 張）',
    'deck.court': '宮廷牌（16 張）',
    'deck.numbered': '數字牌（40 張）',
    'spread.group.basic': '基礎指引',
    'spread.group.time': '時間運勢',
    'spread.group.love': '感情與人際',
    'spread.group.career': '抉擇、事業與學業',
    'spread.group.self': '內在探索',
    'spread.group.advanced': '進階經典',
    'spread.bottom': '底牌',
    'spread.bottom.desc': '洗牌後壓在整疊最下面、沒有進入牌陣的那張，常當作整件事底下的背景基調。',
    'spread.unknown': '未知牌陣',
    'spread.picker.title': '選擇牌陣',
    'spread.picker.count': '{n} 張',
    'spread.single.name': '單張牌指引',
    'spread.single.label': '單張牌',
    'spread.single.desc': '只抽一張，適合每日指引，或一個已經聚焦的具體問題。',
    'spread.single.howTo': '只有一張牌，就拿它和你的問題對照：先看牌面上的人在做什麼、面向哪裡，再問自己這個動作對應到問題裡的哪件事。正位多半是可以直接拿來用的提示，逆位常是這股力量太過、不足或卡住。看不懂先別重抽，同一個問題重抽只會讓答案更模糊；把它記下來，晚上再讀一次。',
    'spread.single.ex.0': '今天上班，我最需要留意的是什麼？',
    'spread.single.ex.1': '這週跟家人相處，我可以多做些什麼？',
    'spread.single.ex.2': '下週要上台簡報，我該帶著什麼心態準備？',
    'spread.single.pos.0': '核心指引',
    'spread.single.pos.0.desc': '對你問題的直接回應，也就是此刻最該留意的主題。',
    'spread.yesno.name': '是非指引',
    'spread.yesno.label': '是非指引',
    'spread.yesno.desc': '針對「會不會」「該不該」的問題。逐張解讀會列出每張牌抽到的這一面偏向是或否；本站不替三張牌合算答案，請把三個位置放在一起判斷。',
    'spread.yesno.howTo': '先翻第三張看傾向，再拿前兩張秤它的份量：支持的牌比阻礙的牌強（例如大阿卡納對上數字牌、正位對上逆位），傾向就比較穩。阻礙那張若是很具體的處境或一個人，多半是可以處理的變數，處理了答案可能翻轉。三張都模糊時，常表示問題問得太大，把它拆成一個你能做的決定再問。',
    'spread.yesno.ex.0': '這個月向主管提出調部門，對我來說是好時機嗎？',
    'spread.yesno.ex.1': '我主動約他週末吃飯，會順利嗎？',
    'spread.yesno.ex.2': '今年報名在職專班，我的時間和體力撐得住嗎？',
    'spread.yesno.pos.0': '支持的力量',
    'spread.yesno.pos.0.desc': '有利於「是」的因素：你手上的資源、時機或助力。',
    'spread.yesno.pos.1': '阻礙的力量',
    'spread.yesno.pos.1.desc': '不利於「是」的因素：卡住的地方、風險或你的顧慮。重點是它能不能被處理，而不只是它存不存在。',
    'spread.yesno.pos.2': '結果傾向',
    'spread.yesno.pos.2.desc': '照目前的情況走下去，事情大致偏向哪一邊。以這張牌的是非傾向為主，再用前兩張判斷這個傾向穩不穩。',
    'spread.three.name': '聖三角',
    'spread.three.label': '聖三角',
    'spread.three.desc': '最常用的三張牌時間線，台灣也常叫「時間之流」：一件事從哪裡來、正走到哪裡、接下來往哪裡去。',
    'spread.three.howTo': '把三張連成一句話：「因為……，所以現在……，接下來……」。再看是遞進還是轉折：花色或數字一路延續，多半是同一股力量在累積；中間那張突然換了花色或翻成逆位，轉折點就在現在。不喜歡未來那張時，回到中間那張找你能改的動作，而不是回頭責怪過去。',
    'spread.three.ex.0': '我和室友的關係最近變僵，事情是怎麼走到這一步的？',
    'spread.three.ex.1': '經營了一年的副業，接下來會往哪裡發展？',
    'spread.three.ex.2': '減重卡在停滯期，我該怎麼看待這段過程？',
    'spread.three.pos.0': '過去',
    'spread.three.pos.0.desc': '已經發生、至今仍在影響這件事的經歷或決定。讀它是為了理解現況從何而來。',
    'spread.three.pos.1': '現在',
    'spread.three.pos.1.desc': '你此刻的處境與眼前的主題，是三張牌的重心。',
    'spread.three.pos.2': '未來',
    'spread.three.pos.2.desc': '照目前的方向發展下去最可能的走向，不是定局；不喜歡這張牌，就回頭看「現在」有什麼可以改。',
    'spread.mbs.name': '身心靈牌陣',
    'spread.mbs.label': '身心靈',
    'spread.mbs.desc': '從心態、身體、靈性三個層面看你目前的狀態：找出哪一層失衡，再看它怎麼牽動另外兩層。',
    'spread.mbs.howTo': '先找三張裡最「重」的那張：逆位、寶劍或大阿卡納常是失衡所在。再看旁邊那層有沒有同樣的花色或數字，有的話，表示問題已經從一層蔓延到另一層。三張裡最順的那張是著力點，例如靈性那張穩，就先用固定散步或睡前寫幾行字把心態拉回來。身體那張只當提醒，不當診斷。',
    'spread.mbs.ex.0': '最近一直覺得很累，我的身心是哪裡失去平衡？',
    'spread.mbs.ex.1': '換了新工作之後，我要怎麼照顧好自己的狀態？',
    'spread.mbs.ex.2': '一直提不起勁做喜歡的事，我缺的是什麼？',
    'spread.mbs.pos.0': '心態',
    'spread.mbs.pos.0.desc': '你的想法、情緒與壓力，以及你怎麼看待自己的處境。',
    'spread.mbs.pos.1': '身體',
    'spread.mbs.pos.1.desc': '體力、作息與身體發出的訊號。逆位常是提醒你休息或照顧被忽略的需要；身體不適請以就醫為準。',
    'spread.mbs.pos.2': '靈性',
    'spread.mbs.pos.2.desc': '你和意義感、信念或內在平靜的連結：什麼能讓你重新感到踏實。',
    'spread.path.name': '突破之路',
    'spread.path.label': '突破之路',
    'spread.path.desc': '只有一件事、一條路要面對時用：先看清問題的核心，再看卡在哪裡、該往哪個方向使力，以及照這個方向走下去的結果。手上有兩個以上的選項要比較，請改用二擇一或三選一。',
    'spread.path.howTo': '先把「問題」和你原本問的話並排：兩者說的若不是同一件事，後面三張都要用牌給的那個問題來讀。接著把「挑戰」和「方向」當成一組，好的方向常正好回應挑戰，例如挑戰是寶劍的想太多，方向是權杖的先動手。結果是走完方向之後的樣子；不理想時，回頭看方向那張是不是逆位、要先修正。',
    'spread.path.ex.0': '拖了半年的論文，我卡在哪裡、該怎麼推進？',
    'spread.path.ex.1': '想跟主管談加薪，我該從哪裡著手？',
    'spread.path.ex.2': '想搬出家裡自己住，我要先解決什麼？',
    'spread.path.pos.0': '問題',
    'spread.path.pos.0.desc': '這件事真正的核心。它有時和你問的不一樣，那正是值得注意的地方。',
    'spread.path.pos.1': '挑戰',
    'spread.path.pos.1.desc': '眼前最主要的阻力，可能來自外在環境，也可能是你自己的習慣或顧慮。',
    'spread.path.pos.2': '方向',
    'spread.path.pos.2.desc': '牌建議你採取的態度或行動。正位就照著做；逆位提醒你先修正這個方向裡過度或不足的部分。',
    'spread.path.pos.3': '結果',
    'spread.path.pos.3.desc': '照「方向」的建議走下去最可能的結果。',
    'spread.weekly.name': '週運勢',
    'spread.weekly.label': '週運勢',
    'spread.weekly.desc': '一張整週主題，加上週一到週日每天一張。先讀主題，再看每天的牌怎麼呼應或偏離它。',
    'spread.weekly.howTo': '七張每日牌除了跟主題比，也要橫著看：同花色連續出現的那幾天，常是同一件事在發酵，例如週二到週四都是寶劍，多半是同一個討論拖了三天；正逆位突然翻轉的那天是轉折日。把最吃力的那天挑出來，事先在行事曆留緩衝，最順的那天留給最重要的待辦。週末回頭對照，比預測準不準更有用。',
    'spread.weekly.ex.0': '這週在工作上，我最該把力氣放在哪裡？',
    'spread.weekly.ex.1': '週末要回老家，這週我在情緒和人際上要留意什麼？',
    'spread.weekly.ex.2': '這週開始執行運動計畫，哪幾天比較難堅持？',
    'spread.weekly.pos.0': '主題',
    'spread.weekly.pos.0.desc': '這一週的基調與最該留意的事；每天的牌都放在它底下讀。',
    'spread.weekly.pos.1': '週一',
    'spread.weekly.pos.2': '週二',
    'spread.weekly.pos.3': '週三',
    'spread.weekly.pos.4': '週四',
    'spread.weekly.pos.5': '週五',
    'spread.weekly.pos.6': '週六',
    'spread.weekly.pos.7': '週日',
    'spread.monthly.name': '月運勢',
    'spread.monthly.label': '月運勢',
    'spread.monthly.desc': '一張本月主題，加上四週各一張；第四週的牌也涵蓋月底剩下的日子。',
    'spread.monthly.howTo': '把四週的牌當成四格漫畫依序讀，看劇情是一路往上、一路往下，還是中間起伏。數字由小到大常是事情在推進；花色從權杖轉到錢幣，多半是想法開始落地。再拿最好和最難的兩週並排，看主題牌比較像哪一週，那一週的狀態就是這個月的主要面貌。月底回頭寫一句對照。',
    'spread.monthly.ex.0': '這個月要準備搬家，每一週我該把重點放在哪裡？',
    'spread.monthly.ex.1': '這個月業績要衝刺，我的節奏要怎麼安排？',
    'spread.monthly.ex.2': '這個月想把開銷控制下來，我要留意什麼？',
    'spread.monthly.pos.0': '本月主題',
    'spread.monthly.pos.0.desc': '這個月的整體走向與重點；四週的牌都放在它底下讀。',
    'spread.monthly.pos.1': '第一週',
    'spread.monthly.pos.2': '第二週',
    'spread.monthly.pos.3': '第三週',
    'spread.monthly.pos.4': '第四週',
    'spread.quarterly.name': '四季展望',
    'spread.quarterly.label': '四季展望',
    'spread.quarterly.desc': '看接下來一年的四季，各抽一張：還沒過完的季節讀今年，已經過去的季節讀明年。',
    'spread.quarterly.howTo': '先把四張依實際的時間順序重排，從你所在的季節開始讀，而不是從春季開始，起承轉合才對得上。哪一季出現大阿卡納或王牌，常是這一年的關鍵季；相鄰兩季同花色，表示同一件事會跨季延續。最後把第一季和最後一季並排，看這一年從哪裡出發、收在哪裡。',
    'spread.quarterly.ex.0': '接下來這一年，我的工作會經歷哪些階段？',
    'spread.quarterly.ex.1': '明年想存一筆出國念書的錢，每一季我該怎麼安排？',
    'spread.quarterly.ex.2': '接下來一年，我要怎麼在照顧家人和顧好自己之間取得平衡？',
    'spread.quarterly.pos.0': '春季（3–5 月）',
    'spread.quarterly.pos.1': '夏季（6–8 月）',
    'spread.quarterly.pos.2': '秋季（9–11 月）',
    'spread.quarterly.pos.3': '冬季（12–2 月）',
    'spread.yearly.name': '年度主題',
    'spread.yearly.label': '年度主題',
    'spread.yearly.desc': '一張年度總主題，加上一月到十二月各一張。適合在年初做，年中可以回頭對照。',
    'spread.yearly.howTo': '十三張牌別一開始就逐月細讀。先把十二個月按季分成四組，各看一眼主要花色，找出全年哪一段偏行動、哪一段偏情感或收成。再標出大阿卡納落在哪幾個月，那幾個月常和總主題直接呼應，是重點月份。之後每個月初只要回頭讀當月那張和總主題，一年下來就是一份可以對照的紀錄。',
    'spread.yearly.ex.0': '新的一年，我在事業上最重要的課題是什麼？',
    'spread.yearly.ex.1': '今年想談一段穩定的感情，我要留意哪些時期？',
    'spread.yearly.ex.2': '三十歲這一年，我想把重心放在哪裡？',
    'spread.yearly.pos.0': '總主題',
    'spread.yearly.pos.0.desc': '這一年的核心課題與整體走向；各月的牌是它在不同時段的展開。',
    'spread.yearly.pos.1': '一月',
    'spread.yearly.pos.2': '二月',
    'spread.yearly.pos.3': '三月',
    'spread.yearly.pos.4': '四月',
    'spread.yearly.pos.5': '五月',
    'spread.yearly.pos.6': '六月',
    'spread.yearly.pos.7': '七月',
    'spread.yearly.pos.8': '八月',
    'spread.yearly.pos.9': '九月',
    'spread.yearly.pos.10': '十月',
    'spread.yearly.pos.11': '十一月',
    'spread.yearly.pos.12': '十二月',
    'spread.newmoon.name': '新月啟程',
    'spread.newmoon.label': '新月啟程',
    'spread.newmoon.desc': '在新月前後做，為接下來約一個月（到下一次新月）設定意圖，並找出實現它需要的資源與該放下的東西。',
    'spread.newmoon.howTo': '最該並排的是「內在資源」和「需要放下」：兩張常是同一個特質的兩面，同一種謹慎，用得好是資源，用過頭就成了該放下的拖累。再拿「外在助力」對照「顯化方向」，看第一步要不要借別人的力。最後把顯化方向寫成一件這週就能做的事，滿月時回來對照。',
    'spread.newmoon.ex.0': '這個月我想開始存旅遊基金，該怎麼起步？',
    'spread.newmoon.ex.1': '新的週期裡，我想在創作上投入什麼？',
    'spread.newmoon.ex.2': '我想改掉睡前滑手機的習慣，這個月可以怎麼做？',
    'spread.newmoon.pos.0': '新月意圖',
    'spread.newmoon.pos.0.desc': '這個週期最值得投入的目標或方向。若和你原本想的不同，先想想牌為什麼這樣提示。',
    'spread.newmoon.pos.1': '內在資源',
    'spread.newmoon.pos.1.desc': '你已經具備、可以拿來用的能力或特質。',
    'spread.newmoon.pos.2': '外在助力',
    'spread.newmoon.pos.2.desc': '環境裡可以借力的人、機會或條件。',
    'spread.newmoon.pos.3': '需要放下',
    'spread.newmoon.pos.3.desc': '會拖住你的習慣、想法或關係，這個週期先把它放下。',
    'spread.newmoon.pos.4': '顯化方向',
    'spread.newmoon.pos.4.desc': '把意圖落實的具體做法，也就是接下來該踏出的第一步。',
    'spread.fullmoon.name': '滿月釋放',
    'spread.fullmoon.label': '滿月釋放',
    'spread.fullmoon.desc': '在滿月前後做，回顧從上次新月到現在的這段週期：完成了什麼、還沒完成什麼、該放下什麼。',
    'spread.fullmoon.howTo': '先並排讀「已然圓滿」和「未竟之事」：同花色時，完成與未完成多半是同一件事的不同階段；不同花色，表示你的力氣可能都放在另一個領域。再看「需要釋放」是不是正好卡住「未竟之事」，若是，放下它就是往前的前提。最後把「收穫果實」和「下一步」連起來讀：學到的東西就是下個週期的起點。',
    'spread.fullmoon.ex.0': '從上次新月到現在，我在工作上完成了什麼、還卡著什麼？',
    'spread.fullmoon.ex.1': '這個月我在感情裡該放下的是什麼？',
    'spread.fullmoon.ex.2': '學日文的進度不如預期，我該怎麼調整期待？',
    'spread.fullmoon.pos.0': '已然圓滿',
    'spread.fullmoon.pos.0.desc': '這個週期已經完成或開花結果的事，先肯定它。',
    'spread.fullmoon.pos.1': '未竟之事',
    'spread.fullmoon.pos.1.desc': '還沒完成的部分：看它是需要再努力，還是該調整期待。',
    'spread.fullmoon.pos.2': '需要釋放',
    'spread.fullmoon.pos.2.desc': '該放下的情緒、執著或負擔，放下後才有空間迎接下一個週期。',
    'spread.fullmoon.pos.3': '收穫果實',
    'spread.fullmoon.pos.3.desc': '這個週期留給你的東西：不一定是看得見的成果，更常是學到的一課或新長出的能力。',
    'spread.fullmoon.pos.4': '下一步',
    'spread.fullmoon.pos.4.desc': '帶著這次的收穫進入下一個週期時，最該做的事。',
    'spread.relationship.name': '關係牌陣',
    'spread.relationship.label': '關係',
    'spread.relationship.desc': '看一段關係（伴侶、家人、朋友或同事都可以）裡雙方各自的看法、目前的狀態、主要的考驗與發展的可能。',
    'spread.relationship.howTo': '先把「你的觀點」和「對方觀點」並排看元素：權杖與寶劍、聖杯與錢幣屬於友好的元素，多半合拍；權杖與聖杯、寶劍與錢幣相對，常是一個急著行動、一個要先顧感受，或一個講道理、一個要實際。再看「挑戰」比較像哪一方的牌，問題常卡在那一側。最後拿「潛力」和「現況」比，差距越大，要調整的越多。',
    'spread.relationship.ex.0': '我和交往三年的男友最近常為小事吵架，我們之間發生了什麼？',
    'spread.relationship.ex.1': '我和媽媽的相處總是很緊繃，我可以怎麼改善？',
    'spread.relationship.ex.2': '和新來的同事合作不太順，這段關係還有什麼可能？',
    'spread.relationship.pos.0': '你的觀點',
    'spread.relationship.pos.0.desc': '你怎麼看這段關係，以及你在其中的感受與期待。',
    'spread.relationship.pos.1': '對方觀點',
    'spread.relationship.pos.1.desc': '對方可能的感受與立場。這是牌給的角度，不等於讀心，最好再用實際的溝通確認。',
    'spread.relationship.pos.2': '現況',
    'spread.relationship.pos.2.desc': '這段關係此刻的狀態與兩人互動的基調。',
    'spread.relationship.pos.3': '挑戰',
    'spread.relationship.pos.3.desc': '關係裡最需要面對的問題或摩擦點。',
    'spread.relationship.pos.4': '潛力',
    'spread.relationship.pos.4.desc': '如果雙方都願意經營，這段關係能發展成的樣子。',
    'spread.feelings.name': '對方心意',
    'spread.feelings.label': '對方心意',
    'spread.feelings.desc': '從表面態度到內心感受，逐層看對方對你的心意。牌呈現的是可能性，不是讀心；真正的答案仍要從互動與溝通裡得到。',
    'spread.feelings.howTo': '由外往內讀：先比「表面態度」和「內心真實感受」，兩張一致代表對方表裡如一，落差大則說明你看到的不是全部。再把「對關係的期待」和「猶豫與顧慮」並排，兩者拉扯的結果，就是「可能的行動」。讀完別當成結論，挑一個牌提示的細節（例如對方在意的是時間還是承諾），用一次實際的對話去確認。',
    'spread.feelings.ex.0': '我們最近訊息越聊越少，我想知道他對這段曖昧可能有什麼顧慮？',
    'spread.feelings.ex.1': '同事最近對我很冷淡，背後可能是什麼原因？',
    'spread.feelings.ex.2': '分手後還保持聯絡的前任，可能怎麼看待我們現在的關係？',
    'spread.feelings.pos.0': '表面態度',
    'spread.feelings.pos.0.desc': '對方表現在外、你看得到的態度。',
    'spread.feelings.pos.1': '內心真實感受',
    'spread.feelings.pos.1.desc': '對方心裡可能的感受；可能和表面態度一致，也可能不同。',
    'spread.feelings.pos.2': '對關係的期待',
    'spread.feelings.pos.2.desc': '對方希望這段關係變成什麼樣子。',
    'spread.feelings.pos.3': '猶豫與顧慮',
    'spread.feelings.pos.3.desc': '讓對方遲疑或保留的原因。',
    'spread.feelings.pos.4': '可能的行動',
    'spread.feelings.pos.4.desc': '對方接下來比較可能採取的行動或態度。',
    'spread.loveCross.name': '愛情十字',
    'spread.loveCross.label': '愛情十字',
    'spread.loveCross.desc': '六張牌排成十字：左右是你與對方，中間是關係本身，上方是助力、下方是阻礙，最右邊是發展方向。',
    'spread.loveCross.howTo': '先橫著讀中間一排：你、關係現況、對方三張並排，看現況比較像誰的延伸，主導節奏的通常是那一方。再直著讀中間一列，助力在上、阻礙在下，比較兩張的強弱，判斷關係是被往上拉還是往下拖。最後才看最右邊的發展方向；它若和阻礙同花色，表示阻礙沒處理，事情就會往那邊走。',
    'spread.loveCross.ex.0': '我和曖昧中的他，要怎麼讓關係往前走一步？',
    'spread.loveCross.ex.1': '結婚五年，我們的感情現在處在什麼狀態？',
    'spread.loveCross.ex.2': '單身好一陣子了，我在感情上需要調整什麼？',
    'spread.loveCross.pos.0': '你的狀態',
    'spread.loveCross.pos.0.desc': '你目前在感情裡的心態與處境。',
    'spread.loveCross.pos.1': '對方的狀態',
    'spread.loveCross.pos.1.desc': '對方目前的心態與處境；單身時可以讀成你正在吸引、或你期待遇見的對象。',
    'spread.loveCross.pos.2': '關係現況',
    'spread.loveCross.pos.2.desc': '兩人之間此刻的互動與連結。',
    'spread.loveCross.pos.3': '關係的阻礙',
    'spread.loveCross.pos.3.desc': '妨礙關係發展的因素，可能來自外在，也可能來自你們其中一方。',
    'spread.loveCross.pos.4': '關係的助力',
    'spread.loveCross.pos.4.desc': '讓關係更好的因素，值得刻意培養。',
    'spread.loveCross.pos.5': '發展方向',
    'spread.loveCross.pos.5.desc': '照目前的互動走下去，這段關係最可能的走向。',
    'spread.conflict.name': '衝突化解',
    'spread.conflict.label': '衝突化解',
    'spread.conflict.desc': '梳理一次人際衝突：根源在哪裡、雙方各自在意什麼、還有什麼共同點，以及化解的方法。',
    'spread.conflict.howTo': '讀完根源之後，把「你的立場」和「對方的立場」並排：兩張同花色或同數字，表示你們要的其實是同一樣東西，只是方法不同；差很多時，就從「彼此的共同點」找一個可以先談的小題目。最後的「化解之道」要用在自己身上，它回答的是你能先做什麼，而不是怎麼讓對方讓步。',
    'spread.conflict.ex.0': '我和合夥人為了分潤鬧僵，我要怎麼談下去？',
    'spread.conflict.ex.1': '家裡為了誰照顧爸媽起爭執，我該怎麼面對？',
    'spread.conflict.ex.2': '跟好朋友因為一句話吵架，我可以怎麼修補？',
    'spread.conflict.pos.0': '衝突的根源',
    'spread.conflict.pos.0.desc': '表面爭執底下真正的原因。',
    'spread.conflict.pos.1': '你的立場',
    'spread.conflict.pos.1.desc': '你在意的是什麼，以及你可能沒看到的盲點。',
    'spread.conflict.pos.2': '對方的立場',
    'spread.conflict.pos.2.desc': '對方在意的是什麼。用這張牌去理解對方，而不是證明對方錯了。',
    'spread.conflict.pos.3': '彼此的共同點',
    'spread.conflict.pos.3.desc': '雙方都在乎、可以當作和解起點的東西。',
    'spread.conflict.pos.4': '化解之道',
    'spread.conflict.pos.4.desc': '具體可以採取的做法或態度。',
    'spread.twoChoice.name': '二擇一',
    'spread.twoChoice.label': '二擇一',
    'spread.twoChoice.desc': '比較兩個選項：最下方是現況，左邊一列是選項 A、右邊一列是選項 B，各自由下往上是過程與結果。結果要和過程一起看：結果好的選項，過程不一定輕鬆。',
    'spread.twoChoice.howTo': '依「層」左右對照，不要先把 A 一路讀完再讀 B：先並排比兩張過程，看哪條路順、哪條要付出比較多；再並排比兩張結果。最後回到底部的現況，看它的花色或氣氛比較接近哪一邊，那常透露你心裡已經偏向哪個選項。兩邊結果都不錯時，比的就是哪一段過程你比較願意承受。',
    'spread.twoChoice.ex.0': '留在現在的公司升主管，還是跳槽到新創，哪條路比較適合我？',
    'spread.twoChoice.ex.1': '繼續在台北租房，還是搬回台南老家？',
    'spread.twoChoice.ex.2': '研究所要讀在職專班，還是辭職全心準備考試？',
    'spread.twoChoice.pos.0': '現況',
    'spread.twoChoice.pos.0.desc': '你做決定時的處境與心態。',
    'spread.twoChoice.pos.1': '選項 A 的過程',
    'spread.twoChoice.pos.1.desc': '選 A 這條路要經歷什麼：順不順、要付出多少。',
    'spread.twoChoice.pos.2': '選項 B 的過程',
    'spread.twoChoice.pos.2.desc': '選 B 這條路要經歷什麼，和 A 的過程對照著讀。',
    'spread.twoChoice.pos.3': '選項 A 的結果',
    'spread.twoChoice.pos.3.desc': '選 A 最可能的結果。',
    'spread.twoChoice.pos.4': '選項 B 的結果',
    'spread.twoChoice.pos.4.desc': '選 B 最可能的結果。',
    'spread.prosCons.name': '優劣分析',
    'spread.prosCons.label': '優劣分析',
    'spread.prosCons.desc': '把兩個選項的優缺點並排：左邊是選項 A，右邊是選項 B，中間一張是做決定時最該放在心上的提示。',
    'spread.prosCons.howTo': '先橫著比：上排兩個優點並排、下排兩個缺點並排，同一排放在一起才看得出輕重。再直著看每一邊：優點和缺點同花色，代表好處和代價來自同一件事，沒辦法只拿一半。最後讀中間的核心提示，看它的花色或主題呼應哪一邊的優點，那多半就是你真正在意的東西。',
    'spread.prosCons.ex.0': '接下外派的機會和留在台灣，各有什麼得失？',
    'spread.prosCons.ex.1': '買房和繼續租房，對現在的我各有什麼利弊？',
    'spread.prosCons.ex.2': '孩子要念公立還是私立國中，我最該考慮的是什麼？',
    'spread.prosCons.pos.0': '選項 A 的優點',
    'spread.prosCons.pos.0.desc': '選 A 能得到的好處。',
    'spread.prosCons.pos.1': '選項 A 的缺點',
    'spread.prosCons.pos.1.desc': '選 A 要承擔的代價或風險。',
    'spread.prosCons.pos.2': '選項 B 的優點',
    'spread.prosCons.pos.2.desc': '選 B 能得到的好處。',
    'spread.prosCons.pos.3': '選項 B 的缺點',
    'spread.prosCons.pos.3.desc': '選 B 要承擔的代價或風險。',
    'spread.prosCons.pos.4': '核心提示',
    'spread.prosCons.pos.4.desc': '做這個決定時最該放在心上的事，往往點出你真正在意的是什麼。',
    'spread.goal.name': '目標達成牌陣',
    'spread.goal.label': '目標達成',
    'spread.goal.desc': '針對一個具體的目標：看它的核心、阻礙、可用的資源、該採取的步驟，以及照做之後的結果。',
    'spread.goal.howTo': '這五張可以拆成兩組對照。先把「阻礙」和「資源」並排：資源常就是對付阻礙的工具，例如阻礙是寶劍的過度擔心，資源若是錢幣，就是用一張具體的進度表取代空想。再看「步驟」有沒有用上那份資源。最後拿「結果」對照「核心」：結果若偏離核心，就算做到了，也可能不是你真正要的。',
    'spread.goal.ex.0': '我想在年底前開始經營自己的 Podcast，關鍵在哪裡？',
    'spread.goal.ex.1': '想在一年內存到二十萬，我該怎麼規劃？',
    'spread.goal.ex.2': '我想跑完人生第一場半馬，接下來要怎麼準備？',
    'spread.goal.pos.0': '核心',
    'spread.goal.pos.0.desc': '這個目標對你真正的意義，或它成敗的關鍵。',
    'spread.goal.pos.1': '阻礙',
    'spread.goal.pos.1.desc': '最可能讓你卡住的事。',
    'spread.goal.pos.2': '資源',
    'spread.goal.pos.2.desc': '你可以運用的能力、人脈或條件。',
    'spread.goal.pos.3': '步驟',
    'spread.goal.pos.3.desc': '接下來最該採取的具體行動。',
    'spread.goal.pos.4': '結果',
    'spread.goal.pos.4.desc': '照「步驟」的建議走下去最可能的結果。',
    'spread.career.name': '職涯發展',
    'spread.career.label': '職涯發展',
    'spread.career.desc': '檢視目前的工作或職涯方向：現況、你的優勢與盲點、外在的機會與挑戰，最後是具體建議。',
    'spread.career.howTo': '這個牌陣是兩組內外對照：「優勢」對「外在機會」，看你的強項接不接得住環境給的機會；「盲點」對「潛在挑戰」，兩張若相似，表示外面的風險多半被你自己的盲點放大。讀完這兩組再回頭看「職涯現況」；最後讀「發展建議」時，把它當成把優勢帶進機會、同時補上盲點的做法。',
    'spread.career.ex.0': '在現在的公司待了五年，下一步我該往哪裡發展？',
    'spread.career.ex.1': '想從工程師轉做產品經理，我有哪些優勢和盲點？',
    'spread.career.ex.2': '接案三年收入不穩，職涯上要怎麼調整？',
    'spread.career.pos.0': '職涯現況',
    'spread.career.pos.0.desc': '你在工作上的處境與心態。',
    'spread.career.pos.1': '你的優勢',
    'spread.career.pos.1.desc': '可以多加發揮的能力或特質。',
    'spread.career.pos.2': '你的盲點',
    'spread.career.pos.2.desc': '你沒注意到、或習慣忽略的弱點。',
    'spread.career.pos.3': '外在機會',
    'spread.career.pos.3.desc': '環境裡值得把握的機會。',
    'spread.career.pos.4': '潛在挑戰',
    'spread.career.pos.4.desc': '可能出現的阻力或風險，先做準備。',
    'spread.career.pos.5': '發展建議',
    'spread.career.pos.5.desc': '綜合前五張，牌建議你下一步怎麼做。',
    'spread.wealth.name': '財富流動',
    'spread.wealth.label': '財富流動',
    'spread.wealth.desc': '看你和金錢的關係：錢從哪裡來、從哪裡流失、有什麼機會。牌談的是態度與做法，不涉及任何具體的投資標的。',
    'spread.wealth.howTo': '先把「財富的來源」和「金錢的流失」並排：同花色常表示賺錢和花錢出自同一種習慣，例如為工作賺錢，也為工作壓力花錢。再看「財務機會」補不補得上流失的缺口。最後的「理財建議」要回頭對照「財務現況」裡你對錢的感受，態度先調整，做法才會持久。',
    'spread.wealth.ex.0': '我每個月都存不到錢，問題出在哪裡？',
    'spread.wealth.ex.1': '開始接副業之後，我要怎麼管理這筆收入？',
    'spread.wealth.ex.2': '我對錢總是很焦慮，可以怎麼調整和金錢的關係？',
    'spread.wealth.pos.0': '財務現況',
    'spread.wealth.pos.0.desc': '目前的財務狀態，以及你對錢的感受。',
    'spread.wealth.pos.1': '財富的來源',
    'spread.wealth.pos.1.desc': '目前或可能的收入來源，或你賺錢的強項。',
    'spread.wealth.pos.2': '金錢的流失',
    'spread.wealth.pos.2.desc': '錢花在哪裡、漏在哪裡，包括習慣與情緒性的消費。',
    'spread.wealth.pos.3': '財務機會',
    'spread.wealth.pos.3.desc': '值得留意的增加收入或改善財務的機會。',
    'spread.wealth.pos.4': '理財建議',
    'spread.wealth.pos.4.desc': '牌建議你對金錢採取的態度或做法。',
    'spread.chakra.name': '脈輪牌陣',
    'spread.chakra.label': '脈輪',
    'spread.chakra.desc': '依印度瑜伽傳統的七個脈輪，由下而上各抽一張，看哪個層面順暢、哪個受阻。脈輪不屬於塔羅傳統，這是現代常見的結合用法。',
    'spread.chakra.howTo': '把七張看成一根由下往上的柱子：下面三輪偏現實與行動，上面三輪偏表達、直覺與意義，心輪在中間連接兩邊。先找最卡的那一輪，再看它上下的鄰居：常見的是下方不穩撐不住上方，例如安全感不足時，表達也容易縮回去。這時從最下方受阻的那一輪開始調整，常比直接處理上面的輪有效。',
    'spread.chakra.ex.0': '最近心裡總是很亂，哪個層面最需要我照顧？',
    'spread.chakra.ex.1': '我在工作上總是不敢表達意見，可以從哪裡開始調整？',
    'spread.chakra.ex.2': '想找回生活的熱情，我該先照顧自己的哪一部分？',
    'spread.chakra.pos.0': '海底輪',
    'spread.chakra.pos.0.desc': '安全感與現實基礎：錢、住所、身體是否讓你感到踏實。',
    'spread.chakra.pos.1': '臍輪',
    'spread.chakra.pos.1.desc': '情緒、慾望、創造力，以及享受生活的能力。',
    'spread.chakra.pos.2': '太陽神經叢輪',
    'spread.chakra.pos.2.desc': '自信、意志與行動力：你能不能為自己做決定。',
    'spread.chakra.pos.3': '心輪',
    'spread.chakra.pos.3.desc': '愛、慈悲與人際連結，也包括你怎麼對待自己。',
    'spread.chakra.pos.4': '喉輪',
    'spread.chakra.pos.4.desc': '表達與溝通：說出真話、被聽見的能力。',
    'spread.chakra.pos.5': '眉心輪',
    'spread.chakra.pos.5.desc': '直覺、洞察，以及看清事情的能力。',
    'spread.chakra.pos.6': '頂輪',
    'spread.chakra.pos.6.desc': '意義感、信仰，以及和更大整體的連結。',
    'spread.elements.name': '五元素牌陣',
    'spread.elements.label': '五元素',
    'spread.elements.desc': '火、水、風、土四元素各對應一個花色的領域，再加上把它們整合起來的「靈」，看你生活裡哪一塊充足、哪一塊匱乏。',
    'spread.elements.howTo': '先找四張元素牌裡最弱的一張（逆位，或和那個元素格格不入的牌），那就是匱乏的領域。再看元素之間的關係：火與風互相助長、水與土互相滋養，火與水、風與土則互相牽制。最弱的那一塊，可以從友好的元素借力，例如土不穩時先用水撐住。最後看「靈」比較接近哪一張，那是你目前整合生活的重心。',
    'spread.elements.ex.0': '最近生活一團亂，我是哪一塊失去平衡了？',
    'spread.elements.ex.1': '工作很忙卻覺得空虛，我少的是什麼？',
    'spread.elements.ex.2': '新的一年想讓生活更完整，我可以從哪個面向著手？',
    'spread.elements.pos.0': '火',
    'spread.elements.pos.0.desc': '行動、熱情與意志（權杖的領域）：你有沒有動力去做想做的事。',
    'spread.elements.pos.1': '水',
    'spread.elements.pos.1.desc': '情感、關係與直覺（聖杯的領域）：你的感受是否流動、有沒有被照顧。',
    'spread.elements.pos.2': '風',
    'spread.elements.pos.2.desc': '思考、溝通與判斷（寶劍的領域）：你的想法清不清楚、有沒有被困住。',
    'spread.elements.pos.3': '土',
    'spread.elements.pos.3.desc': '金錢、工作與身體（錢幣的領域）：生活的現實基礎穩不穩。',
    'spread.elements.pos.4': '靈',
    'spread.elements.pos.4.desc': '把四者整合起來的核心：此刻什麼讓你覺得完整、有方向。',
    'spread.selfDiscovery.name': '自我探索',
    'spread.selfDiscovery.label': '自我探索',
    'spread.selfDiscovery.desc': '比較你意識到的自己與潛意識裡的自己，找出內在真正的需要與被忽略的部分，再看怎麼把它們整合起來。',
    'spread.selfDiscovery.howTo': '讀完前兩張的落差之後，把「內在的需要」和「被忽略的自己」並排：被你壓下去的特質，常正好是滿足那份需要的方法，例如需要的是休息，被忽略的是愛玩、不講效率的那一面。讀「整合之道」時，檢查它有沒有同時回應這兩張；只照顧其中一邊，舊的模式多半很快又回來。',
    'spread.selfDiscovery.ex.0': '為什麼我在關係裡總是先討好別人？',
    'spread.selfDiscovery.ex.1': '工作很順利卻一點也不快樂，我真正想要的是什麼？',
    'spread.selfDiscovery.ex.2': '我常說自己不在乎，心裡真正在意的是什麼？',
    'spread.selfDiscovery.pos.0': '表意識的你',
    'spread.selfDiscovery.pos.0.desc': '你認為的自己，也是你習慣呈現給別人的樣子。',
    'spread.selfDiscovery.pos.1': '潛意識的你',
    'spread.selfDiscovery.pos.1.desc': '你沒意識到、卻一直在影響你的動機與感受。它和第一張的落差，就是這個牌陣的重點。',
    'spread.selfDiscovery.pos.2': '內在的需要',
    'spread.selfDiscovery.pos.2.desc': '你此刻真正需要的東西，不一定是你以為想要的。',
    'spread.selfDiscovery.pos.3': '被忽略的自己',
    'spread.selfDiscovery.pos.3.desc': '被你壓抑或遺忘的特質、才能或渴望。',
    'spread.selfDiscovery.pos.4': '整合之道',
    'spread.selfDiscovery.pos.4.desc': '把以上幾面整合起來的方法或下一步。',
    'spread.shadow.name': '陰影功課',
    'spread.shadow.label': '陰影功課',
    'spread.shadow.desc': '借用榮格的「陰影」概念：那些你不願承認、卻一直影響你的特質。先看清它的樣子與來源，再找接納與轉化的方式。觸及創傷時，建議與專業諮商師一起進行。',
    'spread.shadow.howTo': '前三張是一條因果鏈：成因造成面貌，面貌再造成影響，讀的時候把三張連成一句話。「它如何影響你」最好對到一個最近發生的具體場景，例如上週開會時的反應。後兩張並排讀：鑰匙是態度，轉化是接納後拿得到的東西，兩張同花色時，轉化常比你想的近。讀到不舒服的牌就先停下，不必一次讀完。',
    'spread.shadow.ex.0': '我為什麼特別看不慣愛炫耀的人？',
    'spread.shadow.ex.1': '每次被批評我都很難受，這背後是什麼？',
    'spread.shadow.ex.2': '我總在事情快成的時候放棄，這是什麼模式？',
    'spread.shadow.pos.0': '陰影的面貌',
    'spread.shadow.pos.0.desc': '你不願面對的特質，常常也是你在別人身上特別看不慣的那一點。',
    'spread.shadow.pos.1': '陰影的成因',
    'spread.shadow.pos.1.desc': '它從哪裡來：過去的經驗、成長環境，或某種恐懼。',
    'spread.shadow.pos.2': '它如何影響你',
    'spread.shadow.pos.2.desc': '這個陰影目前在生活裡造成的影響或反覆出現的模式。',
    'spread.shadow.pos.3': '接納的鑰匙',
    'spread.shadow.pos.3.desc': '幫助你承認並接納它的態度或觀點。',
    'spread.shadow.pos.4': '轉化的力量',
    'spread.shadow.pos.4.desc': '接納之後，這個特質可以轉化成的力量或天賦。',
    'spread.dream.name': '夢境解析',
    'spread.dream.label': '夢境解析',
    'spread.dream.desc': '先把夢的內容寫下來再抽牌：看夢的主題、潛意識想提醒什麼、它和現實的關聯，以及醒來後可以怎麼回應。',
    'spread.dream.howTo': '先拿「夢境主題」和你記下的夢對照：牌面的場景、人物或情緒若和夢裡某個細節重疊，就從那個細節讀起。再把「潛意識訊息」和「與現實的關聯」並排，前者說的是感受，後者指向生活中的哪件事，兩張合起來才是完整的提醒。「夢的指引」最好落成一件醒來後做得到的事，例如回一封拖著沒回的訊息。',
    'spread.dream.ex.0': '我最近反覆夢到考試遲到，這在提醒我什麼？',
    'spread.dream.ex.1': '夢到已過世的外婆對我說話，我可以怎麼理解這個夢？',
    'spread.dream.ex.2': '夢裡一直在找路卻找不到，這和我現在的生活有什麼關聯？',
    'spread.dream.pos.0': '夢境主題',
    'spread.dream.pos.0.desc': '這個夢的核心主題或情緒。',
    'spread.dream.pos.1': '潛意識訊息',
    'spread.dream.pos.1.desc': '夢背後想提醒你的事。',
    'spread.dream.pos.2': '與現實的關聯',
    'spread.dream.pos.2.desc': '夢反映的是生活裡哪一件事或哪一段關係。',
    'spread.dream.pos.3': '夢的指引',
    'spread.dream.pos.3.desc': '醒來之後可以採取的行動或調整。',
    'spread.celtic.name': '凱爾特十字',
    'spread.celtic.label': '凱爾特十字',
    'spread.celtic.desc': '適合一個明確、牽涉較廣的問題，想看清整件事的全貌時用。十張分成兩區：左邊的十字是事情本身，中央是處境與橫越其上的阻力，四周是根基、過去、目標與近期；右邊一列四張由下往上排，是你自己、環境、希望與恐懼，最上方是結果。牌陣出自偉特《圖像塔羅之鑰》（1911）。偉特會先挑一張宮廷牌當「指示者」代表問卜者，依年齡選：騎士代表四十歲以上的男性，國王代表四十歲以下的男性，皇后代表四十歲以上的女性，侍者代表較年輕的女性；現代多半不拘泥這條規則，本站也不另挑，十張都從牌堆抽出。偉特也說，第十張若是宮廷牌，表示事情最後落到那個人手上，結果主要取決於他。附註：本站用現代常見的編號，第 3 張在下、第 4 張在左、第 5 張在上、第 6 張在右；偉特原書是第 3 張在上、第 4 張在下，第 5、6 張依指示者的人物面向，放在他背後與面前。編號不同，各位置的意義相同。',
    'spread.celtic.howTo': '先讀第一、二張的十字，弄清處境和阻力的關係。再讀橫的時間軸：第四張、第一張、第六張，看事情在升溫還是降溫；直的第三、五張是根基與目標，落差越大越使不上力。接著讀右側一列：第七張的你和第八張的環境對照，看誰的影響大；最後把第九張和第十張並排，結果常正是你最期待或最怕的那件事。',
    'spread.celtic.ex.0': '我考慮離開待了八年的公司自己創業，這件事的全貌是什麼？',
    'spread.celtic.ex.1': '這段遠距離戀愛走到現在，我該怎麼看待它？',
    'spread.celtic.ex.2': '家裡為了賣老房子爭執了一年，我在其中該怎麼自處？',
    'spread.celtic.pos.0': '現況',
    'spread.celtic.pos.0.desc': '放在中央：你目前的處境，以及籠罩這件事的整體氣氛。',
    'spread.celtic.pos.1': '阻礙',
    'spread.celtic.pos.1.desc': '橫壓在第一張上：阻力或對立的力量。偉特說若這是一張吉牌，表示阻力不大，或某件本身是好事的東西在這件事上反而幫不上忙。',
    'spread.celtic.pos.2': '根基',
    'spread.celtic.pos.2.desc': '放在下方：這件事的基礎與遠因，已經成為事實、你只能以它為起點的部分。',
    'spread.celtic.pos.3': '過去',
    'spread.celtic.pos.3.desc': '放在左邊：剛過去、或正在消退的影響。',
    'spread.celtic.pos.4': '目標',
    'spread.celtic.pos.4.desc': '放在上方：你意識上追求的目標，或在目前條件下最好能達到、但還沒實現的結果。',
    'spread.celtic.pos.5': '未來',
    'spread.celtic.pos.5.desc': '放在右邊：即將發生、在近期起作用的影響。它說的是接下來一段時間的走向，不是最後的結局；結局看第十張。',
    'spread.celtic.pos.6': '態度',
    'spread.celtic.pos.6.desc': '右側一列最下方：你自己在這件事裡的態度與位置。',
    'spread.celtic.pos.7': '環境',
    'spread.celtic.pos.7.desc': '由下往上第二張：身邊的人與環境對這件事的影響。',
    'spread.celtic.pos.8': '希望與恐懼',
    'spread.celtic.pos.8.desc': '由下往上第三張：你對這件事的期待與擔心，兩者常是同一件事的兩面。',
    'spread.celtic.pos.9': '結果',
    'spread.celtic.pos.9.desc': '最上方：綜合前九張，事情最可能的結局。若這張看不出結論，偉特的做法是拿它當新的指示者重排一次；在本站可以把它的主題寫進問題，另做一次占卜。若這張是宮廷牌，偉特說事情最後會落到那張牌代表的人手上，結果主要取決於他；同樣可以拿這個人當主題再占一次，看他會怎麼影響結局。',
    'spread.horseshoe.name': '馬蹄鐵牌陣',
    'spread.horseshoe.label': '馬蹄鐵',
    'spread.horseshoe.desc': '七張牌排成拱形，從左下讀到右下：過去、現在、隱藏的影響，拱頂是眼前的障礙，再到周遭環境、建議與結果。',
    'spread.horseshoe.howTo': '拱形左右對稱的牌可以兩兩並排：先讀拱頂的障礙，再比「隱藏的影響」和「周遭環境」，看暗處的因素在你身上還是在別人身上；接著比「現在」和「建議」，看建議要你改的是哪個現況；最外側的「過去」和「結果」並排，看事情是在重演舊模式，還是走出新局。',
    'spread.horseshoe.ex.0': '我的網拍生意這半年停滯不前，問題在哪裡？',
    'spread.horseshoe.ex.1': '準備跟另一半談結婚的事，我要留意什麼？',
    'spread.horseshoe.ex.2': '想重回職場，接下來會遇到什麼、我該怎麼做？',
    'spread.horseshoe.pos.0': '過去',
    'spread.horseshoe.pos.0.desc': '影響這件事的過往經驗或事件。',
    'spread.horseshoe.pos.1': '現在',
    'spread.horseshoe.pos.1.desc': '目前的狀態與你面對的處境。',
    'spread.horseshoe.pos.2': '隱藏的影響',
    'spread.horseshoe.pos.2.desc': '你沒察覺到、卻正在起作用的因素。',
    'spread.horseshoe.pos.3': '眼前的障礙',
    'spread.horseshoe.pos.3.desc': '位在拱頂：目前最需要克服的困難，也是整個牌陣的轉折點。',
    'spread.horseshoe.pos.4': '周遭環境',
    'spread.horseshoe.pos.4.desc': '身邊的人與環境對這件事的態度與影響。',
    'spread.horseshoe.pos.5': '建議',
    'spread.horseshoe.pos.5.desc': '牌建議你採取的行動或態度。',
    'spread.horseshoe.pos.6': '結果',
    'spread.horseshoe.pos.6.desc': '照建議去做，事情最可能的結果。',
    'spread.treeOfLife.name': '生命之樹',
    'spread.treeOfLife.label': '生命之樹',
    'spread.treeOfLife.desc': '依卡巴拉生命之樹的十個質點排出，每個質點對應生命的一個層面，從最高的靈性（王冠）一路落到現實生活（王國）。適合做整體的人生檢視，不適合單一的是非問題。',
    'spread.treeOfLife.howTo': '依三根柱子讀：智慧、仁慈、勝利一柱偏擴張與給予，理解、嚴厲、榮耀一柱偏收斂與限制，王冠、美、根基、王國是中柱。先把同一層左右兩張並排比，例如仁慈對嚴厲，看你是給得太多還是收得太緊；再由上往下讀中柱，看最高的方向有沒有一路落到王國的現實裡。',
    'spread.treeOfLife.ex.0': '我現在的人生整體處在什麼狀態？',
    'spread.treeOfLife.ex.1': '三十五歲這個階段，我生活裡哪個層面最需要調整？',
    'spread.treeOfLife.ex.2': '離婚後重新開始，我的內在和現實各需要什麼？',
    'spread.treeOfLife.pos.0': '王冠・靈性核心',
    'spread.treeOfLife.pos.0.desc': '最高的目標與靈性方向：你這一生想成為什麼。',
    'spread.treeOfLife.pos.1': '智慧・創造的動力',
    'spread.treeOfLife.pos.1.desc': '推動你的原始動力與靈感，事情最初的火花。',
    'spread.treeOfLife.pos.2': '理解・結構與限制',
    'spread.treeOfLife.pos.2.desc': '讓想法成形的結構、責任與限制，也包括你必須接受的現實。',
    'spread.treeOfLife.pos.3': '仁慈・給予與成長',
    'spread.treeOfLife.pos.3.desc': '你得到的支持與擴展的機會，以及你怎麼慷慨待人。',
    'spread.treeOfLife.pos.4': '嚴厲・紀律與割捨',
    'spread.treeOfLife.pos.4.desc': '需要的紀律與界線，或必須面對的衝突與割捨。',
    'spread.treeOfLife.pos.5': '美・內在平衡',
    'spread.treeOfLife.pos.5.desc': '整棵樹的中心：你的自我認同，也是各種力量取得平衡的地方。',
    'spread.treeOfLife.pos.6': '勝利・情感與慾望',
    'spread.treeOfLife.pos.6.desc': '情感、慾望，以及讓你堅持下去的動力。',
    'spread.treeOfLife.pos.7': '榮耀・思考與溝通',
    'spread.treeOfLife.pos.7.desc': '理性、溝通與學習：你怎麼分析與表達。',
    'spread.treeOfLife.pos.8': '根基・潛意識與習慣',
    'spread.treeOfLife.pos.8.desc': '潛意識、夢與日常習慣，支撐一切的底層模式。',
    'spread.treeOfLife.pos.9': '王國・現實生活',
    'spread.treeOfLife.pos.9.desc': '一切落到現實的樣子：身體、家庭、工作與物質環境。',
    'spread.astroHouses.name': '占星十二宮',
    'spread.astroHouses.label': '占星十二宮',
    'spread.astroHouses.desc': '十二張牌對應占星的十二宮，每一宮代表一個生活領域，適合鳥瞰近期生活各方面的狀態。',
    'spread.astroHouses.howTo': '十二宮可以兩兩對宮來讀：第一宮自我對第七宮伴侶、第二宮自己的錢對第八宮共有的資源、第四宮家庭對第十宮事業，依此類推，對宮的兩張常是同一件事的兩端。先找出牌面最強烈的一兩宮當重點，再讀它的對宮，看那股力量從哪裡被平衡或拉扯。最後標出大阿卡納落在哪幾宮，那幾個領域是近期的重心。',
    'spread.astroHouses.ex.0': '接下來三個月，我生活各方面的狀態如何？',
    'spread.astroHouses.ex.1': '最近覺得哪裡都不順，是哪個領域在拖累我？',
    'spread.astroHouses.ex.2': '搬到新城市生活半年，我各方面適應得怎麼樣？',
    'spread.astroHouses.pos.0': '第一宮・自我',
    'spread.astroHouses.pos.0.desc': '你給人的第一印象、個人狀態與新的開始。',
    'spread.astroHouses.pos.1': '第二宮・財務',
    'spread.astroHouses.pos.1.desc': '收入、財產，以及你重視的價值。',
    'spread.astroHouses.pos.2': '第三宮・溝通',
    'spread.astroHouses.pos.2.desc': '溝通、學習、短程往來，以及和兄弟姊妹、鄰居的關係。',
    'spread.astroHouses.pos.3': '第四宮・家庭',
    'spread.astroHouses.pos.3.desc': '家庭、居所與內心的根基。',
    'spread.astroHouses.pos.4': '第五宮・創造',
    'spread.astroHouses.pos.4.desc': '創作、戀愛、娛樂，以及和子女的關係。',
    'spread.astroHouses.pos.5': '第六宮・健康',
    'spread.astroHouses.pos.5.desc': '日常工作、作息與健康習慣。',
    'spread.astroHouses.pos.6': '第七宮・伴侶',
    'spread.astroHouses.pos.6.desc': '伴侶、合作對象與一對一的關係。',
    'spread.astroHouses.pos.7': '第八宮・轉化',
    'spread.astroHouses.pos.7.desc': '共有的資源、親密關係、危機與深層的轉變。',
    'spread.astroHouses.pos.8': '第九宮・信念',
    'spread.astroHouses.pos.8.desc': '信仰與人生觀、高等教育、遠行與異國事物。',
    'spread.astroHouses.pos.9': '第十宮・事業',
    'spread.astroHouses.pos.9.desc': '事業、社會地位與公開形象。',
    'spread.astroHouses.pos.10': '第十一宮・人際',
    'spread.astroHouses.pos.10.desc': '朋友、社群，以及你對未來的願景。',
    'spread.astroHouses.pos.11': '第十二宮・潛意識',
    'spread.astroHouses.pos.11.desc': '潛意識、隱藏的事、獨處與休養。',
    'spread.hexagram.name': '六芒星牌陣',
    'spread.hexagram.label': '六芒星',
    'spread.hexagram.desc': '七張牌排成兩個交疊的三角形：朝上的三角是過去、現在、未來的時間線，朝下的三角是對策、環境與你的內心，中央是結果。適合一件已經在進行、想看清來龍去脈與因應方法的事。這是日本與台灣常見的現代牌陣，來源不明，各家的牌位與擺法也不盡相同，本站採用最通行的版本。',
    'spread.hexagram.howTo': '先讀朝上的三角（過去、現在、未來），看時間線是遞進還是轉折。再讀朝下的三角，把「環境」和「你的內心」並排，看阻力在外面還是在你心裡，「對策」通常是在回應兩者中比較弱的那一張。最後讀中央的結果，拿它和「未來」比較：方向一致，代表照現在的路走就會到那裡；不一致時，差別多半在你有沒有照對策去做。',
    'spread.hexagram.ex.0': '和男友在討論同居，我該怎麼面對接下來的變化？',
    'spread.hexagram.ex.1': '新接的專案進度落後，我要怎麼扭轉局面？',
    'spread.hexagram.ex.2': '我開的手搖飲店生意下滑，接下來要怎麼調整？',
    'spread.hexagram.pos.0': '過去',
    'spread.hexagram.pos.0.desc': '影響這件事的前因：已經發生、仍在作用的經歷或選擇。正位多半是可以倚靠的經驗，逆位常是還沒消化完、仍在拖著你的舊事。',
    'spread.hexagram.pos.1': '現在',
    'spread.hexagram.pos.1.desc': '你此刻的處境與這件事的核心狀態。正位表示這股力量正順利運作；逆位常是它過度、不足或卡住，也就是眼前最該處理的地方。',
    'spread.hexagram.pos.2': '未來',
    'spread.hexagram.pos.2.desc': '照目前的方向，接下來一段時間最可能出現的變化，不是最後結論。正位多半順勢；逆位提醒你可能遇到延遲或轉折。',
    'spread.hexagram.pos.3': '對策',
    'spread.hexagram.pos.3.desc': '牌建議你採取的做法或態度。正位就照牌面的動作去做；逆位提醒你這個方向用過頭或用錯地方，先修正再出手。',
    'spread.hexagram.pos.4': '環境',
    'spread.hexagram.pos.4.desc': '身邊的人、環境與時機對這件事的影響。正位多半是助力或中性的條件；逆位表示外在有阻力、誤會或時機不利，要預留空間。',
    'spread.hexagram.pos.5': '你的內心',
    'spread.hexagram.pos.5.desc': '你對這件事真正的想法與感受，未必是說出口的那些。正位是心意清楚；逆位常是矛盾、不安，或你還不願承認的情緒。',
    'spread.hexagram.pos.6': '結果',
    'spread.hexagram.pos.6.desc': '放在中央，綜合前六張最可能的結局。正位多半是值得期待的方向；逆位常是結果打折或需要更久，回頭看對策還能做什麼。',
    'spread.reunion.name': '復合牌陣',
    'spread.reunion.label': '復合',
    'spread.reunion.desc': '分開之後還在想要不要復合，或想好好放下時用。從你自己出發：先看關係為什麼結束、你現在走到哪裡，再看重新開始的阻礙、你真正需要的東西，以及照目前走下去的樣子。對方那張只是可能的樣貌，不是對方的答案；要不要復合，最後仍要靠你們實際談過才知道。',
    'spread.reunion.howTo': '先把「關係結束的原因」和「復合的阻礙」並排：兩張相近，表示當初分開的問題還在，復合多半會重演；不同時，才有重新開始的空間。再比「你現在的狀態」和「你真正需要的」，如果需要的是安全感或被肯定，不一定只有這個人給得了。「照目前走下去」要和建議一起讀，前者是不改變時的走向，建議才是你能動手的地方。',
    'spread.reunion.ex.0': '分手半年了，我還是想復合，這份想法背後是什麼？',
    'spread.reunion.ex.1': '最近和前任又開始聯絡，我該怎麼看待這段重新出現的關係？',
    'spread.reunion.ex.2': '我一直放不下上一段感情，要怎麼往前走？',
    'spread.reunion.pos.0': '關係結束的原因',
    'spread.reunion.pos.0.desc': '這段關係走到分開的主要原因。正位多半是清楚可辨的事件或差異；逆位常是一直沒說開、你們都在迴避的那一塊。',
    'spread.reunion.pos.1': '你現在的狀態',
    'spread.reunion.pos.1.desc': '分開後的你，情緒恢復到哪裡、生活有沒有站穩。正位表示你已有餘力看清這段關係；逆位常是還在傷口裡，想復合可能出於不甘或寂寞。',
    'spread.reunion.pos.2': '對方可能的狀態',
    'spread.reunion.pos.2.desc': '對方現在可能的處境與心情。這只是牌給的一個角度，不是讀心，也不是對方的答案；正位多半較平穩，逆位常是對方也有糾結或刻意保持距離。',
    'spread.reunion.pos.3': '復合的阻礙',
    'spread.reunion.pos.3.desc': '如果要重新開始，最需要面對的問題。正位多半是可以談、可以改的具體障礙；逆位常是同樣的問題被忽略，或外在條件仍沒有改變。',
    'spread.reunion.pos.4': '你真正需要的',
    'spread.reunion.pos.4.desc': '想復合的念頭底下，你真正渴望的東西：可能是這個人，也可能是安全感、被理解或一個好好的結束。逆位提醒你，這份需要可能被恐懼包裝成想復合。',
    'spread.reunion.pos.5': '照目前走下去',
    'spread.reunion.pos.5.desc': '照你們現在的互動和你目前的心態，接下來最可能的發展，不是定局。正位多半是朝和緩或重新連結的方向；逆位常是停在原地或重演舊模式。',
    'spread.reunion.pos.6': '給你的建議',
    'spread.reunion.pos.6.desc': '這段時間最值得你採取的態度或行動，不論最後有沒有復合都用得上。正位照著做；逆位提醒你先收一收，例如先停下反覆查看對方動態的習慣。',
    'spread.newLove.name': '新戀情牌陣',
    'spread.newLove.label': '新戀情',
    'spread.newLove.desc': '單身想遇見新對象，或正在曖昧、還沒確定關係時用。從你自己的狀態出發，看你和什麼樣的人容易互相吸引、緣分從哪裡長出來、卡在哪裡，以及可以怎麼做。牌不回答「什麼時候會遇到」，而是幫你看清楚自己可以準備什麼。',
    'spread.newLove.howTo': '先把第一、二張並排：你的狀態和你吸引來的人常互相呼應，例如你那張是想要安穩的錢幣，第二張卻是衝動的權杖騎士，就值得想想落差從哪裡來。再把「相遇與靠近的契機」和「阻礙」放在一起，契機常在阻礙的反方向。最後的建議只挑一件下週做得到的事，例如答應一次朋友的聚會邀約。',
    'spread.newLove.ex.0': '我和最近認識的他互動不錯，要怎麼讓關係自然地往前走？',
    'spread.newLove.ex.1': '單身三年了，我在感情上需要準備什麼？',
    'spread.newLove.ex.2': '交友軟體上聊得來的人不少，卻都走不下去，我卡在哪裡？',
    'spread.newLove.pos.0': '你的感情狀態',
    'spread.newLove.pos.0.desc': '你此刻對愛情的準備程度與心態。正位表示你有餘裕迎接新的人；逆位常是還帶著舊傷、太急，或防備心太重。',
    'spread.newLove.pos.1': '吸引來的對象',
    'spread.newLove.pos.1.desc': '曖昧中讀成對方和這段互動的樣子；還沒有對象時，讀成你容易吸引的那類人。正位是自然的吸引，逆位常是熱度不穩或期待不對等。',
    'spread.newLove.pos.2': '相遇與靠近的契機',
    'spread.newLove.pos.2.desc': '緣分容易從哪裡長出來：工作、朋友聚會、共同興趣或線上。曖昧中則讀成拉近距離的方式。逆位提醒你生活圈可能太窄，或步調太忙。',
    'spread.newLove.pos.3': '阻礙',
    'spread.newLove.pos.3.desc': '讓關係難以開始或往前的因素，可能是你的顧慮、對方的狀態或現實條件。正位是看得見的障礙；逆位常是你沒察覺的習慣，例如太快下定論。',
    'spread.newLove.pos.4': '建議',
    'spread.newLove.pos.4.desc': '這段時間在感情上最值得採取的行動或態度。正位照著做；逆位提醒你這個做法要收一點，例如主動，但別步步緊逼。',
    'spread.exam.name': '考試與學業牌陣',
    'spread.exam.label': '考試學業',
    'spread.exam.desc': '準備學測、國考、證照或期末考時用：看你目前的準備狀態、容易失分的地方、可以借力的資源、上考場時的心態，以及接下來該怎麼調整。牌不預測分數，也不判斷會不會上榜；結果仍取決於接下來的準備。',
    'spread.exam.howTo': '先把「準備狀態」和「弱點與盲點」並排：兩張若在講同一件事（例如都指向分心或拖延），那就是最該先處理的地方。再看「助力」能不能直接補上那個弱點。接著比「應考時的心態」和準備狀態：心態那張明顯比較弱時，代表實力夠，要練的是臨場，例如用計時的模擬考練節奏。最後把建議寫成每天做得到的一件事。',
    'spread.exam.ex.0': '離國考還有半年，我的準備方向需要調整什麼？',
    'spread.exam.ex.1': '模擬考數學一直卡在同一個程度，我的問題在哪裡？',
    'spread.exam.ex.2': '一邊上班一邊準備證照，我要怎麼安排才讀得下去？',
    'spread.exam.pos.0': '準備狀態',
    'spread.exam.pos.0.desc': '到目前為止的準備程度與讀書節奏。正位表示基礎在、方向對；逆位常是進度落後、範圍抓不準，或讀得多卻沒有吸收。',
    'spread.exam.pos.1': '弱點與盲點',
    'spread.exam.pos.1.desc': '最可能讓你失分或卡住的地方：某個科目、讀書方法或作息。正位是你已經知道、只是還沒處理的；逆位常是你沒意識到的盲點。',
    'spread.exam.pos.2': '助力',
    'spread.exam.pos.2.desc': '可以借力的資源：老師、同學、讀書會、考古題或你自己的某個強項。正位表示助力就在手邊；逆位提醒你，有現成的幫助你還沒開口要。',
    'spread.exam.pos.3': '應考時的心態',
    'spread.exam.pos.3.desc': '走進考場時你可能的狀態。正位多半能穩定發揮；逆位常是緊張、粗心或太在意結果，考前就要先練習怎麼應對這種情緒。',
    'spread.exam.pos.4': '建議',
    'spread.exam.pos.4.desc': '從現在到考試前最值得做的調整。正位照著牌面的動作去做；逆位提醒你先停掉某個沒效率的習慣，例如熬夜硬讀。',
    'spread.interview.name': '面試與求職牌陣',
    'spread.interview.label': '面試求職',
    'spread.interview.desc': '找工作、投履歷、準備面試或等待錄取時用：看你帶去的優勢、對方可能在找什麼、要補強的地方、面試當下要留意的事，以及接下來該怎麼做。牌不判斷會不會錄取，而是幫你把準備做到位；同時在等幾家公司時，可以每家各做一次。',
    'spread.interview.howTo': '先把「你帶去的優勢」和「對方在找什麼」並排，這是整個牌陣的核心：兩張相合，面試時就把那項優勢放在最前面講；兩張錯開，就要把你的經驗翻譯成對方在意的語言。再把「需要補強的地方」和「面試當下要留意」連起來讀，前者是事前準備，後者是臨場應變，常是同一個弱點在兩個時間點出現。',
    'spread.interview.ex.0': '下週要面試一家外商，我要怎麼準備才能發揮實力？',
    'spread.interview.ex.1': '投了二十幾封履歷都沒有回音，我的求職方式哪裡需要調整？',
    'spread.interview.ex.2': '想轉換跑道去做行銷，面試時我可以怎麼呈現自己？',
    'spread.interview.pos.0': '你帶去的優勢',
    'spread.interview.pos.0.desc': '這次求職你最拿得出手的能力、經驗或特質。正位表示優勢明顯，要準備具體例子；逆位常是你低估了自己，或優勢沒寫進履歷和自我介紹裡。',
    'spread.interview.pos.1': '對方在找什麼',
    'spread.interview.pos.1.desc': '這份職缺或這家公司可能最看重的條件。正位多半和你的優勢相合；逆位提醒你，對方要的可能和職缺描述不同，面試前多查公司近況。',
    'spread.interview.pos.2': '需要補強的地方',
    'spread.interview.pos.2.desc': '履歷、作品集、專業知識或表達裡最需要補上的一塊。正位是短時間內能準備好的；逆位常是你一直迴避、最怕被問到的部分。',
    'spread.interview.pos.3': '面試當下要留意',
    'spread.interview.pos.3.desc': '現場容易影響表現的因素：緊張、說太多、談薪水或和面試官的互動。正位多半能順利應對；逆位提醒你先預演最怕被問的題目。',
    'spread.interview.pos.4': '建議',
    'spread.interview.pos.4.desc': '這段求職期間最值得採取的行動或態度。正位照著做；逆位提醒你調整做法，例如別只是大量投遞，挑幾家用心準備。',
    'spread.threeChoice.name': '三選一牌陣',
    'spread.threeChoice.label': '三選一',
    'spread.threeChoice.desc': '有三個選項要比較時用，例如三份工作邀約、三間學校或三個住處。最下方是你真正在乎什麼，中間一排是 A、B、C 三個選項的現況，上方一排是各自最可能的結果，由下往上讀。只有兩個選項時，請用二擇一。',
    'spread.threeChoice.howTo': '先讀最下方「你真正在乎什麼」，把它當成這次比較的標準。接著一層一層橫著讀：先並排比三張現況，再並排比三張結果，不要先把一個選項從下讀到上。最後把每個結果拿回來和底部那張對照：結果最好的不一定是答案，最貼近你在乎的那一個才是。三條都不理想時，可能還有第四個選項沒被想到。',
    'spread.threeChoice.ex.0': '三家公司都給了錄取通知，哪一家最適合現階段的我？',
    'spread.threeChoice.ex.1': '畢業後要讀研究所、去打工度假，還是直接就業？',
    'spread.threeChoice.ex.2': '想搬家，看了三個地方都各有優缺點，各會帶給我什麼樣的生活？',
    'spread.threeChoice.pos.0': '你真正在乎什麼',
    'spread.threeChoice.pos.0.desc': '做這個決定時你最重視的東西，例如穩定、成長、自由或身邊的人。先讀它，再拿它當尺量三個選項；逆位常是你在乎的被別人的期待蓋住了。',
    'spread.threeChoice.pos.1': '選項 A 的現況',
    'spread.threeChoice.pos.1.desc': 'A 這條路此刻的條件與你對它的真實感受：什麼已經到位、什麼還沒。正位多半是起點穩、你也願意；逆位常是條件不足或你心裡在勉強。',
    'spread.threeChoice.pos.2': '選項 B 的現況',
    'spread.threeChoice.pos.2.desc': 'B 這條路此刻的條件與你的感受，和 A、C 的現況並排比較。正位是基礎扎實或心甘情願；逆位提醒你留意被美化或被低估的地方。',
    'spread.threeChoice.pos.3': '選項 C 的現況',
    'spread.threeChoice.pos.3.desc': 'C 這條路此刻的條件與你的感受。三張現況裡若只有它特別亮或特別暗，先問自己為什麼；逆位常是資訊不足或太快下的判斷。',
    'spread.threeChoice.pos.4': '選項 A 的結果',
    'spread.threeChoice.pos.4.desc': '選 A 並照目前的條件走下去，最可能的結果。正位多半能得到你要的；逆位常是結果打折、比預期慢，或得到的不是你最在乎的東西。',
    'spread.threeChoice.pos.5': '選項 B 的結果',
    'spread.threeChoice.pos.5.desc': '選 B 最可能的結果，和 A、C 的結果放在同一排比較。正位是值得期待的方向；逆位不等於失敗，常表示要付出比預期多的代價。',
    'spread.threeChoice.pos.6': '選項 C 的結果',
    'spread.threeChoice.pos.6.desc': '選 C 最可能的結果。正位是值得期待的方向，但若和你在乎的無關，也不一定是最好的選擇；逆位提醒你這條路的風險或代價較高。',
    'suit.major': '大阿卡納',
    'suit.wands': '權杖',
    'suit.cups': '聖杯',
    'suit.swords': '寶劍',
    'suit.pentacles': '錢幣',
    'orientation.upright': '正位',
    'orientation.reversed': '逆位',
    'tendency.yes': '傾向是',
    'tendency.no': '傾向否',
    'tendency.unclear': '不明朗',
    'history.title': '占卜記錄',
    'history.filter.allSpreads': '所有牌陣',
    'history.filter.allTags': '所有標籤',
    'history.filter.favorite': '只看收藏',
    'history.clear': '清除記錄',
    'history.empty': '尚無符合條件的記錄',
    'history.none': '還沒有占卜記錄',
    'history.none.cta': '開始占卜',
    'history.item.note': '筆記：',
    'history.item.favorite': '收藏',
    'history.item.open': '查看結果：{spread}，{time}',
    'stats.title': '統計分析',
    'stats.empty': '尚無統計資料',
    'stats.readings.title': '占卜次數',
    'stats.readings.unit': '次',
    'stats.cards.title': '總抽牌數',
    'stats.cards.unit': '張',
    'stats.uprightPct.title': '正位比例',
    'stats.reversedPct.title': '逆位比例',
    'stats.orientation.unit': '{n} 張',
    'stats.favorites.title': '收藏數量',
    'stats.favorites.unit': '個收藏',
    'stats.avg.title': '平均每次',
    'stats.avg.unit': '張牌',
    'stats.trend.title': '近 12 個月占卜趨勢',
    'stats.trend.bar': '{month}：{n} 次',
    'stats.suits.title': '花色分布',
    'stats.topSpreads.title': '常用牌陣',
    'stats.topCards.title': '最常抽到的牌',
    'stats.item.count': '{n} 次（{pct}%）',
    'stats.legend.item': '{suit}：{n} 張（{pct}%）',
    'db.title': '資料庫',
    'db.search.placeholder': '搜尋牌名、關鍵詞或牌義…',
    'db.search.label': '搜尋牌卡',
    'db.search.count': '找到 {n} 張牌',
    'db.deckHistory.offline': '知識庫需要網路才能載入，連上網路後重新整理頁面即可。',
    'db.seg.label': '資料庫內容',
    'db.seg.cards': '牌卡',
    'db.seg.library': '知識庫',
    'db.filter.kind': '依類別篩選',
    'db.filter.suit': '依花色篩選',
    'db.filter.all': '全部',
    'db.filter.pip': '數字牌',
    'db.filter.court': '宮廷牌',
    'db.hit.keyword': '正位關鍵詞',
    'db.hit.keywordReversed': '逆位關鍵詞',
    'db.hit.upright': '正位牌義',
    'db.hit.reversed': '逆位牌義',
    'db.hit.symbolism': '牌面描述',
    'db.hit.origin': '源流',
    'db.hit.waite': '偉特 1911 原文語詞',
    'db.hit.waiteAdd': '偉特 1911 補充牌義',
    'db.hit.mofa': 'mofatarot 關鍵詞',
    'db.library.cards': '出現在這些牌',
    'db.library.sampleCards': '這次抽到的牌',
    'db.library.sampleCard': '{pos}：{name}（{ori}）',
    'db.seg.symbols': '符號',
    'db.symbols.listTitle': '所有符號',
    'db.symbols.intro': '點一個符號，看它畫在哪些牌上、畫在哪裡。',
    'db.symbols.count': '{n} 張',
    'db.symbols.button': '{title}，{n} 張牌',
    'db.symbols.detail': '畫著{title}的牌',
    'db.symbols.offline': '符號索引需要網路才能載入，連上網路後重新整理頁面即可。',
    'db.filter.corr': '對應',
    'db.hit.alias': '別名',
    'db.hit.names': '其他牌系的名稱',
    'db.hit.symbol': '畫面上的符號',
    'db.hit.study': '學業',
    'db.hit.growth': '成長',
    'db.hit.positions': '放在不同牌位',
    'db.hit.journal': '書寫提問',
    'db.hit.person': '當它代表一個人',
    'db.hit.combos': '常見組合',
    'db.hit.related': '相關的牌',
    'history.filter.spreadLabel': '依牌陣篩選',
    'history.filter.tagLabel': '依標籤篩選',
    'note.label': '筆記內容',
    'db.empty': '尚無符合條件的牌卡',
    'learn.title': '學習',
    'learn.mode.flash': '閃卡',
    'learn.mode.quiz': '測驗',
    'learn.mode.label': '學習方式',
    'learn.scope.label': '學習範圍',
    'learn.scope.all': '全部 78 張',
    'learn.mastery.title': '熟練度',
    'learn.mastery.count': '已掌握 {n} / {total}',
    'learn.mastery.cell': '{name} · 熟練度 {lv}/{max}',
    'learn.mastery.legend': '熟練度圖例',
    'learn.mastery.legend.low': '生疏',
    'learn.mastery.legend.high': '熟練',
    'learn.reset': '重設學習進度',
    'learn.empty.noMeaning': '此範圍沒有可用的牌義，請換一個範圍。',
    'learn.empty.tooFew': '此範圍牌數不足以出題，請換一個範圍。',
    'learn.streak.days': '連續 {n} 天',
    'learn.streak.idle': '今天還沒練習',
    'learn.streak.best': '最佳紀錄 {n} 天',
    'learn.streak.none': '練一張閃卡或答一題測驗就開始計算',
    'learn.streak.continue': '{best} · 今天再練一次就能延續',
    'learn.flash.hint': '點一下看牌義',
    'learn.flash.hard': '還不熟',
    'learn.flash.easy': '記得了',
    'learn.flash.more': '繼續閱讀',
    'learn.flash.less': '收合',
    'learn.flash.progress': '本輪已看 {n} 張',
    'learn.quiz.progress': '第 {n} / {total} 題',
    'learn.quiz.promptArt': '這張牌正位的關鍵詞是？',
    'learn.quiz.promptKeywords': '這組正位關鍵詞屬於哪張牌？',
    'learn.quiz.promptCard': '「{name}」正位的關鍵詞是？',
    'learn.quiz.promptKeywordsReversed': '這組逆位關鍵詞屬於哪張牌？',
    'learn.quiz.promptCardReversed': '「{name}」逆位的關鍵詞是？',
    'learn.quiz.promptSituation': '問「{domain}」時抽到這張牌（{ori}），讀法如下。這是哪張牌？',
    'learn.quiz.promptPerson': '這張牌（{ori}）代表一個人時，會是這樣的人。這是哪張牌？',
    'learn.quiz.promptSymbol': '「{symbol}」畫在哪一張牌上？',
    'learn.quiz.thisCard': '這張牌',
    'learn.quiz.mark.correct': '正確答案',
    'learn.quiz.mark.chosen': '你的答案',
    'learn.quiz.feedback.correct': '答對了',
    'learn.quiz.feedback.wrong': '答錯，正確答案是：{answer}',
    'learn.quiz.explain.pickCard': '你選的是{name}，它的{ori}關鍵詞是：{keywords}。',
    'learn.quiz.explain.pickSet': '你選的是{name}{ori}的關鍵詞。',
    'learn.quiz.viewCard': '看卡片詳情',
    'learn.quiz.next': '下一題',
    'learn.quiz.toResult': '看結果',
    'learn.quiz.score': '答對 {n} / {total}',
    'learn.quiz.rate': '正確率 {pct}%',
    'learn.quiz.reviewTitle': '再複習這幾張',
    'learn.quiz.reviewReversed': '{name}（逆位）',
    'learn.quiz.perfect': '全部答對，這個範圍你已經很熟了。',
    'learn.quiz.again': '再來一輪',
    'learn.quiz.toFlash': '回到閃卡',
    'settings.title': '設定',
    'settings.theme.title': '外觀主題',
    'settings.theme.auto': '跟隨系統',
    'settings.theme.light': '淺色模式',
    'settings.theme.dark': '深色模式',
    'settings.theme.neon': '霓虹占卜館',
    'settings.theme.neon.desc': '夜色配上霓虹光，配色依版型調整；線稿模式的牌依花色發光',
    'settings.template.title': '版型',
    'settings.template.minimal': '簡約',
    'settings.template.minimal.desc': '原本的版面：上方分頁列，黑白色調',
    'settings.template.aurora': '星夜玻璃',
    'settings.template.aurora.desc': '預設版型：夜藍與淡紫、霧面玻璃與柔金，下方浮動導覽列',
    'settings.template.editorial': '現代編輯',
    'settings.template.editorial.desc': '冷灰與墨黑、一抹朱紅，雜誌式大標題與方塊版面',
    'settings.template.immersive': '沉浸手勢',
    'settings.template.immersive.desc': '電影裡的占卜屋：燭光、絲絨與黃銅，牌堆躺在桌布上；向上滑動抽牌，左右滑動換牌',
    'settings.visual.title': '視覺樣式',
    'settings.visual.text': '純文字模式（預設）',
    'settings.visual.text.desc': '只顯示牌名、正逆位與關鍵詞，不載入圖片。',
    'settings.visual.api': '牌圖模式',
    'settings.visual.api.desc': '1909 年版偉特牌的原始牌圖（公有領域）。看過的牌圖會留在裝置上，離線也能顯示。',
    'settings.visual.line': '線稿模式',
    'settings.visual.name.text': '純文字模式',
    'settings.visual.name.api': '牌圖模式',
    'settings.visual.name.line': '線稿模式',
    'settings.visual.line.desc': '本站自繪的 78 張彩色插畫，構圖依循偉特牌。',
    'settings.pref.title': '顯示偏好',
    'settings.pref.interactiveDraw': '互動選牌',
    'settings.pref.interactiveDraw.desc': '占卜時親手從牌堆中選牌；關閉則直接翻出結果',
    'settings.pref.spreadInfo': '顯示牌陣說明',
    'settings.pref.spreadInfo.desc': '在牌陣選單與「關於此牌陣」顯示牌陣說明與牌位讀法（逐張解讀照常列出牌位讀法）',
    'settings.pref.shortcuts': '啟用鍵盤快捷鍵',
    'settings.pref.shortcuts.desc': '空白鍵＝開始占卜　T＝切換主題　1–6＝切換分頁',
    'settings.pref.haptics': '觸覺回饋',
    'settings.pref.haptics.desc': '抽牌與翻牌時輕輕震動（裝置支援時）',
    'settings.data.title': '資料管理',
    'settings.data.stats': '目前共 {n} 筆占卜記錄（上限 {max} 筆），約佔 {kb} KB 儲存空間。',
    'settings.data.export': '匯出資料',
    'settings.data.import': '匯入資料',
    'settings.data.clearAll': '清除所有資料',
    'shichen.unknown': '不詳',
    'shichen.0': '子　23:00–01:00',
    'shichen.1': '丑　01:00–03:00',
    'shichen.2': '寅　03:00–05:00',
    'shichen.3': '卯　05:00–07:00',
    'shichen.4': '辰　07:00–09:00',
    'shichen.5': '巳　09:00–11:00',
    'shichen.6': '午　11:00–13:00',
    'shichen.7': '未　13:00–15:00',
    'shichen.8': '申　15:00–17:00',
    'shichen.9': '酉　17:00–19:00',
    'shichen.10': '戌　19:00–21:00',
    'shichen.11': '亥　21:00–23:00',
    'profile.title': '個人化',
    'profile.birthday.label': '你的生日',
    'profile.shichen.label': '出生時辰',
    'profile.desc': '用生日與出生時辰算出你的五張個人牌，顯示在占卜分頁上方。生日與時辰只存在這台裝置。',
    'profile.clear': '清除生日',
    'profile.empty': '尚未設定生日',
    'profile.preview.item': '{pos}：{name} {ori}',
    'profile.pos.origin': '源',
    'profile.pos.inheritance': '承',
    'profile.pos.self': '身',
    'profile.pos.legacy': '續',
    'profile.pos.return': '歸',
    'profile.note.deal.title': '這五張牌怎麼來的',
    'profile.note.deal.text': '用你的生日與出生時辰，從 78 張牌裡不放回地發出五張，每張各有正位或逆位。同一組生日與時辰永遠得到同樣的五張；不同的日期或時辰（「不詳」也算一種）各得一組，不會有兩組完全相同。五張依序是——源：你的起點與根源；承：你從家庭或過去承接下來的東西；身：現在的你；續：你想延續、留給別人的東西；歸：你最終想走向的地方。',
    'profile.note.frame.title': '源、承、身、續、歸是本站自訂的',
    'profile.note.frame.text': '這五個位置不出自任何塔羅或命理傳統，是本站設計的讀牌框架。五個位置同等重要，沒有主次之分。',
    'profile.note.shichen.title': '時辰只用來計時',
    'profile.note.shichen.text': '十二時辰是中國傳統的計時法，一個時辰兩小時。八字（四柱）也用它定出時柱，但本站只借用計時，不套用八字的柱義與命理解釋。子時跨過午夜，本站不做早子時、晚子時的換日：日期就是你填的那一天。',
    'profile.note.legacy.title': '與常見的「生日牌」算法不同',
    'profile.note.legacy.text': 'Mary K. Greer 在《Tarot for Your Self》（1984）推廣的生日牌，是把出生的月、日、年相加，再把各位數反覆相加化簡，得出大阿卡納裡的「人格牌」與「靈魂牌」，所以很多人會得到同一組。本站不做數字化簡，而是照上面的方式從全部 78 張裡發牌。',
    'profile.note.closing': '同樣的五張牌會一直跟著你，適合在不同時期回頭重讀，看看自己對它們的理解有什麼改變。',
    'card.loading': '載入中…',
    'card.imageFailed': '圖片暫時無法載入',
    'card.sub': '{en} · {suit} · {number}',
    'card.sub.minor': '{en} · {suit}',
    'card.sub.drawn': '{sub} · 本次抽到{ori}',
    'card.meaning.drawn': '（本次抽到）',
    'card.seg.label': '卡片內容',
    'card.seg.meaning': '牌義',
    'card.seg.icon': '圖義',
    'card.seg.context': '情境',
    'card.seg.lore': '源流',
    'card.viewArt': '放大檢視「{name}」的牌面',
    'card.viewer.title': '{name}的牌面',
    'card.depth.title': '深度解說',
    'card.symbolism.title': '牌面描述',
    'card.icon.title': '符號解讀',
    'card.image.upright': '正位圖面',
    'card.image.reversed': '逆位圖面',
    'card.context.title': '情境牌義',
    'card.context.love': '感情',
    'card.context.career': '事業',
    'card.context.wealth': '財務',
    'card.context.wellbeing': '身心',
    'card.context.study': '學業',
    'card.context.growth': '成長',
    'card.positions.title': '放在不同牌位',
    'card.context.ori.label': '看哪一面',
    'card.context.more': '細分：{list}',
    'card.context.subtopics': '細分主題',
    'card.person.title': '當它代表一個人',
    'card.person.note': '宮廷牌與大牌常被讀成某個人，也可能是你自己的某種態度。年紀與外貌的慣例出自偉特 1911 年挑選「指示者」的規則，現代多不拘泥。',
    'card.pace.title': '節奏與時機',
    'card.pace.note': '只談事情的快慢與走勢，不換算成日期；為什麼不推算日期，見讀牌指南的〈問時間要格外小心〉。',
    'card.combos.title': '常見組合',
    'card.combos.lead': '和這些牌一起出現時：',
    'care.title': '需要有人陪你談談嗎',
    'care.text': '牌面碰到的難受如果已經壓得你喘不過氣，比起再抽一次牌，更值得先找人說說。台灣可以撥打的專線：',
    'care.1925': '衛福部安心專線 1925（二十四小時、免付費）',
    'care.1995': '生命線 1995（二十四小時）',
    'care.1980': '張老師專線 1980（依服務時段）',
    'care.113': '保護專線 113（二十四小時；家庭暴力、性侵害、兒少與老人保護）',
    'care.emergency': '有立即的危險，請撥 110 或 119。',
    'card.positions.advice': '建議',
    'card.positions.obstacle': '阻礙',
    'card.positions.outcome': '結果',
    'card.journal.label': '書寫提問',
    'refs.related.title': '相關的牌',
    'refs.kind.similar': '相似',
    'refs.kind.contrast': '對照',
    'refs.kind.sequence': '延續',
    'refs.kind.pair': '呼應',
    'refs.names.title': '其他牌系的名稱',
    'refs.names.marseille': '馬賽牌',
    'refs.names.thoth': '托特牌',
    'refs.names.italian': '義大利古名',
    'refs.names.aliases': '中文常見別名',
    'refs.names.thothNumbered': '{name}（{n}）',
    'refs.names.thothAlt': '另一種對法：{name}',
    'refs.names.help': '說明',
    'refs.timing.label': '對應日期',
    'refs.timing.range': '約 {from}–{to}（{what}）',
    'refs.timing.date': '{m} 月 {d} 日',
    'refs.timing.febEnd': '2 月底',
    'refs.timing.decan': '{planet}在{sign}的旬',
    'refs.symbols.title': '畫面上的符號',
    'refs.symbols.rwsOnly': '（僅原版牌圖）',
    'refs.symbols.lineOnly': '（僅線稿牌組）',
    'compare.open': '比較',
    'compare.open.label': '拿{name}和另一張牌比較',
    'compare.title': '比較兩張牌',
    'compare.filter.label': '搜尋第二張牌',
    'compare.filter.placeholder': '輸入牌名、英文名或別名…',
    'compare.filter.count': '{n} 張牌符合',
    'compare.pick.label': '第二張牌',
    'compare.pick.none': '請選擇',
    'compare.empty': '選好第二張牌，兩張的重點會並排列出。',
    'compare.row.keywords': '關鍵詞',
    'compare.row.yesno': '是非傾向',
    'compare.row.attr': '元素與對應',
    'compare.row.names': '其他牌系的名稱',
    'compare.row.timing': '對應日期',
    'compare.row.symbols': '共同的符號',
    'compare.row.related': '兩張牌的關係',
    'compare.none': '無',
    'compare.symbols.none': '沒有共同的符號',
    'compare.related.none': '兩張牌沒有被列為相關的牌。',
    'compare.related.dir': '從{from}看：',
    'compare.loadFailed': '部分資料需要網路才能載入。',
    'card.context.yesno': '是非',
    'card.reflection.label': '反思',
    'card.lore.empty': '這張牌的源流資料尚未收錄。',
    'card.origin.title': '這張牌的源流',
    'card.lore.more': '延伸閱讀',
    'card.lore.more.note': '同類牌共用的背景收在資料庫的知識庫；點選會關閉卡片詳情，前往那一段。',
    'card.lore.related': '同樣的符號也出現在',
    'card.sources.lead': '以上各組語詞的出處與差異：',
    'card.sources.link': '來源說明',
    'error.chunkOffline': '需要網路，請重新整理',
    'about.title': '關於本站',
    'about.intro': '以偉特塔羅（Rider–Waite–Smith，1909）為本的占卜與學習工具。牌義綜合偉特《圖像塔羅之鑰》（1911）與現代主流讀法。卡片詳情另外並列「偉特 1911 原文語詞」「偉特 1911 補充牌義」「mofatarot 關鍵詞」，以及黃金黎明與 Thierens（1930）兩套對應系統，各自分開列出、不合併成一套；它們的出處與差異寫在資料庫的知識庫裡。牌圖模式用的是 1909 年版的原始牌圖，屬公有領域，隨網站提供、不連外。占卜結果僅供參考，不能取代醫療、法律或財務等專業意見。',
    'about.changelog.empty': '尚無更新紀錄。',
    'privacy.title': '隱私政策',
    'privacy.noCollect': '不收集任何個人資料，也不需要帳號',
    'privacy.noTracking': '不使用任何分析或追蹤工具',
    'privacy.localOnly': '占卜記錄、筆記、生日與學習進度只存在這台裝置的瀏覽器裡；清除網站資料會一併刪除，需要時請先在設定裡匯出備份',
    'privacy.shareLink': '分享連結裡的問題放在網址 # 後面：瀏覽器開啟連結時只在本機讀取，不會傳到網站的伺服器；不過收到連結的人看得到你的問題',
    'insight.panel.title': '綜合觀察',
    'insight.panel.note': '標題後的百分比，是「完全隨機抽牌時，出現這種或更極端情況」的機率（有些項目要同時比較多種可能，列的是校正後的上限），低於 5% 才會列出；後面附的是常見的塔羅讀法，僅供參考。抽牌本來就是隨機的，同時檢查這麼多項，總會有某一項碰巧偏低：牌多的牌陣，純隨機時也有約兩成會出現一條這樣的觀察。數字只說明它少見，要不要當成線索由你決定。',
    'insight.prob.is': '是 {p}',
    'insight.prob.atMost': '不超過 {p}',
    'insight.prob.below': '低於 0.1%',
    'insight.major.tag': '大阿卡納密集 · {p}',
    'insight.major.text': '{n} 張牌裡有 {k} 張大阿卡納：{cards}。這副 {N} 張的牌組有 {K} 張大阿卡納，平均只會抽到 {exp} 張；抽到這麼多或更多的機率{prob}。',
    'insight.suit.tag': '{suit}主導 · {p}',
    'insight.suit.text': '{n} 張牌裡有 {k} 張{suit}：{cards}。純隨機抽到這麼集中的機率{prob}（已按四個花色校正）。',
    'insight.reversed.tag': '逆位偏多 · {p}',
    'insight.reversed.text': '{n} 張裡有 {k} 張逆位。每張牌正逆位的機會各半，逆位這麼多或更多的機率{prob}。',
    'insight.upright.tag': '正位偏多 · {p}',
    'insight.upright.text': '{n} 張裡有 {k} 張正位。每張牌正逆位的機會各半，正位這麼多或更多的機率{prob}。',
    'insight.hint.major': '大阿卡納多，傳統上表示牽涉的是人生層次的課題或轉折，不只是日常瑣事；讀的時候先看大阿卡納定下的方向，再用小阿卡納補細節。',
    'insight.hint.suit': '{suit}屬{element}元素，管的是{faculty}：問題多半落在這個領域。',
    'insight.hint.reversed': '逆位多，常見的讀法是事情受阻、延遲，或能量轉向內在、還沒表現出來；先找出卡住的地方，不必當成凶兆。',
    'insight.hint.upright': '正位多，表示牌的能量大多順暢、直接地表現出來，事情比較照牌面的意思發展。',
    'insight.hint.court': '宮廷牌多，表示「人」是重點：可能是牽涉其中的人，也可能是你正在扮演的角色或該採取的態度。',
    'insight.hint.pip': '數字牌多，表示事情多半落在日常、具體的層次，靠實際的步驟就能推動。',
    'insight.recur.tag': '{n} 張{ori}{rank}',
    'insight.recur.text': '這次有 {n} 張{ori}的{rank}：{cards}。偉特《圖像塔羅之鑰》（1911）第三部第五節列出同一點數或階級重複出現時的意義，這個組合是「{term}」。這是 1911 年的算命語彙，今天多半當作歷史參照。',
    'insight.recur.text.both': '這次有 {n} 張{ori}的{rank}：{cards}。偉特《圖像塔羅之鑰》（1911）第三部第五節的讀法是「{term}」；Foli《Fortune-Telling by Cards》（1915）第四章的讀法是「{foli}」——Foli 的規則原本是給一般撲克牌用的，兩者可以對照著看；這兩組都是一百多年前的算命語彙，今天多半當作歷史參照。',
    'rank.label.ace': '一號牌',
    'rank.label.two': '二號牌',
    'rank.label.three': '三號牌',
    'rank.label.four': '四號牌',
    'rank.label.five': '五號牌',
    'rank.label.six': '六號牌',
    'rank.label.seven': '七號牌',
    'rank.label.eight': '八號牌',
    'rank.label.nine': '九號牌',
    'rank.label.ten': '十號牌',
    'rank.label.page': '侍者',
    'rank.label.knight': '騎士',
    'rank.label.queen': '皇后',
    'rank.label.king': '國王',
    'waite.recur.natural.king.4': '大榮譽',
    'waite.recur.natural.king.3': '商議',
    'waite.recur.natural.king.2': '小忠告',
    'waite.recur.natural.queen.4': '大爭論',
    'waite.recur.natural.queen.3': '受女性欺瞞',
    'waite.recur.natural.queen.2': '真誠的朋友',
    'waite.recur.natural.knight.4': '嚴肅的事',
    'waite.recur.natural.knight.3': '熱烈的辯論',
    'waite.recur.natural.knight.2': '親密',
    'waite.recur.natural.page.4': '危險的疾病',
    'waite.recur.natural.page.3': '爭執',
    'waite.recur.natural.page.2': '不安',
    'waite.recur.natural.ten.4': '定罪',
    'waite.recur.natural.ten.3': '新的處境',
    'waite.recur.natural.ten.2': '改變',
    'waite.recur.natural.nine.4': '一位好朋友',
    'waite.recur.natural.nine.3': '成功',
    'waite.recur.natural.nine.2': '收受',
    'waite.recur.natural.eight.4': '挫折',
    'waite.recur.natural.eight.3': '婚姻',
    'waite.recur.natural.eight.2': '新的知識',
    'waite.recur.natural.seven.4': '密謀',
    'waite.recur.natural.seven.3': '體弱',
    'waite.recur.natural.seven.2': '消息',
    'waite.recur.natural.six.4': '豐盛',
    'waite.recur.natural.six.3': '成功',
    'waite.recur.natural.six.2': '易怒',
    'waite.recur.natural.five.4': '規律',
    'waite.recur.natural.five.3': '決心',
    'waite.recur.natural.five.2': '守夜',
    'waite.recur.natural.four.4': '近在眼前的旅程',
    'waite.recur.natural.four.3': '一個值得反覆思索的主題',
    'waite.recur.natural.four.2': '失眠',
    'waite.recur.natural.three.4': '進展',
    'waite.recur.natural.three.3': '合一',
    'waite.recur.natural.three.2': '平靜',
    'waite.recur.natural.two.4': '爭端',
    'waite.recur.natural.two.3': '安全',
    'waite.recur.natural.two.2': '和諧一致',
    'waite.recur.natural.ace.4': '有利的機緣',
    'waite.recur.natural.ace.3': '小小的成功',
    'waite.recur.natural.ace.2': '詭計',
    'waite.recur.reversed.king.4': '迅捷',
    'waite.recur.reversed.king.3': '商務往來',
    'waite.recur.reversed.king.2': '計畫',
    'waite.recur.reversed.queen.4': '壞的同伴',
    'waite.recur.reversed.queen.3': '暴食',
    'waite.recur.reversed.queen.2': '工作',
    'waite.recur.reversed.knight.4': '結盟',
    'waite.recur.reversed.knight.3': '一場決鬥，或當面的衝突',
    'waite.recur.reversed.knight.2': '易受影響',
    'waite.recur.reversed.page.4': '匱乏',
    'waite.recur.reversed.page.3': '怠惰',
    'waite.recur.reversed.page.2': '交際',
    'waite.recur.reversed.ten.4': '事件發生',
    'waite.recur.reversed.ten.3': '失望',
    'waite.recur.reversed.ten.2': '期待得到印證',
    'waite.recur.reversed.nine.4': '放高利貸',
    'waite.recur.reversed.nine.3': '輕率',
    'waite.recur.reversed.nine.2': '小額獲利',
    'waite.recur.reversed.eight.4': '錯誤',
    'waite.recur.reversed.eight.3': '一場熱鬧的場面',
    'waite.recur.reversed.eight.2': '不幸',
    'waite.recur.reversed.seven.4': '好爭吵的人',
    'waite.recur.reversed.seven.3': '喜悅',
    'waite.recur.reversed.seven.2': '名聲不佳的女子',
    'waite.recur.reversed.six.4': '掛慮',
    'waite.recur.reversed.six.3': '滿足',
    'waite.recur.reversed.six.2': '垮台',
    'waite.recur.reversed.five.4': '秩序',
    'waite.recur.reversed.five.3': '猶豫',
    'waite.recur.reversed.five.2': '挫折',
    'waite.recur.reversed.four.4': '外出走動',
    'waite.recur.reversed.four.3': '不安',
    'waite.recur.reversed.four.2': '爭執',
    'waite.recur.reversed.three.4': '大成功',
    'waite.recur.reversed.three.3': '寧靜',
    'waite.recur.reversed.three.2': '安全無虞',
    'waite.recur.reversed.two.4': '和解',
    'waite.recur.reversed.two.3': '憂懼',
    'waite.recur.reversed.two.2': '不信任',
    'waite.recur.reversed.ace.4': '不名譽',
    'waite.recur.reversed.ace.3': '放蕩',
    'waite.recur.reversed.ace.2': '敵人',
    'foli.recur.natural.ace.4': '危險、破財、與朋友離散、感情上的麻煩，某些情況下還有牢獄之災',
    'foli.recur.natural.ace.3': '一時的麻煩，由好消息化解',
    'foli.recur.natural.king.4': '榮銜、擢升、好職位',
    'foli.recur.natural.king.2': '生意上的合作',
    'foli.recur.natural.queen.3': '友善的造訪',
    'foli.recur.reversed.queen.3': '醜聞、流言',
    'foli.recur.natural.queen.2': '交換瑣碎的私語、祕密被洩露、朋友間的會面',
    'foli.recur.natural.ten.4': '好運、財富',
    'foli.recur.natural.ten.2': '意外的好運',
    'foli.recur.natural.nine.4': '意外之事成真',
    'foli.recur.natural.nine.3': '健康、財富、幸福',
    'foli.recur.natural.nine.2': '興旺與滿足、遺囑文件',
    'foli.recur.reversed.nine.2': '小煩惱',
    'foli.recur.reversed.eight.4': '不受擾動的安定',
    'foli.recur.natural.eight.3': '新的家庭關係、有意成婚的正當心意',
    'foli.recur.reversed.eight.3': '調情、放蕩與愚行',
    'foli.recur.natural.eight.2': '輕浮的享樂、一時的戀慕、意料之外的發展',
    'foli.recur.natural.seven.4': '算計與圈套、爭執與對立',
    'foli.recur.natural.seven.3': '健康不佳、悔恨',
    'foli.recur.natural.seven.2': '兩情相悅、一件意外的事',
    'foli.recur.reversed.seven.2': '不忠、欺瞞或悔恨',
    'insight.class.court.tag': '宮廷牌密集 · {p}',
    'insight.class.court.text': '{n} 張牌裡有 {k} 張宮廷牌：{cards}。這副 {N} 張的牌組有 {K} 張宮廷牌，平均只會抽到 {exp} 張；抽到這麼多或更多的機率{prob}。',
    'insight.class.pip.tag': '數字牌密集 · {p}',
    'insight.class.pip.text': '{n} 張牌裡有 {k} 張數字牌。這副 {N} 張的牌組有 {K} 張數字牌，平均會抽到 {exp} 張；抽到這麼多或更多的機率{prob}。',
    'insight.quality.tag': '{quality}星座 · {p}',
    'insight.quality.text': '你抽到的大阿卡納裡，有 {k} 張在 Thierens（《General Book of the Tarot》，1930）的系統裡對應到星座，而且全是{quality}星座。他的十二張星座牌每種性質各 4 張，隨機抽到的星座牌全屬同一種性質（不限哪一種）的機率{prob}。{qdesc}這是 Thierens 自己的對應，與本站採用的黃金黎明系統不同，只當作另一個角度。',
    'quality.cardinal': '開創',
    'quality.fixed': '固定',
    'quality.mutable': '變動',
    'quality.cardinal.desc': '開創星座主導起頭與開拓：事情多半處在要你主動開始的階段。',
    'quality.fixed.desc': '固定星座主導維持與堅持：事情往往需要耐力，也可能卡在不肯改變。',
    'quality.mutable.desc': '變動星座主導調整與轉換：事情多半正在變化，彈性比堅持更重要。',
    'mofa.terms.title': 'mofatarot 關鍵詞',
    'waite.terms.title': '偉特 1911 原文語詞',
    'waite.terms.upright': '正位',
    'waite.terms.reversed': '逆位',
    'waite.additional.title': '偉特 1911 補充牌義',
    'court.looks.title': '這張牌常指向的人',
    'court.looks.wands': '髮色金黃或赤褐、膚色白皙、藍眼',
    'court.looks.cups': '髮色淺褐或暗金、灰眼或藍眼',
    'court.looks.swords': '髮色深褐、榛色或灰眼、膚色偏暗',
    'court.looks.pentacles': '髮色深褐或黑、深色眼睛、膚色偏黃或黝黑',
    'court.looks.note': '偉特挑選「指示者」時用的外貌對照；現代讀法多看性情與角色。',
    'suit.faculty.wands': '行動、熱情、意志',
    'suit.faculty.cups': '情感、關係、直覺',
    'suit.faculty.swords': '思考、溝通、判斷',
    'suit.faculty.pentacles': '金錢、工作、身體',
    'systems.title': '對應系統',
    'systems.std.source': '標準系統（本站預設）',
    'systems.std.note': '元素、稱號、旬位與質點出自黃金黎明一系（《T 之書》、《777》）；面向是本站的概括，撲克花色是通行的對照。',
    'systems.guide.lead': '各欄的意思：',
    'systems.guide.link': '對應系統怎麼讀',
    'systems.std.note.court': '黃金黎明替宮廷牌另配的位階元素與旬位，這裡不採用，只列花色本身的對應。',
    'systems.std.note.major': '黃金黎明的大阿卡納對應（《T 之書》、《777》）；字母的中文名只是音譯。',
    'systems.thierens.source': 'Thierens 1930',
    'systems.thierens.note': '宮位與星座是 Thierens 自己的排法，和標準系統的旬位無關。',
    'systems.thierens.note.major': 'Thierens 自己的大阿卡納星象對應，沿用正義 VIII、力量 XI 的舊序，從魔術師的牡羊座依序排下。',
    'systems.thierens.note.clash': 'Thierens 給這個花色配的元素和標準系統不同；本站牌義依標準系統。',
    'systems.label.element': '元素',
    'systems.label.faculty': '面向',
    'systems.label.french': '撲克花色',
    'systems.label.planet': '行星',
    'systems.label.sign': '星座',
    'systems.label.house': '宮位',
    'systems.label.quality': '性質',
    'systems.label.triplicity': '星座元素',
    'systems.label.letter': '字母',
    'systems.label.tree': '生命之樹',
    'systems.label.decan': '旬位',
    'systems.label.gdTitle': '稱號',
    'systems.house': '第 {n} 宮',
    'systems.letter': '{letter} {name}（{zh}）',
    'systems.path': '第 {n} 條路徑',
    'systems.decan': '{planet}在{sign}',
    'systems.attr.fireSpirit': '火（也對應靈）',
    'systems.attr.saturnEarth': '土星（也對應土元素）',
    'systems.sephira.1': '第一質點・王冠（Kether）：原動天',
    'systems.sephira.2': '第二質點・智慧（Chokmah）：黃道帶',
    'systems.sephira.3': '第三質點・理解（Binah）：土星',
    'systems.sephira.4': '第四質點・仁慈（Chesed）：木星',
    'systems.sephira.5': '第五質點・嚴厲（Geburah）：火星',
    'systems.sephira.6': '第六質點・美（Tiphareth）：太陽',
    'systems.sephira.7': '第七質點・勝利（Netzach）：金星',
    'systems.sephira.8': '第八質點・榮耀（Hod）：水星',
    'systems.sephira.9': '第九質點・根基（Yesod）：月亮',
    'systems.sephira.10': '第十質點・王國（Malkuth）：地球（四元素）',
    'systems.gdTitle.ace_of_wands': '火之力量的根源（Root of the Powers of Fire）',
    'systems.gdTitle.two_of_wands': '統治之主（Lord of Dominion）',
    'systems.gdTitle.three_of_wands': '穩固力量之主（Lord of Established Strength）',
    'systems.gdTitle.four_of_wands': '圓滿工作之主（Lord of Perfected Work）',
    'systems.gdTitle.five_of_wands': '爭鬥之主（Lord of Strife）',
    'systems.gdTitle.six_of_wands': '勝利之主（Lord of Victory）',
    'systems.gdTitle.seven_of_wands': '勇氣之主（Lord of Valour）',
    'systems.gdTitle.eight_of_wands': '迅捷之主（Lord of Swiftness）',
    'systems.gdTitle.nine_of_wands': '強大力量之主（Lord of Great Strength）',
    'systems.gdTitle.ten_of_wands': '壓迫之主（Lord of Oppression）',
    'systems.gdTitle.ace_of_cups': '水之力量的根源（Root of the Powers of Water）',
    'systems.gdTitle.two_of_cups': '愛之主（Lord of Love）',
    'systems.gdTitle.three_of_cups': '豐盛之主（Lord of Abundance）',
    'systems.gdTitle.four_of_cups': '混雜歡愉之主（Lord of Blended Pleasure）',
    'systems.gdTitle.five_of_cups': '歡愉中的失落之主（Lord of Loss in Pleasure）',
    'systems.gdTitle.six_of_cups': '歡愉之主（Lord of Pleasure）',
    'systems.gdTitle.seven_of_cups': '虛幻成功之主（Lord of Illusionary Success）',
    'systems.gdTitle.eight_of_cups': '放棄成功之主（Lord of Abandoned Success）',
    'systems.gdTitle.nine_of_cups': '物質幸福之主（Lord of Material Happiness）',
    'systems.gdTitle.ten_of_cups': '圓滿成功之主（Lord of Perfected Success）',
    'systems.gdTitle.ace_of_swords': '風之力量的根源（Root of the Powers of Air）',
    'systems.gdTitle.two_of_swords': '恢復和平之主（Lord of Peace Restored）',
    'systems.gdTitle.three_of_swords': '悲傷之主（Lord of Sorrow）',
    'systems.gdTitle.four_of_swords': '爭鬥後的休憩之主（Lord of Rest from Strife）',
    'systems.gdTitle.five_of_swords': '挫敗之主（Lord of Defeat）',
    'systems.gdTitle.six_of_swords': '應得成功之主（Lord of Earned Success）',
    'systems.gdTitle.seven_of_swords': '不穩努力之主（Lord of Unstable Effort）',
    'systems.gdTitle.eight_of_swords': '力量縮減之主（Lord of Shortened Force）',
    'systems.gdTitle.nine_of_swords': '絕望與殘酷之主（Lord of Despair and Cruelty）',
    'systems.gdTitle.ten_of_swords': '毀滅之主（Lord of Ruin）',
    'systems.gdTitle.ace_of_pentacles': '土之力量的根源（Root of the Powers of Earth）',
    'systems.gdTitle.two_of_pentacles': '和諧變化之主（Lord of Harmonious Change）',
    'systems.gdTitle.three_of_pentacles': '物質工作之主（Lord of Material Works）',
    'systems.gdTitle.four_of_pentacles': '塵世權力之主（Lord of Earthly Power）',
    'systems.gdTitle.five_of_pentacles': '物質困境之主（Lord of Material Trouble）',
    'systems.gdTitle.six_of_pentacles': '物質成功之主（Lord of Material Success）',
    'systems.gdTitle.seven_of_pentacles': '未竟成功之主（Lord of Success Unfulfilled）',
    'systems.gdTitle.eight_of_pentacles': '審慎之主（Lord of Prudence）',
    'systems.gdTitle.nine_of_pentacles': '物質收穫之主（Lord of Material Gain）',
    'systems.gdTitle.ten_of_pentacles': '財富之主（Lord of Wealth）',
    'element.fire': '火',
    'element.water': '水',
    'element.air': '風',
    'element.earth': '土',
    'french.clubs': '梅花',
    'french.hearts': '紅心',
    'french.spades': '黑桃',
    'french.diamonds': '方塊',
    'planet.saturn': '土星',
    'planet.jupiter': '木星',
    'planet.mars': '火星',
    'planet.sun': '太陽',
    'planet.venus': '金星',
    'planet.mercury': '水星',
    'planet.moon': '月亮',
    'planet.earth': '地球',
    'planet.uranus': '天王星',
    'planet.neptune': '海王星',
    'sign.aries': '牡羊座',
    'sign.taurus': '金牛座',
    'sign.gemini': '雙子座',
    'sign.cancer': '巨蟹座',
    'sign.leo': '獅子座',
    'sign.virgo': '處女座',
    'sign.libra': '天秤座',
    'sign.scorpio': '天蠍座',
    'sign.sagittarius': '射手座',
    'sign.capricorn': '摩羯座',
    'sign.aquarius': '水瓶座',
    'sign.pisces': '雙魚座',
    'insight.echo.tag': '共同語詞 · {term}',
    'insight.echo.text': '{cards}都帶著「{term}」這個語詞；整副 {N} 張牌裡只有 {K} 張有它。（出處：{src}）',
    'insight.echo.text.multi': '{cards}都帶著這些語詞：{term}。其中最少見的是「{best}」，整副 {N} 張牌裡只有 {K} 張有它。（出處：{src}）',
    'insight.echo.text.multiSrc': '{cards}在 {m} 個來源裡都有相同的語詞：{parts}。',
    'insight.echo.part': '「{terms}」（{src}）',
    'insight.echo.net.tag': '語詞交會 · {hub}',
    'insight.echo.net.text': '{hub}和其他幾張牌都有共同的語詞：{links}。它是這次牌面的交會點，可以從它讀起。',
    'insight.echo.net.link': '與{others}共享{parts}',
    'insight.echo.net.extra': '{cards}另外共享{parts}',
    'insight.card.pos': '{name}（{ori}・{pos}）',
    'insight.card.bottom': '底牌{name}（{ori}）',
    'insight.profile.tag': '牌面剖面',
    'insight.profile.text': '{n} 張牌：大阿卡納 {maj}、宮廷牌 {court}、數字牌 {pip}，逆位 {rev} 張；小阿卡納的元素：{els}。',
    'insight.profile.text.noMinors': '{n} 張牌全是大阿卡納，逆位 {rev} 張。',
    'insight.profile.el': '{el} {k}',
    'insight.axis.tag': '{p1}×{p2}',
    'insight.axis.rank.text': '「{p1}」與「{p2}」抽到同一個數字或階級：{c1}、{c2}都是{rank}。這兩個位置本來就該對照著讀；數字或階級相同，表示兩端處在同一個發展階段，差別在花色，也就是落在不同的領域。',
    'insight.axis.suit.tag': '時間線同花色',
    'insight.axis.suit.text': '時間軸上的三張牌（過去、現在、未來）都是{suit}：{cards}。事情一路沒有離開這個領域，變的是走到哪個階段，可以比較三張牌的點數或階級來看。',
    'insight.axis.suit.merge': '而且過去、現在、未來三個位置都是{suit}：事情一路沒有離開這個領域，可以比較這三張的點數或階級，看它走到哪個階段。',
    'insight.axis.suit.merge.exact': '這三張正好佔滿過去、現在、未來：事情一路沒有離開這個領域，可以比較它們的點數或階級，看它走到哪個階段。',
    'insight.echo.card': '{name}（{ori}）',
    'insight.echo.pair': '{zh}（{en}）',
    'insight.echo.src.ours': '本站正逆位關鍵詞',
    'insight.echo.src.mofa': 'mofatarot 正逆位關鍵詞',
    'insight.echo.src.waite': '偉特 1911 原文語詞',
    'insight.echo.src.add': '偉特 1911 補充牌義',
    'insight.balanced.tag': '無顯著偏向',
    'insight.balanced.text': '花色、大阿卡納、宮廷牌與數字牌的比例、正逆位、同點數或階級的重複、共同語詞與位置對照都檢查過了，這次的牌面沒有特別的集中或重複，直接看每張牌在各自位置上的意思即可。',
    'insight.balanced.small': '（只有 {n} 張牌時，本來就很少出現明顯的集中。）',
    'insight.bottom.tag': '底牌基調',
    'insight.bottom.text': '底牌{name}（{ori}）不單獨論吉凶：讀完各張牌後，回頭想想它代表的{kw}，是不是一直在這件事底下起作用。',
    'insight.bottom.text.noKeywords': '底牌{name}（{ori}）不單獨論吉凶：讀完各張牌後，回頭想想它的主題是不是一直在這件事底下起作用。',
    'pattern.panel.title': '模式洞察',
    'pattern.panel.sub': '來自你的 {n} 次占卜',
    'pattern.panel.note': '依你全部的占卜記錄計算，只算牌陣裡抽出的牌，不含底牌。標出的機率是完全隨機時出現這種或更極端分布的機率（同時比較多個花色、標籤或多種牌時是校正後的上限），低於 5% 才列出；後面附的讀法僅供參考。同時比較的項目越多，越容易有某一項碰巧偏低，所以它只說明少見，不代表一定有意義。',
    'pattern.none.tag': '尚未開始',
    'pattern.none.text': '占卜記錄滿 5 次後，這裡會開始分析你長期抽到的牌。',
    'pattern.building.tag': '尚在累積',
    'pattern.building.text': '再占卜 {n} 次，這裡就會開始分析你的長期記錄：哪個花色特別常出現、某個標籤底下的牌有什麼傾向、哪張牌一再出現。',
    'pattern.dominant.tag': '{suit}長期主導',
    'pattern.dominant.text': '你的 {total} 張牌裡有 {k} 張{suit}（{pct}%，平均應是 {exp} 張）。純隨機出現這麼集中的機率{prob}（已按四個花色校正）。',
    'pattern.tag.tag': '標籤「{name}」',
    'pattern.tag.text': '你標記為「{name}」的 {n} 次占卜共 {m} 張牌，其中{suit}佔 {k} 張（{pct}%）。純隨機出現這麼集中的機率{prob}（已按花色與標籤的數量校正）。',
    'pattern.reversed.high.tag': '逆位偏多',
    'pattern.reversed.high.text': '長期 {total} 張牌裡有 {k} 張逆位（{pct}%）。每張牌正逆位的機會各半，逆位這麼多或更多的機率{prob}。',
    'pattern.reversed.low.tag': '逆位偏少',
    'pattern.reversed.low.text': '長期 {total} 張牌裡只有 {k} 張逆位（{pct}%）。每張牌正逆位的機會各半，逆位這麼少或更少的機率{prob}。',
    'pattern.regular.tag': '常客牌',
    'pattern.regular.text': '{name}在你的 {total} 張牌裡出現了 {n} 次。照你用過的牌組隨機發牌，{size} 種牌裡「任何一張」出現到這個次數的機率{prob}。它的關鍵詞：{kw}。這張牌一再出現，它的主題值得你花時間多想一想。',
    'pattern.regular.kw': '{kw}（{ori}）',
    'pattern.regular.text.noKeywords': '{name}在你的 {total} 張牌裡出現了 {n} 次。照你用過的牌組隨機發牌，{size} 種牌裡「任何一張」出現到這個次數的機率{prob}。這張牌一再出現，它的主題值得你花時間多想一想。',
    'pattern.major.high.tag': '大阿卡納偏多',
    'pattern.major.high.text': '你的 {total} 張牌裡有 {k} 張大阿卡納（{pct}%，平均應是 {exp} 張）。純隨機出現這麼多或更多的機率{prob}。',
    'pattern.major.low.tag': '大阿卡納偏少',
    'pattern.major.low.text': '你的 {total} 張牌裡只有 {k} 張大阿卡納（{pct}%，平均應是 {exp} 張）。純隨機出現這麼少或更少的機率{prob}。大阿卡納少，表示你問的事多半落在日常層次，主要靠你自己的具體選擇推動。',
    'pattern.pace.tag': '節奏變快',
    'pattern.pace.text': '最近 30 天你占卜了 {n} 次，前一個 30 天是 {prev} 次。如果是在反覆追問同一件事，不妨先停一停，回頭讀上一次的牌：短時間內為同一個問題重抽，答案往往彼此矛盾，反而更難判斷。',
    'pattern.flat.tag': '無顯著偏向',
    'pattern.flat.text': '花色、大阿卡納比例、正逆位、常客牌與標籤交叉都檢查過了，你的長期分布都在隨機範圍內，沒有特別的集中。',
    'btn.startReading': '開始占卜',
    'btn.share': '分享',
    'btn.copyResults': '複製結果',
    'btn.shareImage': '生成分享圖',
    'btn.print': '列印',
    'btn.note': '筆記',
    'btn.tag': '標籤',
    'btn.delete': '刪除',
    'btn.cancel': '取消',
    'btn.save': '儲存',
    'btn.add': '儲存',
    'btn.confirm': '確定',
    'btn.close': '關閉',
    'btn.reload': '重新整理',
    'note.title': '編輯筆記',
    'note.placeholder': '寫下你的感受與想法…',
    'tag.title': '編輯標籤',
    'tag.common': '常用標籤',
    'tag.custom': '自訂標籤',
    'tag.placeholder': '輸入標籤名稱…',
    'confirm.clearAll.title': '清除所有資料',
    'confirm.clearAll.message': '將刪除這台裝置上的全部占卜記錄、筆記、偏好設定、生日與學習進度，且無法復原。建議先匯出備份。',
    'confirm.clearAll.ok': '全部清除',
    'confirm.import.title': '匯入記錄',
    'confirm.import.message': '將匯入 {n} 筆記錄，取代目前的 {current} 筆記錄。',
    'confirm.import.messageEmpty': '將匯入 {n} 筆記錄。',
    'confirm.import.extras': '檔案裡的偏好設定、學習進度與生日，也會取代這台裝置上現有的資料。',
    'confirm.import.ok': '匯入',
    'confirm.delete.title': '刪除記錄',
    'confirm.delete.message': '確定要刪除此占卜記錄嗎？',
    'confirm.delete.ok': '刪除',
    'confirm.clearHistory.title': '清除所有記錄',
    'confirm.clearHistory.message': '將刪除全部 {n} 筆占卜記錄，包含筆記與標籤。此動作無法復原。',
    'confirm.clearHistory.ok': '全部刪除',
    'confirm.learnReset.title': '重設學習進度',
    'confirm.learnReset.message': '熟練度與連續天數都會歸零，且無法復原。',
    'confirm.learnReset.ok': '重設',
    'toast.deckTooSmall': '牌組數量不足',
    'toast.copied': '已複製到剪貼簿',
    'toast.copyFailed': '複製失敗',
    'toast.linkCopied': '連結已複製',
    'toast.noReading': '請先進行占卜',
    'toast.shareImageDone': '分享圖已下載',
    'toast.shareImageFailed': '分享圖生成失敗',
    'toast.visualStyle': '已切換至{name}',
    'toast.favorited': '已加入收藏',
    'toast.unfavorited': '已取消收藏',
    'toast.deleted': '已刪除記錄',
    'toast.historyCleared': '已清除所有記錄',
    'toast.noteSaved': '筆記已儲存',
    'toast.tagUpdated': '標籤已更新',
    'toast.exported': '資料已匯出',
    'toast.imported': '已匯入 {n} 筆記錄',
    'toast.imported.withPrefs': '已匯入 {n} 筆記錄，以及 {prefs} 項設定與學習資料',
    'toast.importBadFormat': '檔案格式錯誤',
    'toast.importParseFailed': '檔案解析失敗',
    'toast.importEmpty': '檔案裡沒有可用的占卜記錄，已取消匯入',
    'toast.historyTrimmed': '記錄超過 {max} 筆，已移除最舊的 {n} 筆（優先保留收藏與有筆記的）',
    'toast.historyEmpty': '目前沒有可清除的記錄',
    'toast.storageFull': '無法寫入瀏覽器的儲存空間（可能已滿或網站資料被封鎖），這次的變更不會保留',
    'toast.badShareLink': '分享連結的參數有誤，已略過無法使用的部分',
    'toast.updateAvailable': '新版本可用',
    'toast.deckLoadFailed': '線稿牌組載入失敗，已改回原本的樣式',
    'toast.imagesOffline': '目前離線，沒看過的牌圖要連上網路才能顯示',
    'toast.learnReset': '學習進度已重設',
    'toast.birthdayInvalid': '生日格式不正確',
    'toast.birthdayFuture': '生日不能是未來的日期',
    'toast.birthdayCleared': '已清除生日',
    'toast.profileUpdated': '已更新你的個人牌'
  }
};
