export const uiStrings = {
  zh: {
    'app.title': '塔羅占卜',
    'app.name': '塔羅',
    'app.themeToggle.toDark': '切換至深色主題',
    'app.themeToggle.toLight': '切換至淺色主題',
    'app.themeToggle.title': '切換主題 (T)',
    'app.langSwitch.label': '切換語言：{lang}',
    'app.skipToMain': '跳到主要內容',
    'app.hero.title': '探索內心的指引',
    'app.hero.subtitle': '簡潔直覺的占卜體驗，專注於當下的洞察',
    'app.share.text': '查看我的占卜結果',
    'app.share.imageFooter': '僅供參考 · 塔羅占卜工具',
    'footer.about.title': '關於',
    'footer.about.desc': '純粹的占卜工具，專注於呈現牌卡結果。所有資料僅存於您的裝置，完全私密。',
    'footer.info.title': '資訊',
    'footer.link.about': '關於本站',
    'footer.link.privacy': '隱私政策',
    'footer.copyright': '塔羅占卜工具 · 僅供參考使用',
    'tab.reading': '占卜',
    'tab.history': '記錄',
    'tab.statistics': '統計',
    'tab.database': '資料庫',
    'tab.learn': '學習',
    'tab.settings': '設定',
    'reading.daily.label': '每日一牌',
    'reading.daily.title': '每日一牌 · {m}月{d}日',
    'reading.question.label': '你的問題',
    'reading.question.placeholder': '例如：目前最需要專注的方向？',
    'reading.deck.label': '牌組',
    'reading.spread.label': '牌陣',
    'reading.spreadInfo.title': '關於此牌陣',
    'reading.spreadInfo.positions': '牌位說明',
    'reading.results.title': '你的占卜',
    'pick.title': '憑直覺選牌',
    'pick.hint': '靜心想著你的問題，選出 <strong>{n}</strong> 張牌',
    'pick.progress': '已選 {n} / {total}',
    'pick.cardBack': '第 {n} 張牌背',
    'pick.random': '隨機快選',
    'pick.reshuffle': '重新洗牌',
    'deck.full': '完整牌組（78 張）',
    'deck.major': '大阿卡納（22 張）',
    'deck.minor': '小阿卡納（56 張）',
    'deck.court': '宮廷牌（16 張）',
    'deck.numbered': '數字牌（40 張）',
    'spread.group.basic': '基礎指引',
    'spread.group.time': '時間運勢',
    'spread.group.love': '感情人際',
    'spread.group.career': '抉擇事業',
    'spread.group.self': '自我探索',
    'spread.group.advanced': '進階經典',
    'spread.bottom': '底牌',
    'spread.unknown': '未知牌陣',
    'spread.picker.title': '選擇牌陣',
    'spread.picker.count': '{n} 張',
    'spread.single.name': '單張牌指引',
    'spread.single.label': '單張牌',
    'spread.single.desc': '最簡單直接的牌陣，適合日常指引或快速問答。',
    'spread.single.pos.0': '核心指引',
    'spread.yesno.name': '是非指引',
    'spread.yesno.label': '是非指引',
    'spread.yesno.desc': '針對是非題的快速牌陣，綜合三張牌的能量與正逆位判斷答案的傾向。',
    'spread.yesno.pos.0': '支持的力量',
    'spread.yesno.pos.1': '阻礙的力量',
    'spread.yesno.pos.2': '結果傾向',
    'spread.three.name': '聖三角',
    'spread.three.label': '聖三角',
    'spread.three.desc': '經典三張牌時間線，呈現事件發展脈絡。',
    'spread.three.pos.0': '過去',
    'spread.three.pos.1': '現在',
    'spread.three.pos.2': '未來',
    'spread.mbs.name': '身心靈牌陣',
    'spread.mbs.label': '身心靈',
    'spread.mbs.desc': '身心靈整體檢視，觀察平衡狀態。',
    'spread.mbs.pos.0': '心態',
    'spread.mbs.pos.1': '身體',
    'spread.mbs.pos.2': '靈性',
    'spread.path.name': '抉擇之路',
    'spread.path.label': '抉擇之路',
    'spread.path.desc': '四步驟路徑牌陣，釐清完整流程。',
    'spread.path.pos.0': '問題',
    'spread.path.pos.1': '挑戰',
    'spread.path.pos.2': '方向',
    'spread.path.pos.3': '結果',
    'spread.weekly.name': '週運勢',
    'spread.weekly.label': '週運勢',
    'spread.weekly.desc': '週運勢，含整週基調與每日提示。',
    'spread.weekly.pos.0': '主題',
    'spread.weekly.pos.1': '週一',
    'spread.weekly.pos.2': '週二',
    'spread.weekly.pos.3': '週三',
    'spread.weekly.pos.4': '週四',
    'spread.weekly.pos.5': '週五',
    'spread.weekly.pos.6': '週六',
    'spread.weekly.pos.7': '週日',
    'spread.monthly.name': '月運勢',
    'spread.monthly.label': '月運勢',
    'spread.monthly.desc': '月運勢，含整月基調與每週能量提示。',
    'spread.monthly.pos.0': '本月主題',
    'spread.monthly.pos.1': '第一週',
    'spread.monthly.pos.2': '第二週',
    'spread.monthly.pos.3': '第三週',
    'spread.monthly.pos.4': '第四週',
    'spread.quarterly.name': '季度展望',
    'spread.quarterly.label': '季度展望',
    'spread.quarterly.desc': '以四季觀察全年能量流動。',
    'spread.quarterly.pos.0': '春季',
    'spread.quarterly.pos.1': '夏季',
    'spread.quarterly.pos.2': '秋季',
    'spread.quarterly.pos.3': '冬季',
    'spread.yearly.name': '年度主題',
    'spread.yearly.label': '年度主題',
    'spread.yearly.desc': '年度主題加各月重點。',
    'spread.yearly.pos.0': '總主題',
    'spread.yearly.pos.1': '一月',
    'spread.yearly.pos.2': '二月',
    'spread.yearly.pos.3': '三月',
    'spread.yearly.pos.4': '四月',
    'spread.yearly.pos.5': '五月',
    'spread.yearly.pos.6': '六月',
    'spread.yearly.pos.7': '七月',
    'spread.yearly.pos.8': '八月',
    'spread.yearly.pos.9': '九月',
    'spread.yearly.pos.10': '十月',
    'spread.yearly.pos.11': '十一月',
    'spread.yearly.pos.12': '十二月',
    'spread.newmoon.name': '新月啟程',
    'spread.newmoon.label': '新月啟程',
    'spread.newmoon.desc': '新月是設定意圖的時刻，此牌陣協助釐清新週期的目標與實現路徑。',
    'spread.newmoon.pos.0': '新月意圖',
    'spread.newmoon.pos.1': '內在資源',
    'spread.newmoon.pos.2': '外在助力',
    'spread.newmoon.pos.3': '需要放下',
    'spread.newmoon.pos.4': '顯化方向',
    'spread.fullmoon.name': '滿月釋放',
    'spread.fullmoon.label': '滿月釋放',
    'spread.fullmoon.desc': '滿月是回顧與釋放的時刻，檢視這個週期的完成、收穫與該放下的事物。',
    'spread.fullmoon.pos.0': '已然圓滿',
    'spread.fullmoon.pos.1': '未竟之事',
    'spread.fullmoon.pos.2': '需要釋放',
    'spread.fullmoon.pos.3': '收穫果實',
    'spread.fullmoon.pos.4': '下一步',
    'spread.relationship.name': '關係牌陣',
    'spread.relationship.label': '關係牌陣',
    'spread.relationship.desc': '關係探索，呈現雙方視角。',
    'spread.relationship.pos.0': '你的觀點',
    'spread.relationship.pos.1': '對方觀點',
    'spread.relationship.pos.2': '現況',
    'spread.relationship.pos.3': '挑戰',
    'spread.relationship.pos.4': '潛力',
    'spread.feelings.name': '對方心意',
    'spread.feelings.label': '對方心意',
    'spread.feelings.desc': '探索對方對你的心意，從表面到內心逐層解讀。',
    'spread.feelings.pos.0': '表面態度',
    'spread.feelings.pos.1': '內心真實感受',
    'spread.feelings.pos.2': '對關係的期待',
    'spread.feelings.pos.3': '猶豫與顧慮',
    'spread.feelings.pos.4': '可能的行動',
    'spread.loveCross.name': '愛情十字',
    'spread.loveCross.label': '愛情十字',
    'spread.loveCross.desc': '愛情十字牌陣，全面檢視一段感情的內外動態與走向。',
    'spread.loveCross.pos.0': '你的狀態',
    'spread.loveCross.pos.1': '對方的狀態',
    'spread.loveCross.pos.2': '關係現況',
    'spread.loveCross.pos.3': '關係的阻礙',
    'spread.loveCross.pos.4': '關係的助力',
    'spread.loveCross.pos.5': '發展方向',
    'spread.conflict.name': '衝突化解',
    'spread.conflict.label': '衝突化解',
    'spread.conflict.desc': '梳理人際衝突的成因與雙方視角，尋找和解的可能。',
    'spread.conflict.pos.0': '衝突的根源',
    'spread.conflict.pos.1': '你的立場',
    'spread.conflict.pos.2': '對方的立場',
    'spread.conflict.pos.3': '彼此的共同點',
    'spread.conflict.pos.4': '化解之道',
    'spread.twoChoice.name': '二擇一',
    'spread.twoChoice.label': '二擇一',
    'spread.twoChoice.desc': '比較兩個選擇的過程與結果。',
    'spread.twoChoice.pos.0': '現況',
    'spread.twoChoice.pos.1': '選項A過程',
    'spread.twoChoice.pos.2': '選項B過程',
    'spread.twoChoice.pos.3': '選項A結果',
    'spread.twoChoice.pos.4': '選項B結果',
    'spread.prosCons.name': '優劣分析',
    'spread.prosCons.label': '優劣分析',
    'spread.prosCons.desc': '優劣分析，客觀呈現正反面。',
    'spread.prosCons.pos.0': '選項A優點',
    'spread.prosCons.pos.1': '選項A缺點',
    'spread.prosCons.pos.2': '選項B優點',
    'spread.prosCons.pos.3': '選項B缺點',
    'spread.prosCons.pos.4': '核心提示',
    'spread.goal.name': '目標達成牌陣',
    'spread.goal.label': '目標達成',
    'spread.goal.desc': '目標達成的五個關鍵面向。',
    'spread.goal.pos.0': '核心',
    'spread.goal.pos.1': '阻礙',
    'spread.goal.pos.2': '資源',
    'spread.goal.pos.3': '步驟',
    'spread.goal.pos.4': '結果',
    'spread.career.name': '職涯發展',
    'spread.career.label': '職涯發展',
    'spread.career.desc': '職涯全面分析，以塔羅視角檢視優劣勢、機會與挑戰。',
    'spread.career.pos.0': '職涯現況',
    'spread.career.pos.1': '你的優勢',
    'spread.career.pos.2': '你的盲點',
    'spread.career.pos.3': '外在機會',
    'spread.career.pos.4': '潛在挑戰',
    'spread.career.pos.5': '發展建議',
    'spread.wealth.name': '財富流動',
    'spread.wealth.label': '財富流動',
    'spread.wealth.desc': '檢視金錢能量的流動，找出開源與節流的方向。',
    'spread.wealth.pos.0': '財務現況',
    'spread.wealth.pos.1': '財富的來源',
    'spread.wealth.pos.2': '金錢的流失',
    'spread.wealth.pos.3': '財務機會',
    'spread.wealth.pos.4': '理財建議',
    'spread.chakra.name': '脈輪牌陣',
    'spread.chakra.label': '脈輪牌陣',
    'spread.chakra.desc': '七脈輪能量檢視。',
    'spread.chakra.pos.0': '海底輪',
    'spread.chakra.pos.1': '臍輪',
    'spread.chakra.pos.2': '太陽神經叢',
    'spread.chakra.pos.3': '心輪',
    'spread.chakra.pos.4': '喉輪',
    'spread.chakra.pos.5': '眉心輪',
    'spread.chakra.pos.6': '頂輪',
    'spread.elements.name': '四元素牌陣',
    'spread.elements.label': '四元素',
    'spread.elements.desc': '五元素平衡狀態。',
    'spread.elements.pos.0': '火',
    'spread.elements.pos.1': '水',
    'spread.elements.pos.2': '風',
    'spread.elements.pos.3': '土',
    'spread.elements.pos.4': '靈',
    'spread.selfDiscovery.name': '自我探索',
    'spread.selfDiscovery.label': '自我探索',
    'spread.selfDiscovery.desc': '向內探索表意識與潛意識的落差，認回被忽略的部分。',
    'spread.selfDiscovery.pos.0': '表意識的你',
    'spread.selfDiscovery.pos.1': '潛意識的你',
    'spread.selfDiscovery.pos.2': '內在的需要',
    'spread.selfDiscovery.pos.3': '被忽略的自己',
    'spread.selfDiscovery.pos.4': '整合之道',
    'spread.shadow.name': '陰影功課',
    'spread.shadow.label': '陰影功課',
    'spread.shadow.desc': '榮格式陰影功課，正視並轉化不願面對的內在面向。',
    'spread.shadow.pos.0': '陰影的面貌',
    'spread.shadow.pos.1': '陰影的成因',
    'spread.shadow.pos.2': '它如何影響你',
    'spread.shadow.pos.3': '接納的鑰匙',
    'spread.shadow.pos.4': '轉化的力量',
    'spread.dream.name': '夢境解析',
    'spread.dream.label': '夢境解析',
    'spread.dream.desc': '解讀夢境背後的潛意識訊息，以及它對現實生活的提醒。',
    'spread.dream.pos.0': '夢境主題',
    'spread.dream.pos.1': '潛意識訊息',
    'spread.dream.pos.2': '與現實的關聯',
    'spread.dream.pos.3': '夢的指引',
    'spread.celtic.name': '凱爾特十字',
    'spread.celtic.label': '凱爾特十字',
    'spread.celtic.desc': '經典凱爾特十字，深入探索。',
    'spread.celtic.pos.0': '核心',
    'spread.celtic.pos.1': '阻礙',
    'spread.celtic.pos.2': '根基',
    'spread.celtic.pos.3': '過去',
    'spread.celtic.pos.4': '目標',
    'spread.celtic.pos.5': '未來',
    'spread.celtic.pos.6': '態度',
    'spread.celtic.pos.7': '環境',
    'spread.celtic.pos.8': '希望與恐懼',
    'spread.celtic.pos.9': '結果',
    'spread.horseshoe.name': '馬蹄鐵牌陣',
    'spread.horseshoe.label': '馬蹄鐵',
    'spread.horseshoe.desc': '經典馬蹄鐵牌陣，七張牌完整鋪陳事件的來龍去脈與對策。',
    'spread.horseshoe.pos.0': '過去',
    'spread.horseshoe.pos.1': '現在',
    'spread.horseshoe.pos.2': '隱藏的影響',
    'spread.horseshoe.pos.3': '眼前的障礙',
    'spread.horseshoe.pos.4': '周遭環境',
    'spread.horseshoe.pos.5': '建議',
    'spread.horseshoe.pos.6': '結果',
    'spread.treeOfLife.name': '生命之樹',
    'spread.treeOfLife.label': '生命之樹',
    'spread.treeOfLife.desc': '卡巴拉生命之樹牌陣，以十個質點檢視生命的完整光譜。',
    'spread.treeOfLife.pos.0': '王冠・靈性核心',
    'spread.treeOfLife.pos.1': '智慧',
    'spread.treeOfLife.pos.2': '理解',
    'spread.treeOfLife.pos.3': '仁慈',
    'spread.treeOfLife.pos.4': '力量',
    'spread.treeOfLife.pos.5': '和諧',
    'spread.treeOfLife.pos.6': '勝利・情感',
    'spread.treeOfLife.pos.7': '宏光・心智',
    'spread.treeOfLife.pos.8': '根基',
    'spread.treeOfLife.pos.9': '王國・顯化',
    'spread.astroHouses.name': '占星十二宮',
    'spread.astroHouses.label': '占星十二宮',
    'spread.astroHouses.desc': '占星十二宮牌陣，鳥瞰生活十二個領域的能量狀態。',
    'spread.astroHouses.pos.0': '第一宮・自我',
    'spread.astroHouses.pos.1': '第二宮・財務',
    'spread.astroHouses.pos.2': '第三宮・溝通',
    'spread.astroHouses.pos.3': '第四宮・家庭',
    'spread.astroHouses.pos.4': '第五宮・創造',
    'spread.astroHouses.pos.5': '第六宮・健康',
    'spread.astroHouses.pos.6': '第七宮・伴侶',
    'spread.astroHouses.pos.7': '第八宮・轉化',
    'spread.astroHouses.pos.8': '第九宮・信念',
    'spread.astroHouses.pos.9': '第十宮・事業',
    'spread.astroHouses.pos.10': '第十一宮・人際',
    'spread.astroHouses.pos.11': '第十二宮・潛意識',
    'suit.major': '大阿卡納',
    'suit.wands': '權杖',
    'suit.cups': '聖杯',
    'suit.swords': '寶劍',
    'suit.pentacles': '錢幣',
    'orientation.upright': '正位',
    'orientation.reversed': '逆位',
    'tendency.yes': '傾向是',
    'tendency.no': '傾向否',
    'tendency.unclear': '不明朗',
    'history.title': '占卜記錄',
    'history.filter.allSpreads': '所有牌陣',
    'history.filter.allTags': '所有標籤',
    'history.filter.favorite': '只看收藏',
    'history.clear': '清除記錄',
    'history.empty': '尚無符合條件的記錄',
    'history.item.favorite': '收藏',
    'history.item.open': '查看結果：{spread}，{time}',
    'stats.title': '統計分析',
    'stats.empty': '尚無統計資料',
    'stats.readings.title': '占卜次數',
    'stats.readings.unit': '次',
    'stats.cards.title': '總抽牌數',
    'stats.cards.unit': '張',
    'stats.uprightPct.title': '正位比例',
    'stats.reversedPct.title': '逆位比例',
    'stats.orientation.unit': '{n} 張',
    'stats.favorites.title': '收藏數量',
    'stats.favorites.unit': '個收藏',
    'stats.avg.title': '平均每次',
    'stats.avg.unit': '張牌',
    'stats.trend.title': '近 12 個月占卜趨勢',
    'stats.trend.bar': '{month}：{n} 次',
    'stats.suits.title': '花色分布',
    'stats.topSpreads.title': '常用牌陣',
    'stats.topCards.title': '常見牌卡',
    'stats.item.count': '{n} 次（{pct}%）',
    'stats.legend.item': '{suit}：{n} 張（{pct}%）',
    'db.title': '牌卡資料庫',
    'db.search.placeholder': '搜尋牌名或英文名...',
    'db.search.label': '搜尋牌卡',
    'history.filter.spreadLabel': '依牌陣篩選',
    'history.filter.tagLabel': '依標籤篩選',
    'note.label': '筆記內容',
    'db.empty': '尚無符合條件的牌卡',
    'learn.title': '學習',
    'learn.mode.flash': '閃卡',
    'learn.mode.quiz': '測驗',
    'learn.scope.label': '學習範圍',
    'learn.scope.all': '全部 78 張',
    'learn.mastery.title': '熟練度',
    'learn.mastery.count': '已掌握 {n} / {total}',
    'learn.mastery.cell': '{name} · 熟練度 {lv}/{max}',
    'learn.reset': '重設學習進度',
    'learn.empty.noMeaning': '此範圍沒有可用的牌義，請換一個範圍。',
    'learn.empty.tooFew': '此範圍牌數不足以出題，請換一個範圍。',
    'learn.streak.days': '🔥 連續 {n} 天',
    'learn.streak.idle': '今天還沒開始',
    'learn.streak.best': '最佳紀錄 {n} 天',
    'learn.streak.none': '完成一次閃卡或測驗即開始計算',
    'learn.streak.continue': '{best} · 今天再學一次就能延續',
    'learn.flash.hint': '點一下看牌義',
    'learn.flash.hard': '還不熟',
    'learn.flash.easy': '記得了',
    'learn.flash.progress': '本輪已看 {n} 張',
    'learn.quiz.progress': '第 {n} / {total} 題',
    'learn.quiz.promptArt': '這張牌的牌義是？',
    'learn.quiz.promptKeywords': '這些關鍵字屬於哪張牌？',
    'learn.quiz.promptCard': '「{name}」的關鍵字是？',
    'learn.quiz.next': '下一題',
    'learn.quiz.toResult': '看結果',
    'learn.quiz.score': '答對 {n} / {total}',
    'learn.quiz.rate': '正確率 {pct}%',
    'learn.quiz.reviewTitle': '再複習這幾張',
    'learn.quiz.perfect': '全部答對，這個範圍你已經很熟了。',
    'learn.quiz.again': '再來一輪',
    'learn.quiz.toFlash': '回到閃卡',
    'settings.title': '設定',
    'settings.theme.title': '外觀主題',
    'settings.theme.auto': '跟隨系統',
    'settings.theme.light': '淺色模式',
    'settings.theme.dark': '深色模式',
    'settings.theme.neon': '霓虹占卜館',
    'settings.theme.neon.desc': '深夜藍黑與霓虹光，墨線牌依花色發光',
    'settings.visual.title': '視覺樣式',
    'settings.visual.text': '純文字模式（預設）',
    'settings.visual.text.desc': '簡潔的文字呈現，快速載入',
    'settings.visual.api': '牌圖模式',
    'settings.visual.api.desc': '經典偉特塔羅牌圖（1909 公版，已內建於本機，無需網路）',
    'settings.visual.line': '線稿模式',
    'settings.visual.line.desc': '自製單色墨線牌組（78 張完備），隨深淺主題自動反轉',
    'settings.pref.title': '顯示偏好',
    'settings.pref.interactiveDraw': '互動選牌',
    'settings.pref.interactiveDraw.desc': '占卜時親手從牌堆中選牌；關閉則直接翻出結果',
    'settings.pref.spreadInfo': '顯示牌陣說明',
    'settings.pref.spreadInfo.desc': '在牌陣選單與占卜頁顯示牌陣的詳細說明',
    'settings.pref.shortcuts': '啟用鍵盤快捷鍵',
    'settings.pref.shortcuts.desc': '空白鍵＝開始占卜　T＝切換主題　1–6＝切換分頁',
    'settings.data.title': '資料管理',
    'settings.data.stats': '目前共 {n} 筆占卜記錄（上限 {max} 筆），約佔 {kb} KB 儲存空間。',
    'settings.data.export': '匯出資料',
    'settings.data.import': '匯入資料',
    'settings.data.clearAll': '清除所有資料',
    'shichen.unknown': '不詳',
    'shichen.0': '子　23:00–01:00',
    'shichen.1': '丑　01:00–03:00',
    'shichen.2': '寅　03:00–05:00',
    'shichen.3': '卯　05:00–07:00',
    'shichen.4': '辰　07:00–09:00',
    'shichen.5': '巳　09:00–11:00',
    'shichen.6': '午　11:00–13:00',
    'shichen.7': '未　13:00–15:00',
    'shichen.8': '申　15:00–17:00',
    'shichen.9': '酉　17:00–19:00',
    'shichen.10': '戌　19:00–21:00',
    'shichen.11': '亥　21:00–23:00',
    'profile.title': '個人化',
    'profile.birthday.label': '你的生日',
    'profile.shichen.label': '出生時辰',
    'profile.desc': '用來發出你的五張個人牌。僅存在這台裝置，不會上傳。',
    'profile.clear': '清除生日',
    'profile.empty': '尚未設定生日',
    'profile.preview.item': '{pos}：{name} {ori}',
    'profile.pos.origin': '源',
    'profile.pos.inheritance': '承',
    'profile.pos.self': '身',
    'profile.pos.legacy': '續',
    'profile.pos.return': '歸',
    'profile.note.deal.title': '這五張牌怎麼來的',
    'profile.note.deal.text': '你的生日與時辰決定五張牌：從七十八張裡不放回地發五張，每張各自有正位或逆位。不做數字加總、不做縮減，所以每一天、每一個時辰各自成一組，彼此不重複。五張牌依序落在源、承、身、續、歸：從哪來、帶著什麼、你、傳下什麼、往哪去。',
    'profile.note.frame.title': '源承身續歸是本 app 自訂的',
    'profile.note.frame.text': '這五個位置的名字不出自任何傳統，是我們自己取的讀牌框架。五個位置在結構上完全平等，沒有哪一個比較深——名字只是讀牌的框。',
    'profile.note.shichen.title': '時辰只借了一個鐘',
    'profile.note.shichen.text': '時辰取自八字（四柱）的時間單位，八字是唐宋以來的系統。我們只借了「一個時辰兩小時、十二時辰」這個鐘，沒有借四柱的柱義：年柱看祖上、月柱看父母那一套，這裡完全沒有用到。另外不做早子／晚子換日——你選哪個時辰就是哪個時辰，日期用你填的那天。這是刻意的簡化。',
    'profile.note.legacy.title': '與一九八七年那套生日牌不同',
    'profile.note.legacy.text': 'Arrien／Greer 發表的生日牌只用二十二張大牌，把月、日、年加總後反覆縮減；本系統用全部七十八張、含正逆位、不做縮減。那套把 46,217 個生日壓成 21 種結果，丟掉約 72% 的資訊；本系統一天一組，不重複。',
    'profile.note.closing': '牌的力量來自你怎麼詮釋它，不是來自偽造的古老權威。',
    'card.loading': '載入中...',
    'card.imageFailed': '圖片暫時無法載入',
    'card.sub': '{en} · {suit} · {number}',
    'card.seg.meaning': '牌義',
    'card.seg.icon': '圖義',
    'card.seg.context': '情境',
    'card.seg.lore': '源流',
    'card.depth.title': '深度解說',
    'card.symbolism.title': '牌面描述',
    'card.icon.title': '元素解碼',
    'card.image.upright': '正位圖面',
    'card.image.reversed': '逆位圖面',
    'card.context.title': '情境牌義',
    'card.context.love': '感情',
    'card.context.career': '事業',
    'card.context.wealth': '財務',
    'card.context.wellbeing': '身心',
    'card.context.yesno': '是非',
    'card.reflection.label': '✍️ 反思',
    'card.lore.empty': '這張牌的源流資料尚未收錄。',
    'about.title': '關於塔羅',
    'about.intro': '純粹的占卜工具，專注於呈現牌卡結果。所有資料僅存於這台裝置，不上傳、不追蹤。牌圖為 1909 年公版偉特牌，已內建於本機。',
    'about.changelog.empty': '尚無更新紀錄。',
    'privacy.title': '隱私政策',
    'privacy.noCollect': '不收集任何資料',
    'privacy.noTracking': '不使用追蹤工具',
    'privacy.localOnly': '完全本地運作（牌圖亦內建，不連外）',
    'insight.panel.title': '綜合觀察',
    'insight.major.tag': '大阿卡納密集 · {p}',
    'insight.major.text': '{n} 張牌裡有 {k} 張大阿卡納（期望值 {exp} 張）——{cards}。隨機抽牌出現這種或更極端的分布，機率是 {p}。',
    'insight.suit.tag': '{suit}主導 · {p}',
    'insight.suit.text': '{n} 張牌裡有 {k} 張{suit}——{cards}。隨機抽牌出現這種或更極端的集中，機率是 {p}（已計入「四個花色挑最多」這件事本身會提高誤報）。{suit}在標準系統下屬{element}，面向是{faculty}。',
    'insight.reversed.tag': '逆位偏多 · {p}',
    'insight.reversed.text': '{n} 張裡有 {k} 張逆位。每張牌正逆位各半，隨機抽牌出現這種或更極端的偏向，機率是 {p}。',
    'insight.upright.tag': '正位偏多 · {p}',
    'insight.upright.text': '{n} 張裡有 {k} 張正位。每張牌正逆位各半，隨機抽牌出現這種或更極端的偏向，機率是 {p}。',
    'insight.recur.tag': '{n} 張{rank}{ori}',
    'insight.recur.text': '這次抽到 {n} 張{ori}的{rank}——{cards}。Waite 在《圖像塔羅之鑰》（1911）第五節列了這種情況的意義：{term}。',
    'insight.recur.text.both': '這次抽到 {n} 張{ori}的{rank}——{cards}。這條規則有兩個獨立來源，相隔四年、各自寫成：Waite《圖像塔羅之鑰》（1911）第五節說{term}；Foli《Fortune-Telling by Cards》（1915）第四章說{foli}。兩份並列不合併——他們同不同意，你自己看。',
    'rank.ace': '一',
    'rank.two': '二',
    'rank.three': '三',
    'rank.four': '四',
    'rank.five': '五',
    'rank.six': '六',
    'rank.seven': '七',
    'rank.eight': '八',
    'rank.nine': '九',
    'rank.ten': '十',
    'rank.page': '侍者',
    'rank.knight': '騎士',
    'rank.queen': '皇后',
    'rank.king': '國王',
    'waite.recur.natural.king.4': '大榮譽',
    'waite.recur.natural.king.3': '商議',
    'waite.recur.natural.king.2': '小忠告',
    'waite.recur.natural.queen.4': '大爭論',
    'waite.recur.natural.queen.3': '受女性欺瞞',
    'waite.recur.natural.queen.2': '真誠的朋友',
    'waite.recur.natural.knight.4': '嚴肅的事',
    'waite.recur.natural.knight.3': '熱烈的辯論',
    'waite.recur.natural.knight.2': '親密',
    'waite.recur.natural.page.4': '危險的疾病',
    'waite.recur.natural.page.3': '爭執',
    'waite.recur.natural.page.2': '不安',
    'waite.recur.natural.ten.4': '譴責',
    'waite.recur.natural.ten.3': '新的處境',
    'waite.recur.natural.ten.2': '改變',
    'waite.recur.natural.nine.4': '一位好朋友',
    'waite.recur.natural.nine.3': '成功',
    'waite.recur.natural.nine.2': '收受',
    'waite.recur.natural.eight.4': '逆轉',
    'waite.recur.natural.eight.3': '婚姻',
    'waite.recur.natural.eight.2': '新的知識',
    'waite.recur.natural.seven.4': '密謀',
    'waite.recur.natural.seven.3': '體弱',
    'waite.recur.natural.seven.2': '消息',
    'waite.recur.natural.six.4': '豐盛',
    'waite.recur.natural.six.3': '成功',
    'waite.recur.natural.six.2': '易怒',
    'waite.recur.natural.five.4': '規律',
    'waite.recur.natural.five.3': '決心',
    'waite.recur.natural.five.2': '守夜',
    'waite.recur.natural.four.4': '近在眼前的旅程',
    'waite.recur.natural.four.3': '一個值得反覆思索的主題',
    'waite.recur.natural.four.2': '失眠',
    'waite.recur.natural.three.4': '進展',
    'waite.recur.natural.three.3': '合一',
    'waite.recur.natural.three.2': '平靜',
    'waite.recur.natural.two.4': '爭端',
    'waite.recur.natural.two.3': '安全',
    'waite.recur.natural.two.2': '和諧一致',
    'waite.recur.natural.ace.4': '有利的機緣',
    'waite.recur.natural.ace.3': '小小的成功',
    'waite.recur.natural.ace.2': '欺瞞',
    'waite.recur.reversed.king.4': '迅捷',
    'waite.recur.reversed.king.3': '商務往來',
    'waite.recur.reversed.king.2': '計畫',
    'waite.recur.reversed.queen.4': '壞的同伴',
    'waite.recur.reversed.queen.3': '暴食',
    'waite.recur.reversed.queen.2': '工作',
    'waite.recur.reversed.knight.4': '結盟',
    'waite.recur.reversed.knight.3': '一場決鬥，或當面的衝突',
    'waite.recur.reversed.knight.2': '易受影響',
    'waite.recur.reversed.page.4': '匱乏',
    'waite.recur.reversed.page.3': '怠惰',
    'waite.recur.reversed.page.2': '交際',
    'waite.recur.reversed.ten.4': '事件、發生',
    'waite.recur.reversed.ten.3': '失望',
    'waite.recur.reversed.ten.2': '期待得到印證',
    'waite.recur.reversed.nine.4': '放高利貸',
    'waite.recur.reversed.nine.3': '輕率',
    'waite.recur.reversed.nine.2': '小額獲利',
    'waite.recur.reversed.eight.4': '錯誤',
    'waite.recur.reversed.eight.3': '一場景象',
    'waite.recur.reversed.eight.2': '不幸',
    'waite.recur.reversed.seven.4': '爭吵者',
    'waite.recur.reversed.seven.3': '喜悅',
    'waite.recur.reversed.seven.2': '名聲不佳的女子',
    'waite.recur.reversed.six.4': '掛慮',
    'waite.recur.reversed.six.3': '滿足',
    'waite.recur.reversed.six.2': '衰敗',
    'waite.recur.reversed.five.4': '秩序',
    'waite.recur.reversed.five.3': '猶豫',
    'waite.recur.reversed.five.2': '逆轉',
    'waite.recur.reversed.four.4': '外出走動',
    'waite.recur.reversed.four.3': '不安',
    'waite.recur.reversed.four.2': '爭執',
    'waite.recur.reversed.three.4': '大成功',
    'waite.recur.reversed.three.3': '寧靜',
    'waite.recur.reversed.three.2': '安全無虞',
    'waite.recur.reversed.two.4': '和解',
    'waite.recur.reversed.two.3': '憂懼',
    'waite.recur.reversed.two.2': '不信任',
    'waite.recur.reversed.ace.4': '不名譽',
    'waite.recur.reversed.ace.3': '放蕩',
    'waite.recur.reversed.ace.2': '敵人',
    'foli.recur.natural.ace.4': '破財、與朋友離散、感情上的麻煩、牢獄之災',
    'foli.recur.natural.ace.3': '一時的麻煩，由好消息化解',
    'foli.recur.natural.king.4': '榮銜、擢升、好職位',
    'foli.recur.natural.king.2': '生意上的合作',
    'foli.recur.natural.queen.3': '友善的造訪',
    'foli.recur.reversed.queen.3': '醜聞、流言',
    'foli.recur.natural.queen.2': '交換瑣碎的私語、祕密被洩露、朋友間的會面',
    'foli.recur.natural.ten.4': '好運、財富',
    'foli.recur.natural.ten.2': '意外的好運',
    'foli.recur.natural.nine.4': '意外之事成真',
    'foli.recur.natural.nine.3': '健康、財富、幸福',
    'foli.recur.natural.nine.2': '興旺與滿足、遺囑文件',
    'foli.recur.reversed.nine.2': '小煩惱',
    'foli.recur.reversed.eight.4': '不受擾動的安定',
    'foli.recur.natural.eight.3': '新的家庭關係、正當的意圖',
    'foli.recur.reversed.eight.3': '調情、放蕩與愚行',
    'foli.recur.natural.eight.2': '輕浮的享樂、一時的戀慕、意料之外的發展',
    'foli.recur.natural.seven.4': '算計與圈套、爭執與對立',
    'foli.recur.natural.seven.3': '健康不佳、悔恨',
    'foli.recur.natural.seven.2': '兩情相悅、一件意外的事',
    'foli.recur.reversed.seven.2': '不忠、欺瞞或悔恨',
    'insight.class.court.tag': '宮廷牌密集 · {p}',
    'insight.class.court.text': '{n} 張牌裡有 {k} 張宮廷牌（期望值 {exp} 張）——{cards}。牌組 78 張裡只有 16 張宮廷牌，隨機抽牌出現這種或更極端的密集，機率是 {p}。宮廷牌在 Waite 的用法裡對應人物——《圖像塔羅之鑰》(1911) 第七節挑指示者，用的就是宮廷牌。',
    'insight.class.pip.tag': '數字牌密集 · {p}',
    'insight.class.pip.text': '{n} 張牌裡有 {k} 張數字牌（期望值 {exp} 張）。隨機抽牌出現這種或更極端的密集，機率是 {p}。',
    'insight.quality.tag': '{quality}星座 · {p}',
    'insight.quality.text': '你抽到的 {k} 張大阿卡納，在 Thierens（《General Book of the Tarot》1930）的星座對應下全部落在{quality}。隨機出現的機率是 {p}。注意這是 Thierens 自己的一套對應，與金色黎明系不同——本站牌義用的是 Waite，這條只是另一個角度。',
    'quality.cardinal': '啟動',
    'quality.fixed': '固定',
    'quality.mutable': '變動',
    'mofa.terms.title': '關鍵詞（正／逆位）',
    'waite.terms.title': 'Waite 1911 原文語詞',
    'waite.terms.upright': '正位',
    'waite.terms.reversed': '逆位',
    'waite.terms.note': '出自 A.E. Waite《The Pictorial Key to the Tarot》(1911)，這副牌的原始作者。保留英文原字：翻譯過就成了轉述，而這裡要的是他實際寫下的詞。他的讀法與上方的現代牌義常有出入——那個出入本身就值得看。',
    'waite.additional.title': 'Waite 1911 追加語意',
    'waite.additional.note': '同一本書第四節，Waite 另外給 56 張小牌的第二組語詞（22 張大牌他沒寫）。他自己在那節結尾註明了兩件事：這組語意與牌面圖案關聯不大，而且「與前面給的往往彼此不一致」。所以這裡不與上一塊合併——那個不一致是他本人留下的，不是我們沒整理。',
    'court.looks.title': '這張牌常指向的人',
    'court.looks.wands': '髮色金黃或赤褐、膚色白皙、藍眼',
    'court.looks.cups': '髮色淺褐或暗金、灰眼或藍眼',
    'court.looks.swords': '髮色深褐、榛色或灰眼、膚色偏暗',
    'court.looks.pentacles': '髮色深褐或黑、深色眼睛、膚色偏黃或黝黑',
    'court.looks.note': 'Waite《圖像塔羅之鑰》(1911) 挑選指示者的規則。他自己註明這不該死板套用——已知的性情可以推翻外貌。',
    'suit.faculty.wands': '意志、創造、行動',
    'suit.faculty.cups': '情感、關係、內在',
    'suit.faculty.swords': '理性、邏輯、判斷',
    'suit.faculty.pentacles': '物質、身體、累積',
    'meaning.minor.upright': '{stage}。落在{suit}的領域——{faculty}。這張牌讀作：{kw}。{read}。',
    'meaning.minor.reversed': '逆位時，同一組主題轉了向——{kw}。{read}。',
    'card.meaning.minorNote': '小牌牌義由三個零件組成：位階的讀法（黃金黎明以降的數字系統，措辭是本站的）×花色的領域（見源流分頁的對應系統）×這張牌自己的關鍵詞。做法比照小牌源流：小牌沒有 56 段各自獨立的真相。',
    'card.context.minorNote': '小牌的情境解讀由兩個零件組成：這個位階在該情境下的讀法×這個花色管的領域（本站系統，做法比照源流分頁）。反思問句隨位階走；「是否傾向」是逐張校準的資料。',
    'systems.title': '對應系統',
    'systems.std.source': '標準系統（本站預設）',
    'systems.std.note': '出自金色黎明一系的對照表——這副牌是 Pamela Colman Smith 為 Waite 畫的，而 Waite 屬於這一系，所以本站的牌義以這套為準。大阿卡納沒有列：那部分沒有一份夠完整的公有領域來源，寧可留白也不用星座去回推。',
    'systems.thierens.source': 'Thierens 1930',
    'systems.thierens.note': '出自 A.E. Thierens《General Book of the Tarot》(1930)，他自己的一套，與上面那組全面不同（他的力量與正義也對調）。列在這裡是多一個角度，不是取代——兩套並排不合併。',
    'systems.thierens.note.clash': '🔴 這張牌的元素兩套說法不一樣，上下對照就看得到。Thierens 的花色元素只有聖杯與通說相同，權杖、寶劍、錢幣三個都相反（他的權杖是風、寶劍是土、錢幣是火）。這不是誰抄錯——他 1930 年就是自成一家。本站不替他們調解，也不取平均：火和風平均不出東西。',
    'systems.label.element': '元素',
    'systems.label.faculty': '面向',
    'systems.label.french': '撲克花色',
    'systems.label.planet': '星象',
    'systems.label.sign': '星座',
    'systems.label.house': '宮位',
    'systems.label.quality': '性質',
    'systems.label.triplicity': '三分性',
    'systems.house': '第 {n} 宮',
    'element.fire': '火',
    'element.water': '水',
    'element.air': '風',
    'element.earth': '土',
    'french.clubs': '梅花',
    'french.hearts': '紅心',
    'french.spades': '黑桃',
    'french.diamonds': '方塊',
    'planet.saturn': '土星',
    'planet.jupiter': '木星',
    'planet.mars': '火星',
    'planet.sun': '太陽',
    'planet.venus': '金星',
    'planet.mercury': '水星',
    'planet.moon': '月亮',
    'planet.earth': '地球',
    'planet.uranus': '天王星',
    'planet.neptune': '海王星',
    'sign.aries': '牡羊座',
    'sign.taurus': '金牛座',
    'sign.gemini': '雙子座',
    'sign.cancer': '巨蟹座',
    'sign.leo': '獅子座',
    'sign.virgo': '處女座',
    'sign.libra': '天秤座',
    'sign.scorpio': '天蠍座',
    'sign.sagittarius': '射手座',
    'sign.capricorn': '摩羯座',
    'sign.aquarius': '水瓶座',
    'sign.pisces': '雙魚座',
    'insight.echo.tag': '共振 · {term}',
    'insight.echo.text': '{cards}的語詞都指向{term}。整副 78 張裡只有 {K} 張帶這個語詞。（{src}）',
    'insight.echo.text.multi': '{cards}的語詞指向同一件事——{term}。其中最少見的是{best}，整副 78 張裡只有 {K} 張帶著。（{src}）',
    'insight.echo.text.multiSrc': '{cards}在 {m} 個來源裡各自共振：{parts}。',
    'insight.echo.part': '「{terms}」（{src}）',
    'insight.echo.net.tag': '共振網 · {hub}',
    'insight.echo.net.text': '{hub}同時落在好幾組共振裡：{links}。',
    'insight.echo.net.link': '與{others}共享{parts}',
    'insight.echo.net.extra': '{cards}另外共享{parts}',
    'insight.card.pos': '{name}（{ori}・{pos}）',
    'insight.card.bottom': '底牌{name}（{ori}）',
    'insight.profile.tag': '牌面剖面',
    'insight.profile.text': '{n} 張牌：大阿卡納 {maj}、宮廷 {court}、數字牌 {pip}，逆位 {rev} 張；小牌元素——{els}。',
    'insight.profile.text.noMinors': '{n} 張牌全是大阿卡納，逆位 {rev} 張。',
    'insight.profile.el': '{el} {k}',
    'insight.axis.tag': '{p1}×{p2}',
    'insight.axis.rank.text': '{p1}與{p2}被同一個階級佔住：{c1}與{c2}都是{rank}。',
    'insight.axis.suit.tag': '時間線同花色',
    'insight.axis.suit.text': '過去、現在、未來三個位置同花色——{cards}，全是{suit}。',
    'insight.echo.card': '{name}（{ori}）',
    'insight.echo.pair': '{zh}（{en}）',
    'insight.echo.src.ours': '本站關鍵詞，不分正逆位',
    'insight.echo.src.mofa': 'mofatarot 正逆位關鍵詞',
    'insight.echo.src.waite': 'Waite 1911 第二節語詞',
    'insight.echo.src.add': 'Waite 1911 第四節追加語意',
    'insight.balanced.tag': '無顯著偏向',
    'insight.balanced.text': '花色、大阿卡納、正逆位、同階級重複、語詞共振與軸線對位都檢查過了，這次的牌面沒有值得特別指出的集中或重複。牌數越少越容易如此——三張牌本來就很難撞出結構。',
    'insight.bottom.tag': '底牌基調',
    'insight.bottom.text': '底牌是{name}（{ori}）——整副牌洗好後墊在最底、不參與牌陣的那張。本站把它當作這次占卜的背景基調，它的關鍵詞：{kw}。',
    'insight.bottom.text.noKeywords': '底牌是{name}（{ori}）——整副牌洗好後墊在最底、不參與牌陣的那張。本站把它當作這次占卜的背景基調。',
    'pattern.panel.title': '模式洞察',
    'pattern.panel.sub': '來自你的 {n} 次占卜',
    'pattern.none.tag': '尚未開始',
    'pattern.none.text': '完成第一次占卜後，這裡會開始累積你的模式。',
    'pattern.building.tag': '尚在累積',
    'pattern.building.text': '再累積 {n} 次占卜，這裡就會開始浮現你的模式——你偏好的花色、標籤背後的傾向、反覆出現的牌。',
    'pattern.dominant.tag': '{suit}長期主導',
    'pattern.dominant.text': '你的 {total} 張牌裡有 {k} 張{suit}（{pct}%，期望值 {exp} 張）。純隨機出現這種集中的機率不超過 {p}（已計入「四個花色挑最多」）。{suit}在標準系統下屬{element}，面向是{faculty}。',
    'pattern.tag.tag': '標籤「{name}」',
    'pattern.tag.text': '你標記為「{name}」的 {n} 次占卜共 {m} 張牌，其中 {suit}佔 {k} 張（{pct}%）。純隨機出現這種集中的機率不超過 {p}（已計入花色與標籤的多重比較）。{suit}的面向是{faculty}。',
    'pattern.reversed.high.tag': '逆位偏多',
    'pattern.reversed.high.text': '長期 {total} 張牌裡有 {k} 張逆位（{pct}%）。每張牌正逆各半，隨機出現這種或更極端偏向的機率是 {p}。',
    'pattern.reversed.low.tag': '逆位偏少',
    'pattern.reversed.low.text': '長期 {total} 張牌裡只有 {k} 張逆位（{pct}%）。每張牌正逆各半，隨機出現這種或更極端偏向的機率是 {p}。',
    'pattern.regular.tag': '常客牌',
    'pattern.regular.text': '{name}在你的 {total} 張牌裡出現了 {n} 次。78 張牌隨機發，「任何一張」出現到這個次數的機率不超過 {p}。它的關鍵詞：{kw}。',
    'pattern.regular.text.noKeywords': '{name}在你的 {total} 張牌裡出現了 {n} 次。78 張牌隨機發，「任何一張」出現到這個次數的機率不超過 {p}。',
    'pattern.major.high.tag': '大牌偏多',
    'pattern.major.high.text': '你的 {total} 張牌裡有 {k} 張大阿卡納（{pct}%，期望值 {exp} 張）。純隨機出現這種集中的機率不超過 {p}。',
    'pattern.major.low.tag': '大牌偏少',
    'pattern.major.low.text': '你的 {total} 張牌裡只有 {k} 張大阿卡納（{pct}%，期望值 {exp} 張）。純隨機出現這種稀疏的機率不超過 {p}。',
    'pattern.pace.tag': '節奏變快',
    'pattern.pace.text': '最近 30 天你占卜了 {n} 次，前一個 30 天是 {prev} 次。',
    'pattern.flat.tag': '無顯著偏向',
    'pattern.flat.text': '花色、大牌比例、正逆位、常客牌與標籤交叉都檢查過了，你的長期分布都在隨機範圍內，沒有統計上值得特別指出的集中。',
    'btn.startReading': '開始占卜',
    'btn.share': '分享',
    'btn.copyResults': '複製結果',
    'btn.shareImage': '生成分享圖',
    'btn.print': '列印',
    'btn.note': '筆記',
    'btn.tag': '標籤',
    'btn.delete': '刪除',
    'btn.cancel': '取消',
    'btn.save': '儲存',
    'btn.add': '新增',
    'btn.confirm': '確定',
    'btn.close': '關閉',
    'note.title': '新增筆記',
    'note.placeholder': '寫下你的感受與想法...',
    'tag.title': '新增標籤',
    'tag.common': '常用標籤',
    'tag.custom': '自訂標籤',
    'tag.placeholder': '輸入標籤名稱...',
    'confirm.clearAll.title': '清除所有資料',
    'confirm.clearAll.message': '將刪除全部占卜記錄與偏好設定，且無法復原。建議先匯出備份。',
    'confirm.clearAll.ok': '全部清除',
    'confirm.import.title': '匯入記錄',
    'confirm.import.message': '將匯入 {n} 筆記錄，並覆蓋現有的 {current} 筆記錄，確定繼續嗎？',
    'confirm.import.ok': '匯入',
    'confirm.delete.title': '刪除記錄',
    'confirm.delete.message': '確定要刪除此占卜記錄嗎？',
    'confirm.delete.ok': '刪除',
    'confirm.clearHistory.title': '清除所有記錄',
    'confirm.clearHistory.message': '將刪除全部 {n} 筆占卜記錄，包含筆記與標籤。此動作無法復原。',
    'confirm.clearHistory.ok': '全部刪除',
    'confirm.learnReset.title': '重設學習進度',
    'confirm.learnReset.message': '熟練度與連續天數都會歸零，且無法復原。',
    'confirm.learnReset.ok': '重設',
    'toast.deckTooSmall': '牌組數量不足',
    'toast.copied': '已複製到剪貼簿',
    'toast.copyFailed': '複製失敗',
    'toast.linkCopied': '連結已複製',
    'toast.noReading': '請先進行占卜',
    'toast.shareImageDone': '分享圖已下載',
    'toast.shareImageFailed': '分享圖生成失敗',
    'toast.visualStyle': '已切換至{name}',
    'toast.favorited': '已加入收藏',
    'toast.unfavorited': '已取消收藏',
    'toast.deleted': '已刪除記錄',
    'toast.historyCleared': '已清除所有記錄',
    'toast.noteSaved': '筆記已儲存',
    'toast.tagUpdated': '標籤已更新',
    'toast.exported': '資料已匯出',
    'toast.imported': '已匯入 {n} 筆記錄',
    'toast.imported.withPrefs': '已匯入 {n} 筆記錄與 {prefs} 項偏好',
    'toast.importBadFormat': '檔案格式錯誤',
    'toast.importParseFailed': '檔案解析失敗',
    'toast.learnReset': '學習進度已重設',
    'toast.birthdayInvalid': '生日格式不正確',
    'toast.birthdayCleared': '已清除生日',
    'toast.profileUpdated': '已更新你的個人牌'
  }
};
