const waiteZh = {
  'a bad card': '不吉的牌',
  'a bad man': '壞男人',
  'a bad woman': '壞女人',
  'a child': '孩子',
  'a dangerous rival': '危險的對手',
  'a dark child': '深色頭髮的孩子',
  'a dark girl': '深色頭髮的女孩',
  'a dark woman': '深色頭髮的女子',
  'a dark young man': '深色頭髮的青年',
  'a dark youth': '深色頭髮的少年',
  'a good card': '吉利的牌',
  'a good harvest': '豐收',
  'a great person': '顯貴人物',
  'a happy marriage': '美滿的婚姻',
  'a lawyer': '律師',
  'a lover': '愛人',
  'a merchant': '商人',
  'a nun': '修女',
  'a postman': '郵差',
  'a priest': '神父',
  'a rather dark man': '髮色偏深的男子',
  'a serious quarrel': '嚴重的爭吵',
  'a sign of birth': '生育的徵兆',
  'a soldier': '軍人',
  'a studious youth': '好學的青年',
  'a very good card': '極吉的牌',
  'a widow': '寡婦',
  'abandonment': '遺棄',
  'abode': '居所',
  'absence': '缺席',
  'abundance': '豐盛',
  'abuse if power': '濫用權力',
  'accident': '意外',
  'accommodation': '通融',
  'accomplishment': '達成',
  'achievement': '成就',
  'action': '行動',
  'activity in undertakings': '事業上的活躍',
  'address': '機敏手腕',
  'adjournment': '延期',
  'advances': '示好接近',
  'advantage': '優勢',
  'adversity': '逆境',
  'affection': '情愛',
  'affinities': '情投意合',
  'affinity': '契合',
  'affliction': '苦難',
  'agitation': '騷動',
  'aid': '援助',
  'alienation': '疏離',
  'alliance': '結盟',
  'alliances': '諸般結盟',
  'an ecclesiastic': '教士',
  'an envoy': '使者',
  'an illness': '疾病',
  'an useful man': '有用的人',
  'ancestry': '血統家世',
  'anecdotes': '軼聞',
  'announcements': '通告',
  'annoyance': '煩擾',
  'anxiety': '焦慮',
  'any kind of success': '任何形式的成功',
  'apathy': '冷漠',
  'application': '勤勉',
  'apprehension': '憂懼',
  'approach': '逼近',
  'archives': '檔案文書',
  'aristocracy': '貴族',
  'arrival': '到來',
  'arrogance': '傲慢',
  'arrows of jealousy': '妒忌之箭',
  'art and science': '技藝與學問',
  'artifice': '巧計',
  'assured success': '篤定的成功',
  'astonishing news': '驚人的消息',
  'attachment': '依戀',
  'attempt': '嘗試',
  'attraction': '吸引',
  'augmentation': '增長',
  'austere': '嚴峻',
  'authority': '權威',
  'authority and will': '權威與意志',
  'avarice': '貪婪',
  'aversion': '厭惡',
  'babbling': '饒舌',
  'bad faith': '背信',
  'bad intelligence': '壞消息',
  'bad news': '噩耗',
  'bad omen': '凶兆',
  'bale': '禍害',
  'barbarity': '野蠻殘暴',
  'barter': '以物易物',
  'bearing his merchandise': '負貨而行',
  'beauty': '美貌',
  'beginning': '開端',
  'benevolence': '仁慈',
  'bewrayment': '洩露',
  'bias': '偏頗',
  'bigotry': '偏執',
  'birth': '誕生',
  'blindness': '盲目',
  'body politic': '政體',
  'bravery': '勇敢',
  'burial and obsequies': '埋葬與喪儀',
  'business': '事業',
  'calamities of all kinds': '各種災禍',
  'calamity': '災厄',
  'calumny': '誹謗',
  'capacity': '才幹',
  'captivity': '囚禁',
  'carelessness': '疏忽',
  'censure': '譴責',
  'certitude': '確信',
  'chagrin': '懊惱',
  'chance': '機運',
  'change of place': '處所變動',
  'change of position': '地位變動',
  'change of residence': '遷居',
  'chaos': '混亂',
  'chaste': '貞潔',
  'childbirth': '分娩',
  'circumspection': '審慎',
  'clandestine': '隱密',
  'collaboration will favour enterprise': '合作有利於事業',
  'comfortable material conditions': '優渥物質條件',
  'command': '統率',
  'commerce': '商貿',
  'commission': '委任',
  'commissionary': '受任者',
  'compassion': '憐憫',
  'competing interests': '利益競逐',
  'competition': '競爭',
  'complete success and honours': '圓滿成功與榮譽',
  'composition': '和解',
  'concealment': '隱瞞',
  'conceit': '自負',
  'conception': '受孕',
  'concord': '和睦',
  'concordance': '相合一致',
  'confession': '坦承',
  'confidence': '信心',
  'conflict': '衝突',
  'confusion': '混亂',
  'confusion to enemies': '敵人潰亂',
  'conquest': '征服',
  'consanguinity': '血親',
  'considerable loss': '重大損失',
  'consolation': '慰藉',
  'content': '心滿意足',
  'contentment': '知足',
  'contradiction': '矛盾',
  'contrarieties': '諸多拂逆',
  'conviction': '堅定信念',
  'corruption': '腐敗',
  'counsel': '忠告',
  'country life': '鄉間生活',
  'countryman': '鄉間男子',
  'countrywoman': '鄉間女子',
  'courage': '勇氣',
  'craftsmanship': '工藝技藝',
  'creation': '創造',
  'creative intelligence': '創造性智性',
  'credit': '信用',
  'crisis': '危機',
  'cruelty': '殘酷',
  'cupidity': '貪婪',
  'cure': '痊癒',
  'danger': '危險',
  'dark girl': '深色頭髮的女孩',
  'dark man': '深髮男子',
  'dark woman': '深色頭髮的女子',
  'dark young man': '深髮青年',
  'darkness': '黑暗',
  'dealings with rogues': '與無賴往來',
  'death': '死亡',
  'decadence': '頹敗',
  'deceit': '欺瞞',
  'deception': '蒙騙',
  'decision': '決斷',
  'declaration': '表明宣告',
  'defeat': '挫敗',
  'defence': '防禦',
  'degradation': '淪落',
  'delay': '延遲',
  'deliberation': '審慎斟酌',
  'delirium': '譫妄',
  'demeanour': '舉止儀態',
  'departure': '離去',
  'departure of a relative': '親人離去',
  'depravity': '敗德',
  'design': '圖謀',
  'desire': '慾望',
  'desolation': '淒涼荒蕪',
  'despair': '絕望',
  'despotism': '專制',
  'destiny': '命運',
  'destitution': '赤貧',
  'destruction': '毀滅',
  'determination': '決心',
  'devoted woman': '忠貞的女子',
  'difficulties': '重重困難',
  'difficulties and contradictions': '困難與矛盾',
  'difficulty': '困難',
  'diplomacy': '外交手腕',
  'disappointment': '失望',
  'disaster': '災難',
  'discernment': '洞察力',
  'discord': '不和',
  'discouragement': '氣餒',
  'discovery': '發現',
  'disease': '疾病',
  'disgrace': '蒙羞',
  'disguise': '偽裝',
  'disgust': '厭惡',
  'dishonest': '不誠實',
  'dishonour': '名譽掃地',
  'disloyalty': '背信',
  'disorder': '失序',
  'dispatch': '速辦',
  'dispersion': '離散',
  'dispute': '爭執',
  'disputes': '諸多爭執',
  'disquiet': '不安',
  'dissimulation': '佯裝',
  'dissipation': '放蕩',
  'distraction': '心神渙散',
  'distress': '困厄',
  'distribution': '分配',
  'disunion': '決裂',
  'divination': '占卜',
  'divinity': '神性',
  'division': '分裂',
  'doctor': '醫生',
  'double-dealing man': '兩面派的男人',
  'doubt': '疑慮',
  'dowry': '嫁妝',
  'duplicity': '表裡不一',
  'economical': '節儉',
  'economy': '節約',
  'ecstasy': '狂喜',
  'effort': '努力',
  'elevation': '高升',
  'embarrassments': '窘境',
  'embellishment': '潤飾',
  'embroilment': '糾紛',
  'emigration': '移居',
  'emotion': '情緒',
  'employment': '職務',
  'enchantment': '魅惑',
  'end': '終結',
  'end of the business': '事情了結',
  'energy': '精力',
  'enforced gaiety': '強顏歡笑',
  'enjoyment': '享樂',
  'enmity': '敵意',
  'enterprise': '事業',
  'envoy': '使者',
  'envy': '嫉妒',
  'equity': '公允',
  'error': '謬誤',
  'even deceit and infidelity': '甚至是欺瞞與不忠',
  'evil': '邪惡',
  'evil fatality': '凶惡的宿命',
  'evil intention': '惡意',
  'evil news': '噩耗',
  'exaction': '苛索',
  'examination': '審查',
  'excessive severity': '過度嚴苛',
  'executive': '執行的權柄',
  'exile': '流放',
  'expedient': '權宜之計',
  'expedition': '迅捷',
  'extraction': '出身',
  'extraordinary efforts': '非凡的努力',
  'extravagance': '揮霍',
  'failure': '失敗',
  'failure of marriage projects': '婚事告吹',
  'fair child': '淺髮色的孩子',
  'fair man': '金髮男子',
  'fair woman': '金髮女子',
  'fair young man': '金髮青年',
  'fairy favours': '精靈的眷顧',
  'faithful': '忠實',
  'fall': '墜落',
  'false projects': '虛妄的圖謀',
  'falsehood': '謊言',
  'family': '家族',
  'family matters': '家務事',
  'fatality': '劫數',
  'favour': '恩寵',
  'fear': '恐懼',
  'feasting': '宴飲',
  'felicity': '幸福',
  'felicity hereof': '由此而來的幸福',
  'female sadness and embarrassment': '女子的憂傷與窘迫',
  'fertility': '豐饒',
  'fixity': '固著',
  'flight': '逃遁',
  'folly': '愚行',
  'foolish designs': '愚蠢的圖謀',
  'force': '力量',
  'fortunate marriage': '良緣',
  'fortune': '幸運',
  'fraud': '詐欺',
  'frenzy': '狂亂',
  'friend': '朋友',
  'friendly': '友善',
  'friendship': '友誼',
  'frugality': '節儉',
  'fruitfulness': '多產',
  'fulfilment': '圓滿',
  'fulfilment of deferred hope': '延宕的希望終獲實現',
  'gain': '獲利',
  'games of hazard': '賭局',
  'generally favourable': '大體有利',
  'generally married': '多半已婚',
  'generosity': '慷慨',
  'gift': '贈禮',
  'gifts': '諸多餽贈',
  'gifts for a lady': '給女士的禮物',
  'giving joy': '帶來喜樂',
  'giving new relations': '締結新關係',
  'glory': '榮耀',
  'gold': '黃金',
  'good': '善',
  'good advice': '良言忠告',
  'good augury': '吉兆',
  'good business': '好生意',
  'good understanding': '融洽相知',
  'good woman': '良善女子',
  'goodwill towards the querent': '對問卜者的善意',
  'great haste': '極度倉促',
  'great hope': '厚望',
  'great joy': '大喜',
  'great riches': '钜富',
  'handwriting': '手書',
  'happiness': '幸福',
  'happy issue': '美好結局',
  'harmony': '和諧',
  'haughtiness': '倨傲',
  'haven of refuge': '避風港',
  'healing': '療癒',
  'hermit\'s repose': '隱者之憩',
  'hidden enemies': '暗敵',
  'hindrances': '阻礙',
  'holy table': '聖桌',
  'honest': '誠實',
  'honest and conscientious': '誠實盡責',
  'honour': '榮譽',
  'honourable': '可敬',
  'hope': '希望',
  'hope destroyed': '希望破滅',
  'husband': '丈夫',
  'idea': '想法',
  'idleness': '怠惰',
  'ignorance': '無知',
  'ill': '禍害',
  'illusion': '幻象',
  'images of reflection': '映照之象',
  'imaginary vexations': '臆想煩擾',
  'imagination': '想像',
  'imitation': '仿效',
  'immaturity': '未熟',
  'impatience': '不耐',
  'imperfections': '缺陷',
  'imposture': '冒名頂替',
  'impotence': '無能為力',
  'imprisonment': '囚禁',
  'imprudence': '輕率',
  'incapacity': '無能',
  'incitement': '煽動',
  'inclination': '傾心',
  'inconstancy': '善變',
  'increase': '增益',
  'indefinite delay': '無限期延宕',
  'indigence': '赤貧',
  'indignation': '義憤',
  'inertia': '惰性',
  'infamy': '惡名',
  'inflexible will': '不可動搖的意志',
  'ingenuity': '巧思',
  'inheritance': '繼承',
  'initiative': '主動',
  'injustice': '不義',
  'inspiration': '靈感',
  'instability': '不穩',
  'instruction': '教誨',
  'interest': '利益',
  'internal dispute': '內部爭執',
  'interruption': '中斷',
  'intimacy': '親密',
  'intoxication': '沉醉',
  'intrigues': '陰謀',
  'intuition': '直覺',
  'invention': '發明',
  'invitation': '邀約',
  'irregularity': '失序',
  'jealousy': '嫉妒',
  'journey by water': '水路之旅',
  'joy': '喜悅',
  'law': '法律',
  'law and art': '法律與技藝',
  'legacies': '遺產',
  'legacy': '遺贈',
  'legal complications': '法律糾紛',
  'length of days': '長壽',
  'lethargy': '昏沉',
  'letters of exchange': '匯票',
  'liberality': '慷慨',
  'liberty': '自由',
  'light': '光',
  'litigation': '訴訟',
  'looking back': '回顧',
  'loss': '損失',
  'love': '愛',
  'love of money': '貪財',
  'loving': '深情',
  'loving intelligence': '慈愛的智性',
  'loyalty': '忠誠',
  'luck': '運氣',
  'luxury': '奢華',
  'magnanimity': '寬宏',
  'magnificence': '華美',
  'magus': '魔法師',
  'malice': '惡意',
  'man of arms': '武人',
  'man of business': '生意人',
  'management': '經營',
  'mania': '狂躁',
  'many contrarieties': '諸多阻逆',
  'marriage': '婚姻',
  'marriage broken off': '婚約破裂',
  'master': '雇主',
  'material happiness': '物質的幸福',
  'mediocrity': '平庸',
  'meditation': '冥想',
  'mental alienation': '精神錯亂',
  'mental disease': '精神疾病',
  'mercy and goodness': '慈悲與良善',
  'message': '訊息',
  'metier': '本行',
  'mildness': '溫和',
  'militant intelligence': '尚武的智性',
  'miscarriage': '挫敗',
  'misery': '悲慘',
  'mistress': '情婦',
  'mistrust': '不信任',
  'moderation': '節制',
  'modesty': '謙遜',
  'money': '金錢',
  'moral or physical ardour': '精神或肉體的熱切',
  'mortality': '必死',
  'mortification': '屈辱',
  'mourning': '哀悼',
  'movement': '行動',
  'multiplicity': '繁多',
  'mutation': '變異',
  'mystery': '奧祕',
  'negligence': '疏忽',
  'negotiations': '談判',
  'new environment': '新環境',
  'new instruction': '新的教導',
  'new knowledge': '新知',
  'new relations': '新的人際關係',
  'news': '消息',
  'nourishment': '滋養',
  'novelty': '新奇',
  'nullity': '虛無',
  'obliging': '殷勤',
  'observation': '觀察',
  'obstacles': '障礙',
  'obstacles of all kinds': '各種阻礙',
  'obstruction': '阻撓',
  'occult forces': '神祕力量',
  'offices of the crown': '王室職位',
  'opposition': '對立',
  'opulence': '豐裕',
  'origin': '起源',
  'outcome': '結果',
  'overkindness': '過度仁慈',
  'overseeing': '監督',
  'pain': '痛苦',
  'passion': '激情',
  'patrimony': '祖產',
  'peace': '和平',
  'pension': '年金',
  'perdition': '沉淪',
  'perfect contentment': '圓滿的知足',
  'perfect satisfaction': '圓滿的滿足',
  'perfection and merriment': '圓滿與歡愉',
  'perfidy': '背信',
  'peril': '危難',
  'permanence': '恆常',
  'perplexity': '困惑',
  'perverse woman': '乖戾的女人',
  'perversity': '乖戾',
  'petrifaction': '僵化',
  'pettiness': '小器',
  'physical bien-etre': '身體安適',
  'physical suffering': '肉體的痛苦',
  'physician': '醫者',
  'pillage': '劫掠',
  'placidity': '恬靜',
  'pleasant memories': '愉快的回憶',
  'pleasure': '愉悅',
  'policy': '權謀',
  'power': '力量',
  'power and authority': '權力與威權',
  'power in trammels': '受縛的力量',
  'precaution': '防範',
  'presage': '預兆',
  'present prosperity': '當前的興旺',
  'presentiment': '預感',
  'presents': '禮物',
  'presumption': '僭妄',
  'principle': '原則',
  'privation': '匱乏',
  'probably neglected': '多半被忽略',
  'probity': '廉正',
  'prodigality': '揮霍',
  'professor': '教授',
  'profit': '獲利',
  'profligacy': '放蕩',
  'project': '計畫',
  'prophecy': '預言',
  'proposition': '提議',
  'prosperity': '興旺',
  'protection': '庇護',
  'providence also war': '天佑，亦主戰爭',
  'prudence': '審慎',
  'prudery': '假正經',
  'public rejoicings': '公眾的歡慶',
  'publicity': '張揚',
  'puerility': '幼稚',
  'purgation': '滌淨',
  'pusillanimity': '怯懦',
  'quarrel': '爭吵',
  'quarrelling': '口角不斷',
  'quarrels': '諸般爭執',
  'ravage': '蹂躪',
  'realization': '實現',
  'realizing intelligence': '實現的智慧',
  'reason': '理性',
  'reasonable fear': '合理的恐懼',
  'recompense': '報償',
  'recreation and its connexions': '消遣及其牽連',
  'reflection': '沉思',
  'religions': '諸宗教',
  'removal': '遷移',
  'renewal': '更新',
  'renown': '聲望',
  'repose': '安歇',
  'represents house or dwelling': '代表房屋或住所',
  'resistance': '抵抗',
  'resolve': '決心',
  'responsibility': '責任',
  'responsible': '負責任的',
  'retreat': '退隱',
  'return': '歸返',
  'revocation': '撤銷',
  'revolution': '劇變',
  'riches': '財富',
  'rightness': '正當',
  'riot': '暴亂',
  'robbery': '劫掠',
  'roguery': '奸詐行徑',
  'route': '路途',
  'ruin': '毀滅',
  'rule': '統治',
  'rupture': '決裂',
  'sacrifice': '犧牲',
  'sadness': '悲傷',
  'safety': '安全',
  'satellite': '隨從',
  'scandal': '醜聞',
  'scholarship': '學識',
  'science': '學問',
  'secret service': '密勤',
  'secrets': '秘密',
  'sects': '教派',
  'security': '保障',
  'seduction': '誘騙',
  'self-confidence': '自信',
  'selfishness': '自私',
  'senator': '議員',
  'sentence': '判決',
  'sentiment': '情感',
  'separation': '分離',
  'serviceable': '有用',
  'serviceableness': '助益',
  'servitude': '奴役',
  'sham fight': '佯戰',
  'shame': '羞恥',
  'sickness': '疾病',
  'silence': '沉默',
  'simplicity': '純樸',
  'simulated enjoyment': '偽裝的歡愉',
  'skill': '技藝',
  'skilled labour': '技術勞動',
  'slander': '誹謗',
  'sleep': '睡眠',
  'snares of enemies': '敵人的羅網',
  'society': '社交',
  'solace': '慰藉',
  'solitude': '孤獨',
  'somnambulism': '夢遊',
  'sorrow': '悲傷',
  'source': '源頭',
  'speedy intelligence': '迅捷的消息',
  'spying': '窺探',
  'stability': '穩固',
  'stagnation': '停滯',
  'sterility': '不孕',
  'stingings of conscience': '良心的刺痛',
  'stipendiary': '領餉的人',
  'struggle with a rival': '與對手的爭鬥',
  'study': '鑽研',
  'subtlety': '狡黠',
  'success': '成功',
  'success in enterprise': '事業成功',
  'success in financial speculation': '投機獲利',
  'success in these paths': '此道之成功',
  'succour': '救援',
  'superfluity': '過剩',
  'surface knowledge': '皮相之知',
  'surprise': '意外',
  'suspense': '懸而未決',
  'suspension': '中止',
  'suspicion': '猜疑',
  'swiftness': '迅捷',
  'swindling': '詐財',
  'sympathy': '投契',
  'taste': '品味',
  'tears': '淚水',
  'tenacity': '堅忍',
  'terror': '恐怖',
  'testament': '遺囑',
  'the arrows of love': '愛之箭',
  'the crowd': '群眾',
  'the crown of hope': '希望之冠',
  'the end of troubles': '苦難的終結',
  'the future': '未來',
  'the mortification': '羞辱',
  'the priesthood': '神職',
  'the querent': '問卜者',
  'the querent herself': '問卜者本人（女性）',
  'the surety of possessions': '財產的保障',
  'the town': '城鎮',
  'the unknown': '未知',
  'the vantage position': '有利之位',
  'theft': '竊盜',
  'things connected with churches': '與教會相關之事',
  'things that have vanished': '已消逝之物',
  'timidity': '膽怯',
  'toil and disappointment': '勞苦與失望',
  'tomb and coffin': '墳墓與棺木',
  'trade': '貿易',
  'transmission': '傳遞',
  'treachery': '背叛',
  'trials': '試煉',
  'trials overcome': '試煉已克',
  'trickery': '詭計',
  'triumph': '凱旋',
  'triumph of force': '武力的勝利',
  'trouble': '煩憂',
  'troubles in love': '感情上的麻煩',
  'truth': '真理',
  'tyranny': '暴政',
  'ugliness': '醜陋',
  'unalterable law': '不可更改的法則',
  'unexpected change of position': '地位的意外變動',
  'unexpected good fortune': '意外的好運',
  'unfavourable issue of lawsuit': '訴訟結果不利',
  'unfavourable news': '不利的消息',
  'unfortunate combinations': '不幸的組合',
  'union': '結合',
  'unprepared state': '未備之態',
  'unreasoned caution': '無端戒慎',
  'useful discoveries': '有用的發現',
  'usury': '高利貸',
  'utility': '效用',
  'vacillation': '猶疑不定',
  'vain hopes': '徒然的希望',
  'valour': '英勇',
  'vanity': '虛榮',
  'vehemence': '激烈',
  'vengeance': '復仇',
  'vice': '惡習',
  'victory': '勝利',
  'vigilance': '警覺',
  'violence': '暴力',
  'violent chagrin': '劇烈懊惱',
  'virtue': '美德',
  'voided ambition': '落空的野心',
  'voided project': '落空的計畫',
  'voyage': '航程',
  'war': '戰爭',
  'war of trade': '商戰',
  'weakness': '軟弱',
  'wealth and honour': '財富與榮譽',
  'weariness': '倦怠',
  'what is unforeseen': '未預見之事',
  'widowhood': '孀居',
  'will': '意志',
  'wisdom': '智慧',
  'wise administration': '善治',
  'wish': '心願',
  'wonder': '驚奇',
  'wordy strife': '口舌之爭',
  'work': '工作',
  'wrath': '震怒',
};
export function waiteTermZh(en) {
  const zh = waiteZh[en];
  return zh ? zh : null;
}
