const waiteZh = {
  'a bad card': '不吉的牌',
  'a bad man': '心術不正的男人',
  'a bad woman, with ill-will towards the querent': '心術不正、對問卜者懷有惡意的女人',
  'a brave man out of employment': '失業的勇者',
  'a card of bad omen': '凶兆之牌',
  'a caution to put an end to a ruinous lawsuit': '告誡及早結束耗損家產的訴訟',
  'a certain clouded joy': '蒙上陰影的喜悅',
  'a certain success following wise administration': '妥善管理之後必有成果',
  'a certain success in business': '生意上一定的成功',
  'a check on the querent\'s ambition': '問卜者的野心受到阻遏',
  'a child': '孩子',
  'a country life after a competence has been secured': '攢足家底後過鄉間生活',
  'a dangerous rival': '危險的對手',
  'a dark child': '深髮的孩子',
  'a dark girl': '深髮女孩',
  'a dark woman': '深髮女子',
  'a dark young man': '深髮青年',
  'a dark youth': '深髮少年',
  'a good card': '吉利的牌',
  'a good harvest': '豐收',
  'a good marriage': '良好的婚姻',
  'a great person': '顯貴人物',
  'a happy marriage': '美滿的婚姻',
  'a lawyer': '律師',
  'a lover': '愛人',
  'a married woman will have beautiful children': '已婚女子將有漂亮的孩子',
  'a meeting with one whom the querent has compromised': '與曾被問卜者連累的人相遇',
  'a merchant': '商人',
  'a nun': '修女',
  'a perfect spouse and a good mother': '完美的配偶與好母親',
  'a plan that may fail': '可能失敗的計畫',
  'a postman': '郵差',
  'a priest': '神父',
  'a proposal of love': '求愛',
  'a rather dark man': '髮色偏深的男子',
  'a rich marriage for a man and a distinguished one for a woman': '對男性是富裕的婚姻，對女性是體面的婚姻',
  'a serious quarrel': '嚴重的爭吵',
  'a share in the finding of treasure': '分得一份尋獲的財寶',
  'a sign of birth': '生育的徵兆',
  'a sign of sorrow and mourning': '悲傷與服喪的徵兆',
  'a soldier': '軍人',
  'a studious youth': '好學的青年',
  'a very good card': '極吉的牌',
  'a victor triumphing': '凱旋的勝利者',
  'a visit from a friend': '朋友來訪',
  'a widow': '寡婦',
  'a woman of equivocal character': '品行可疑的女子',
  'a young lady may be betrayed by a friend': '年輕女子可能遭朋友背叛',
  'a young lady may expect trivial disappointments': '年輕女子會遇到一些小失望',
  'a young man in business who has relations with the querent': '與問卜者有往來的年輕生意人',
  'a young man who is unfortunate in love': '情場失意的青年',
  'a young officer or soldier': '年輕軍官或士兵',
  'abandonment': '遺棄',
  'able co-operation in business': '生意上得力的合作',
  'abode': '居所',
  'absence': '不在身邊',
  'abundance': '豐盛',
  'abuse of power': '濫用權力',
  'accident': '意外',
  'accommodation': '調和',
  'accomplishment': '達成',
  'achievement': '成就',
  'action': '行動',
  'activity in undertakings': '事業上積極活躍',
  'address': '機敏手腕',
  'adjournment': '延期',
  'advances': '示好接近',
  'advantage': '好處',
  'adversity': '逆境',
  'advice that should be followed': '應當聽從的忠告',
  'affection': '關愛',
  'affinities': '情投意合',
  'affinity': '契合',
  'affliction': '苦難',
  'agitation': '騷動',
  'aid': '援助',
  'alienation': '疏離',
  'alliance': '結盟',
  'alliances': '聯姻',
  'altercation': '爭辯',
  'an attack on the fortune of the querent': '問卜者的財產受到侵犯',
  'an ecclesiastic': '教士',
  'an envoy': '使者',
  'an illness': '疾病',
  'an indiscreet person will pry into the querent\'s secrets': '有不知分寸的人會窺探問卜者的祕密',
  'an occasion which may be fortunate or otherwise': '一個可能是福也可能是禍的時機',
  'an old and vicious man': '年老而心術不正的男人',
  'an useful man': '有用的人',
  'ancestry': '血統家世',
  'anecdotes': '軼聞',
  'announcements': '宣告',
  'annoyance': '煩擾',
  'anxiety': '焦慮',
  'anxiety regarding money which it may be proposed to lend': '為別人想借的錢擔憂',
  'any kind of success': '任何形式的成功',
  'apathy': '冷漠',
  'application': '勤勉',
  'apprehension': '憂懼',
  'approach': '接近',
  'archives': '檔案文書',
  'aristocracy': '貴族',
  'arrival': '到來',
  'arrogance': '傲慢',
  'arrows of jealousy': '嫉妒之箭',
  'art and science': '藝術與學問',
  'artifice': '巧計',
  'assured success': '篤定的成功',
  'astonishing news': '驚人的消息',
  'attachment': '依戀',
  'attempt': '嘗試',
  'attention': '關注',
  'attraction': '吸引',
  'augmentation': '增長',
  'austere, yet tolerant': '嚴峻卻寬容',
  'authority': '權威',
  'authority and will': '權威與意志',
  'avarice': '貪婪',
  'aversion': '厭惡',
  'babbling': '多嘴',
  'bad faith': '背信',
  'bad intelligence': '壞音訊',
  'bad news': '壞消息',
  'bad omen': '凶兆',
  'bale': '禍害',
  'barbarity': '野蠻殘暴',
  'barter': '交易',
  'beauty': '美',
  'beginning': '開端',
  'benevolence': '仁慈',
  'bewrayment': '洩露',
  'bias': '偏頗',
  'bigotry': '偏執',
  'birth': '誕生',
  'blended pleasure': '苦樂參半',
  'blindness': '盲目',
  'body politic': '國家整體',
  'bravery': '勇敢',
  'burial and obsequies': '埋葬與喪儀',
  'business': '生意',
  'business and normal intellectual aptitude': '經商與一般的智力才能',
  'but none of these are permanent': '但都不長久',
  'calamities of all kinds': '各種災禍',
  'calamity': '災厄',
  'calumny': '誹謗',
  'capacity': '才幹',
  'captivity': '受縛',
  'carelessness': '粗心大意',
  'censure': '譴責',
  'certitude': '確信',
  'chagrin': '懊惱',
  'chance': '機運',
  'change of place': '遷往他處',
  'change of position': '地位變動',
  'change of residence': '遷居',
  'chaos': '混亂',
  'chaste': '貞潔',
  'childbirth': '分娩',
  'circumspection': '思慮周全',
  'clandestine': '隱密',
  'cleaving to that which one has': '緊抓已有的東西',
  'collaboration will favour enterprise': '合作有利於事業',
  'comfortable material conditions': '優渥的物質條件',
  'command': '統率',
  'commerce': '商貿',
  'commission': '委託',
  'commissionary': '受託者',
  'compassion': '慈悲',
  'competing interests': '利益衝突',
  'competition': '競爭',
  'complete success and honours': '圓滿成功與榮譽',
  'composition': '文書撰寫',
  'concealment': '隱瞞',
  'conceit': '自負',
  'conception': '受孕',
  'concord': '和睦',
  'concord in a state of arms': '武裝中的和睦',
  'concordance': '相合一致',
  'confession': '坦白',
  'confidence': '信心',
  'conflict': '衝突',
  'conformity': '一致',
  'confusion': '迷亂',
  'confusion to enemies': '敵人潰亂',
  'conquest': '征服',
  'conquest of fortune by reason': '憑理智贏得財富',
  'consanguinity': '血親',
  'considerable loss': '重大損失',
  'consolation': '慰藉',
  'content': '心滿意足',
  'contentment': '滿足',
  'contradiction': '矛盾',
  'contrarieties': '種種不順',
  'contrarieties of all kinds': '各種不順',
  'conviction': '堅定信念',
  'corruption': '腐敗',
  'counsel': '忠告',
  'country life': '鄉間生活',
  'countryman': '鄉間男子',
  'countrywoman': '鄉間女子',
  'courage': '勇氣',
  'craftsmanship': '工藝技藝',
  'creation': '創造',
  'creative intelligence': '富創意的才智',
  'credit': '信譽',
  'crisis': '危機',
  'cruelty': '殘酷',
  'cupidity': '貪念',
  'cure': '痊癒',
  'danger': '危險',
  'dark girl': '深髮女孩',
  'dark man': '深髮男子',
  'dark woman': '深髮女子',
  'dark young man': '深髮青年',
  'darkness': '黑暗',
  'dealings with rogues': '與無賴往來',
  'death': '死亡',
  'decadence': '頹敗',
  'deceit': '欺瞞',
  'deception': '欺騙',
  'decision': '決斷',
  'declaration': '表白',
  'defeat': '挫敗',
  'defence': '防禦',
  'degradation': '淪落',
  'delay': '延遲',
  'deliberation': '審慎斟酌',
  'delirium': '譫妄',
  'demeanour': '舉止儀態',
  'departure': '離去',
  'departure of a relative': '親人離去',
  'depends on neighbouring cards': '視鄰近的牌而定',
  'depravity': '敗德',
  'design': '意圖',
  'desire': '慾望',
  'desolation': '淒涼荒蕪',
  'despair': '絕望',
  'despotism': '專制',
  'destiny': '命運',
  'destitution': '赤貧',
  'destruction': '毀滅',
  'determination': '決心',
  'devoted woman': '忠貞的女子',
  'difficulties': '重重困難',
  'difficulties and contradictions': '困難與矛盾',
  'difficulty': '困難',
  'diplomacy': '外交手腕',
  'disappointment': '失望',
  'disaster': '災難',
  'discernment': '洞察力',
  'discord': '不和',
  'discouragement': '氣餒',
  'discovery': '發現',
  'discussion': '討論',
  'disease': '疾病',
  'disgrace': '蒙羞',
  'disguise': '偽裝',
  'disgust': '反感',
  'dishonest': '不誠實',
  'dishonour': '名譽掃地',
  'disloyalty': '不忠',
  'disorder': '失序',
  'dispatch': '速辦',
  'dispersion': '離散',
  'dispute': '爭執',
  'dispute with an imbecile person': '與愚人爭執',
  'disputes': '爭端',
  'disquiet': '不安',
  'dissimulation': '佯裝',
  'dissipation': '浪蕩',
  'distinguished woman but one not to be trusted': '出眾卻不可信的女子',
  'distraction': '心神渙散',
  'distress': '困厄',
  'distribution': '分配',
  'disunion': '離心',
  'divination': '占卜',
  'divinity': '神學',
  'division': '分裂',
  'doctor': '醫生',
  'domestic disputes': '家庭爭執',
  'domestic disputes for a married person': '已婚者的家庭爭執',
  'domestic harvest-home': '家中的豐收慶典',
  'double-dealing man': '兩面派的男人',
  'doubt': '疑慮',
  'dowry': '嫁妝',
  'duplicity': '表裡不一',
  'economical': '節儉',
  'economy': '節約',
  'ecstasy': '狂喜',
  'effort': '努力',
  'elevation': '高升',
  'embarrassments': '窘境',
  'embellishment': '潤飾',
  'embroilment': '糾葛',
  'emigration': '移居',
  'emotion': '激動',
  'employment': '職務',
  'enchantment': '著迷',
  'end': '終結',
  'end of the business': '事情了結',
  'energy': '精力',
  'enforced gaiety': '強顏歡笑',
  'enjoyment': '享樂',
  'enmity': '敵意',
  'enterprise': '事業',
  'envoy': '使者',
  'envy': '眼紅',
  'equipoise': '均衡',
  'equity': '公允',
  'error': '謬誤',
  'established strength': '穩固的實力',
  'even deceit and infidelity': '甚至是欺瞞與不忠',
  'evil': '邪惡',
  'evil fatality': '凶惡的宿命',
  'evil intention': '居心不良',
  'evil news': '凶訊',
  'exaction': '勒索',
  'examination': '審查',
  'excess in physical enjoyment': '肉體享樂過度',
  'excessive severity': '過度嚴苛',
  'executive': '執行權',
  'exile': '流放',
  'expectation crowned with its own desire': '期望如願以償',
  'expedient': '權宜之計',
  'expedition': '迅速',
  'extraction': '出身',
  'extraordinary efforts': '非凡的努力',
  'extravagance': '荒唐',
  'failure': '失敗',
  'failure of marriage projects': '婚事告吹',
  'fair child': '淺髮的孩子',
  'fair man': '淺髮男子',
  'fair woman': '淺髮女子',
  'fair young man': '淺髮青年',
  'fairy favours': '仙子的恩寵',
  'faithful': '忠實',
  'fall': '衰落',
  'false projects': '不實的計畫',
  'false-seeming': '虛有其表',
  'falsehood': '謊言',
  'family': '家族',
  'family intelligence': '家中的消息',
  'family matters': '家務事',
  'fatality': '宿命',
  'favour': '恩寵',
  'favourable in things of pleasure and business, as well as love': '在享樂、生意與愛情上都有利',
  'fear': '恐懼',
  'feasting': '宴飲',
  'felicity': '福樂',
  'felicity hereof': '由此而來的福樂',
  'female sadness and embarrassment': '女子的憂傷與窘迫',
  'fertility': '豐饒',
  'fixity': '固著',
  'flight': '出走',
  'folly': '愚行',
  'foolish designs': '愚蠢的打算',
  'for a bachelor, pleasant news from a lady': '（對單身男子）來自女士的好消息',
  'for a male querent, a good marriage and one beyond his expectations': '（問卜者為男性時）好婚姻，且超乎預期',
  'for a woman, marriage, but probably frustrated': '（問卜者為女性時）婚事，但多半受阻',
  'for a woman, scandal spread in her respect': '（問卜者為女性時）有關她的醜聞流傳',
  'for a woman, struggle with a rival, who will be conquered': '（問卜者為女性時）與情敵相爭，終將勝出',
  'for a woman, the flight of her lover': '（問卜者為女性時）情人離她而去',
  'force': '力量',
  'fortunate marriage': '良緣',
  'fortune': '財運',
  'fraud': '詐欺',
  'frenzy': '狂亂',
  'friend': '朋友',
  'friendly': '友善',
  'friendship': '友誼',
  'frugality': '節儉',
  'fruitfulness': '多產',
  'fulfilment': '圓滿',
  'fulfilment of deferred hope': '延宕的希望終獲實現',
  'gaiety': '歡樂',
  'gain': '獲利',
  'games of hazard': '賭局',
  'generally favourable': '大體有利',
  'generally married': '多半已婚',
  'generosity': '慷慨',
  'gift': '贈禮',
  'gifts': '餽贈',
  'gifts for a lady': '給女士的禮物',
  'giving joy': '帶來喜樂',
  'glory': '榮耀',
  'gold': '黃金',
  'good': '良善',
  'good advice': '良言忠告',
  'good advice, probably neglected': '良言忠告，多半被忽略',
  'good augury': '吉兆',
  'good business': '好生意',
  'good ground for suspicion against a doubtful person': '懷疑可疑之人有充分根據',
  'good understanding': '融洽相知',
  'good woman': '良善女子',
  'good-will towards the querent, but without the opportunity to exercise it': '對問卜者有善意，卻沒有機會施展',
  'good, but severe': '良善但嚴厲',
  'gratification': '欣慰',
  'great force, in love as well as in hatred': '強大的力量，愛恨皆然',
  'great haste': '急速',
  'great hope': '滿懷希望',
  'great joy': '大喜',
  'great news': '重大消息',
  'great prosperity or great misery': '大富大貴或大災大難',
  'great riches': '鉅富',
  'handwriting': '手寫文書',
  'happiness': '幸福',
  'happy issue': '美好結局',
  'harmony': '和諧',
  'haughtiness': '倨傲',
  'haven of refuge': '避風港',
  'healing': '療癒',
  'hermit\'s repose': '隱者般的休憩',
  'heroic action predicted for soldier': '預示軍人將有英勇之舉',
  'hidden enemies': '暗中的敵人',
  'hindrances': '阻礙',
  'holy table': '聖餐桌',
  'honest': '誠實',
  'honest and conscientious': '誠實盡責',
  'honesty': '誠實正直',
  'honour': '榮譽',
  'honourable': '可敬',
  'hope': '希望',
  'hope and bright prospects': '希望與光明的前景',
  'hope destroyed': '希望破滅',
  'house of the false heart': '虛情的居所',
  'house of the true heart': '真心的居所',
  'husband': '丈夫',
  'hypocrisy pretending to help': '假意幫忙的偽善',
  'idea': '想法',
  'idleness': '怠惰',
  'if for a man, celebrity for his eldest son': '（問卜者為男性時）長子揚名',
  'ignorance': '無知',
  'ill-will on the part of a man of position': '有地位男子的惡意',
  'illusion': '幻象',
  'images of reflection': '映照出的意象',
  'imaginary vexations': '臆想的煩惱',
  'imagination': '想像',
  'imitation': '仿效',
  'immaturity': '不成熟',
  'impatience': '不耐煩',
  'imperfections': '缺陷',
  'imposture': '招搖撞騙',
  'impotence': '無能為力',
  'imprisonment': '囚禁',
  'improved position for a lady\'s future husband': '女士的未婚夫地位提升',
  'imprudence': '輕率',
  'incapacity': '無能',
  'incitement': '鼓動',
  'inclination': '傾心',
  'inconstancy': '善變',
  'increase': '增益',
  'indecision': '優柔寡斷',
  'indefinite delay': '無限期延宕',
  'indigence': '貧困',
  'indignation': '憤慨',
  'inertia': '惰性',
  'infamy': '惡名',
  'inflexible will': '不可動搖的意志',
  'influential protection for a man in search of help': '求助的男子得到有權勢者的庇護',
  'ingenuity': '巧思',
  'inheritance': '繼承',
  'inheritance to fall in quickly': '遺產即將到手',
  'initiative': '主動',
  'injustice': '不公',
  'innocence': '天真無邪',
  'inspiration': '靈感',
  'instability': '不穩定',
  'instruction': '教誨',
  'interest': '利益',
  'internal dispute': '內部爭執',
  'interruption': '中斷',
  'intimacy': '親密',
  'intoxication': '沉醉',
  'intrigues': '陰謀',
  'intuition': '直覺',
  'invention': '發明',
  'invitation': '邀約',
  'irregularity': '行為不檢',
  'jealousy': '嫉妒',
  'journey by water': '水路之旅',
  'joy': '喜悅',
  'judgment': '判斷',
  'law': '法律',
  'law and art': '法律與藝術',
  'law in all its departments': '法律的各個領域',
  'legacies': '遺產',
  'legacy': '遺贈',
  'legal complications': '法律糾紛',
  'length of days': '長壽',
  'lesser degrees of deception and error': '程度較輕的欺騙與謬誤',
  'lethargy': '昏沉',
  'letters of exchange': '匯票',
  'liberality': '出手闊綽',
  'liberty': '自由',
  'light': '光',
  'literal sense': '字面意義',
  'litigation': '訴訟',
  'looking back': '回顧',
  'loss': '損失',
  'love': '愛',
  'love and lovers': '愛情與戀人',
  'love of money': '愛財',
  'loving': '深情',
  'loving intelligence': '慈愛的慧心',
  'loyalty': '忠誠',
  'luck': '運氣',
  'luxury': '奢華',
  'magnanimity': '寬宏',
  'magnificence': '華美',
  'magus': '魔法師',
  'malice': '惡意',
  'man of arms': '武人',
  'man of business': '生意人',
  'management': '管理',
  'mania': '狂躁',
  'many contrarieties': '諸多不順',
  'marriage': '婚姻',
  'marriage broken off': '婚約破裂',
  'marriage frustrated': '婚事受挫',
  'marriage with a fair woman': '與淺髮女子結婚',
  'marriage, but not without bitterness or frustration': '婚姻，但難免苦澀或挫折',
  'master': '師傅',
  'material happiness': '物質的幸福',
  'material trouble': '物質上的困境',
  'mathematical gifts': '數學天分',
  'mediocrity': '平庸',
  'meditation': '冥想',
  'memories': '回憶',
  'mental alienation': '精神錯亂',
  'mental disease': '精神疾病',
  'mercy and goodness': '慈悲與良善',
  'message': '訊息',
  'messages and the bringer thereof': '訊息與送信的人',
  'métier': '本行',
  'mildness': '溫和',
  'militant intelligence': '尚武的才智',
  'miscarriage': '流產',
  'misery': '悲慘',
  'mistakes': '過失',
  'mistress': '女情人',
  'mistrust': '不信任',
  'moderation': '節制',
  'modesty': '謙遜',
  'money': '金錢',
  'moral or physical ardour': '精神或肉體的熱切',
  'more evil side of these qualities': '這些特質較壞的一面',
  'mortality': '死亡',
  'mortification': '屈辱',
  'mourning': '哀悼',
  'movement': '行動',
  'multiplicity': '繁衍',
  'mutation': '變動',
  'mystery': '奧祕',
  'negligence': '怠忽',
  'negotiations': '談判',
  'new environment': '新環境',
  'new instruction': '新的教導',
  'new knowledge': '新知',
  'new relations': '新的人際關係',
  'news': '消息',
  'news and messages in writing': '書面的消息與訊息',
  'news concerning an unexpected heritage': '意外遺產的消息',
  'nobility': '高貴',
  'nourishment': '滋養',
  'novelty': '新鮮事',
  'now is the accepted time': '正是時候',
  'nullity': '虛無',
  'obliging': '樂於助人',
  'observation': '觀察',
  'obstacles': '障礙',
  'obstacles of all kinds': '各種阻礙',
  'obstruction': '阻撓',
  'occult forces': '隱祕力量',
  'of good augury for military men': '對軍人是吉兆',
  'offices of the crown': '官職',
  'opposition': '反對',
  'oppression': '壓迫',
  'opulence': '豐裕',
  'origin': '起源',
  'outcome': '結果',
  'over-kindness': '過度仁慈',
  'overseeing': '監督',
  'pain': '痛苦',
  'passion': '激情',
  'patrimony': '祖產',
  'peace': '平安',
  'pension': '年金',
  'perdition': '沉淪',
  'perfect contentment': '全然的滿足',
  'perfect satisfaction': '完全的滿意',
  'perfection and merriment': '圓滿與歡愉',
  'perfection of human love and friendship': '人間愛情與友誼的圓滿',
  'perfidy': '背信棄義',
  'peril': '危難',
  'permanence': '恆常',
  'perplexity': '困惑',
  'perverse woman': '乖戾的女人',
  'perversity': '乖戾',
  'petrifaction': '僵化',
  'pettiness': '格局狹小',
  'physical bien-être': '身體安適',
  'physical suffering': '肉體的痛苦',
  'physician': '醫者',
  'pillage': '劫掠',
  'placidity': '過於安逸',
  'pleasant memories': '愉快的回憶',
  'pleasure': '愉悅',
  'policy': '權謀',
  'power': '權力',
  'power and authority': '權力與權威',
  'power in trammels': '受縛的力量',
  'precaution': '防範',
  'presage': '預兆',
  'present prosperity': '眼前的興旺',
  'presentiment': '預感',
  'presents': '禮物',
  'presents from a rich relative': '富有親戚的餽贈',
  'presumption': '狂妄',
  'principle': '本源',
  'privation': '匱乏',
  'probity': '廉正',
  'prodigality': '揮霍',
  'professor': '教授',
  'profit': '收益',
  'profligacy': '放蕩',
  'project': '計畫',
  'prompt fulfilment of what is presaged by neighbouring cards': '鄰近的牌所預示的事很快實現',
  'prophecy': '預言',
  'proposition': '提議',
  'prosperity': '興旺',
  'protection': '保護',
  'providence': '天佑',
  'prudence': '謹慎',
  'prudery': '假正經',
  'public rejoicings': '公眾的歡慶',
  'publicity': '公開',
  'puerility': '幼稚',
  'purgation': '滌淨',
  'pusillanimity': '怯懦',
  'quarrel': '爭吵',
  'quarrelling': '爭吵不休',
  'quarrels': '口角',
  'quarrels may be turned to advantage': '爭吵可以轉為有利',
  'ravage': '蹂躪',
  'realization': '實現',
  'realizing intelligence': '務實成事的才智',
  'reason': '理性',
  'reasonable fear': '合理的擔憂',
  'recompense': '報償',
  'recreation and its connexions': '娛樂消遣及相關之事',
  'rectitude': '正直不阿',
  'reflection': '沉思',
  'religions': '宗教',
  'removal': '遷移',
  'renewal': '重生',
  'renown': '聲望',
  'repose': '安歇',
  'repose of the entire heart': '全心的安寧',
  'repose of the false heart': '虛情假意的安逸',
  'represents house or dwelling': '代表房屋或住所',
  'resistance': '抵抗',
  'resolve': '果決',
  'responsibility': '責任',
  'responsible': '負責任的',
  'retreat': '退隱',
  'return': '歸返',
  'return of some relative who has not been seen for long': '久未見面的親人歸來',
  'revocation': '撤銷',
  'revolution': '劇變',
  'rich and happy marriage for a young man': '青年男子富裕美滿的婚姻',
  'riches': '財富',
  'rightness': '正當',
  'riot': '暴亂',
  'robbery': '搶劫',
  'roguery': '奸詐行徑',
  'route': '路線',
  'ruin': '破滅',
  'rule': '規範',
  'rupture': '決裂',
  'sacrifice': '犧牲',
  'sadness': '悲傷',
  'safety': '安全',
  'satellite': '隨從',
  'satisfaction for the querent': '問卜者稱心如意',
  'scandal': '醜聞',
  'scholarship': '學識',
  'science': '學問',
  'secret service': '祕密任務',
  'secrets': '祕密',
  'sects': '教派',
  'security': '安穩',
  'seduction': '誘騙',
  'self-confidence': '自信',
  'selfishness': '自私',
  'senator': '議員',
  'sentence': '判決',
  'sentiment': '情感',
  'separation': '分離',
  'servants may lose the confidence of their masters': '僕人可能失去主人的信任',
  'serviceable': '肯幫忙',
  'serviceableness': '樂於效勞',
  'servitude': '奴役',
  'sham fight': '佯戰',
  'shame': '羞恥',
  'sickness': '疾病',
  'silence': '沉默',
  'simplicity': '頭腦簡單',
  'simulated enjoyment': '偽裝的歡愉',
  'skill': '技巧',
  'skill in craft and business': '手藝與生意上的技巧',
  'skilled labour': '技術勞動',
  'slander': '中傷',
  'sleep': '睡眠',
  'snares of enemies': '敵人的陷阱',
  'society': '社交',
  'solace': '撫慰',
  'solitude': '孤獨',
  'something remains over': '仍有所剩',
  'somnambulism': '夢遊',
  'sorrow': '悲傷',
  'source': '源頭',
  'speedy intelligence': '快速到來的消息',
  'spying': '窺探',
  'stability': '穩定',
  'stagnation': '停滯',
  'sterility': '不孕',
  'stingings of conscience': '良心不安',
  'stipendiary': '領薪之人',
  'strength in opposition': '頑強抵抗的力量',
  'strenuous competition and struggle': '激烈的競爭與奮鬥',
  'study': '鑽研',
  'subtlety': '狡黠',
  'success': '成功',
  'success in enterprise': '事業成功',
  'success in financial speculation': '投機獲利',
  'success in these paths': '在這些方面的成功',
  'success, if accompanied by the three of cups': '若與聖杯三同時出現，則成功',
  'succour': '救援',
  'superfluity': '過剩',
  'surface knowledge': '一知半解',
  'surprise': '驚訝',
  'suspense': '懸而未決',
  'suspension': '中止',
  'suspension or cessation of adversity': '逆境暫停或終止',
  'suspicion': '猜疑',
  'swiftness': '迅捷',
  'swindling': '詐財',
  'sympathy': '共鳴',
  'taste': '品味',
  'tears': '淚水',
  'tenacity': '堅韌',
  'tenderness': '溫柔',
  'terror': '恐怖',
  'testament': '遺囑',
  'that which is predestined but is not for this reason evil': '命中注定，卻不因此就是壞事',
  'that which will come to pass presently': '即將發生的事',
  'the abode of a family': '家族的宅第',
  'the arrows of love': '愛神之箭',
  'the battle of life': '人生的奮鬥',
  'the crowd': '群眾',
  'the crown of hope': '希望的桂冠',
  'the decline of a matter': '事情走下坡',
  'the end of troubles': '麻煩告終',
  'the evil side of wealth': '財富的陰暗面',
  'the excessive degree in everything': '凡事走向極端',
  'the future': '未來',
  'the future as yet unrevealed': '尚未揭曉的未來',
  'the gift of vision': '洞見的天賦',
  'the ingenious mind turned to cunning and intrigue': '聰明才智用在狡詐與算計上',
  'the interrelation of the sexes': '兩性之間的關係',
  'the loss of a benefactor': '失去恩人',
  'the man to whom the querent has recourse': '問卜者求助的男子',
  'the most favourable of all cards': '全副牌中最吉的一張',
  'the past': '過去',
  'the pleasures of the senses': '感官的享樂',
  'the present must not be relied on': '眼前的情勢靠不住',
  'the priest who will marry the querent': '將為問卜者證婚的神父',
  'the priesthood': '神職人員',
  'the querent herself, if female': '問卜者本人（問卜者為女性時）',
  'the querent will be compromised in a matter of money-lending': '問卜者將因借貸之事受牽連',
  'the querent, if male': '問卜者本人（問卜者為男性時）',
  'the same': '同正位',
  'the same in a lesser degree': '同正位，程度較輕',
  'the same in a lesser sense': '同正位，程度較輕',
  'the same, but the results are disastrous': '同正位，但結果是災難',
  'the surety of possessions': '穩固的財產',
  'the town, village or country inhabited by the querent': '問卜者居住的城鎮、村莊或鄉間',
  'the unknown': '未知',
  'the unravelling of involved matters': '複雜之事得以理清',
  'the vantage position': '居高臨下的優勢',
  'the voyage will be pleasant': '旅途愉快',
  'the woman who interests the querent, if male': '吸引問卜者的女子（問卜者為男性時）',
  'theft': '竊盜',
  'things connected with churches': '與教會相關之事',
  'things that have vanished': '已逝的事物',
  'timidity': '膽怯',
  'to perish': '覆滅',
  'toil and disappointment': '勞苦與失望',
  'tomb and coffin': '墳墓與棺木',
  'total loss through lawsuit': '因訴訟而全盤皆輸',
  'trade': '貿易',
  'transmission': '傳承',
  'treachery': '背叛',
  'treason': '出賣',
  'treason on the part of friends': '朋友的出賣',
  'trials': '試煉',
  'trials overcome': '克服考驗',
  'trickery': '詭計',
  'triumph': '凱旋',
  'triumph of force': '力量的勝利',
  'triumph of the deserving side in law': '訴訟中有理的一方勝訴',
  'trouble': '紛擾',
  'troubles are more imaginary than real': '煩惱多半是想像出來的',
  'troubles in love': '感情上的麻煩',
  'truth': '真相',
  'tyranny': '暴虐',
  'ugliness': '醜陋',
  'unalterable law': '不可更改的法則',
  'unexpected advancement for military man': '軍人意外升遷',
  'unexpected change of position': '地位的意外變動',
  'unexpected good fortune': '意外的好運',
  'unexpected money': '意外之財',
  'unfavourable issue of lawsuit': '訴訟結果不利',
  'unfavourable news': '不利的消息',
  'unforeseen catastrophe': '突如其來的災變',
  'unfortunate combinations': '不利的結合',
  'union': '結合',
  'unprepared state': '措手不及',
  'unreasoned caution': '無端戒慎',
  'useful discoveries': '有用的發現',
  'usury': '高利貸',
  'utility': '實用',
  'vacillation': '猶疑不定',
  'vain hopes': '落空的希望',
  'valour': '英勇',
  'vanity': '虛榮',
  'vehemence': '激烈',
  'vengeance': '復仇',
  'vice': '惡習',
  'victory': '勝利',
  'victory and consequent fortune for a soldier in war': '軍人在戰爭中獲勝並因此得財',
  'vigilance': '警覺',
  'violence': '暴力',
  'violent chagrin': '極度懊惱',
  'virtue': '美德',
  'voided ambition': '落空的野心',
  'voided project': '落空的計畫',
  'voyage': '遠航',
  'war': '戰爭',
  'war of trade': '商戰',
  'way': '道路',
  'weakness': '軟弱',
  'wealth and honour': '財富與榮譽',
  'weariness': '厭倦',
  'what is unforeseen': '意料之外的事',
  'widowhood': '孀居',
  'wife': '妻子',
  'will': '意志',
  'wisdom': '智慧',
  'wise administration': '妥善管理',
  'wish': '心願',
  'wonder': '驚奇',
  'wordy strife': '口舌之爭',
  'work': '工作',
  'wrath': '憤怒',
  'young man of family in search of young lady': '出身良好、正在尋覓對象的青年',
};
// 同一個英文詞在不同牌上意思不同時，按牌覆寫（例：Five of Cups 逆位的 affinity 是「姻親」，Two of Cups 的是「契合」）。
const waiteZhByCard = {
  death: { 'corruption': '腐朽' },
  five_of_cups: { 'affinity': '姻親' },
  fool: { 'vanity': '虛妄' },
  magician: { 'subtlety': '細膩手法' },
  nine_of_cups: { 'truth': '真誠' },
  strength: { 'power': '力量' },
  three_of_pentacles: { 'trade': '行業' },
  wheel_of_fortune: { 'fortune': '時運' },
};
export function waiteTermZh(en, nameKey) {
  const byCard = nameKey ? waiteZhByCard[nameKey] : null;
  const zh = (byCard && byCard[en]) || waiteZh[en];
  return zh ? zh : null;
}
