export const waiteTerms = {
  ace_of_cups: { upright: ['joy', 'content', 'abode', 'nourishment', 'abundance', 'fertility', 'holy table', 'felicity hereof'], reversed: ['mutation', 'instability', 'revolution'] },
  ace_of_pentacles: { upright: ['perfect contentment', 'felicity', 'ecstasy', 'speedy intelligence', 'gold'], reversed: ['bad intelligence', 'great riches', 'comfortable material conditions'] },
  ace_of_swords: { upright: ['triumph', 'conquest', 'triumph of force'], reversed: ['conception', 'childbirth', 'augmentation', 'multiplicity'] },
  ace_of_wands: { upright: ['creation', 'invention', 'enterprise', 'principle', 'beginning', 'source', 'birth', 'family', 'origin', 'money', 'fortune', 'inheritance'], reversed: ['fall', 'decadence', 'ruin', 'perdition'] },
  chariot: { upright: ['succour', 'providence', 'war', 'triumph', 'presumption', 'vengeance', 'trouble'], reversed: ['riot', 'quarrel', 'dispute', 'litigation', 'defeat'] },
  death: { upright: ['end', 'mortality', 'destruction', 'corruption', 'many contrarieties', 'failure of marriage projects'], reversed: ['inertia', 'sleep', 'lethargy', 'petrifaction', 'somnambulism', 'hope destroyed'] },
  devil: { upright: ['ravage', 'violence', 'vehemence', 'extraordinary efforts', 'force', 'fatality'], reversed: ['evil fatality', 'weakness', 'pettiness', 'blindness'] },
  eight_of_cups: { upright: ['giving joy', 'mildness', 'timidity', 'honour', 'modesty'], reversed: ['great joy', 'happiness', 'feasting'] },
  eight_of_pentacles: { upright: ['work', 'employment', 'commission', 'craftsmanship'], reversed: ['voided ambition', 'vanity', 'cupidity', 'exaction', 'usury'] },
  eight_of_swords: { upright: ['bad news', 'violent chagrin', 'crisis', 'censure', 'power in trammels', 'conflict', 'calumny', 'sickness'], reversed: ['disquiet', 'difficulty', 'opposition', 'accident', 'treachery', 'what is unforeseen', 'fatality'] },
  eight_of_wands: { upright: ['activity in undertakings', 'swiftness', 'great haste', 'great hope', 'the arrows of love'], reversed: ['arrows of jealousy', 'internal dispute', 'stingings of conscience', 'quarrels'] },
  emperor: { upright: ['stability', 'power', 'protection', 'realization', 'a great person', 'aid', 'reason', 'conviction', 'authority and will'], reversed: ['benevolence', 'compassion', 'credit', 'confusion to enemies', 'obstruction', 'immaturity'] },
  empress: { upright: ['fruitfulness', 'action', 'initiative', 'length of days', 'the unknown', 'clandestine', 'difficulty', 'doubt', 'ignorance'], reversed: ['light', 'truth', 'public rejoicings', 'vacillation'] },
  five_of_cups: { upright: ['patrimony', 'transmission'], reversed: ['news', 'alliances', 'affinity', 'consanguinity', 'ancestry', 'return', 'false projects'] },
  five_of_pentacles: { upright: ['destitution', 'husband', 'friend', 'mistress', 'concordance', 'affinities'], reversed: ['disorder', 'chaos', 'ruin', 'discord', 'profligacy'] },
  five_of_swords: { upright: ['degradation', 'destruction', 'revocation', 'infamy', 'dishonour', 'loss'], reversed: ['burial and obsequies'] },
  five_of_wands: { upright: ['imitation', 'sham fight', 'gain', 'opulence'], reversed: ['litigation', 'disputes', 'trickery', 'contradiction'] },
  fool: { upright: ['folly', 'mania', 'extravagance', 'intoxication', 'delirium', 'frenzy', 'bewrayment'], reversed: ['negligence', 'absence', 'distribution', 'carelessness', 'apathy', 'nullity', 'vanity'] },
  four_of_cups: { upright: ['weariness', 'disgust', 'aversion', 'imaginary vexations'], reversed: ['novelty', 'presage', 'new instruction', 'new relations'] },
  four_of_pentacles: { upright: ['the surety of possessions', 'gift', 'legacy', 'inheritance'], reversed: ['suspense', 'delay', 'opposition'] },
  four_of_swords: { upright: ['vigilance', 'retreat', 'solitude', 'hermit\'s repose', 'exile', 'tomb and coffin'], reversed: ['wise administration', 'circumspection', 'economy', 'avarice', 'precaution', 'testament'] },
  four_of_wands: { upright: ['country life', 'haven of refuge', 'repose', 'concord', 'harmony', 'prosperity', 'peace'], reversed: ['increase', 'felicity', 'beauty', 'embellishment'] },
  hanged_man: { upright: ['wisdom', 'circumspection', 'discernment', 'trials', 'sacrifice', 'intuition', 'divination', 'prophecy'], reversed: ['selfishness', 'the crowd', 'body politic'] },
  hermit: { upright: ['prudence', 'circumspection', 'dissimulation', 'roguery', 'corruption'], reversed: ['concealment', 'disguise', 'policy', 'fear', 'unreasoned caution'] },
  hierophant: { upright: ['marriage', 'alliance', 'captivity', 'servitude', 'mercy and goodness', 'inspiration'], reversed: ['society', 'good understanding', 'concord', 'overkindness', 'weakness'] },
  high_priestess: { upright: ['secrets', 'mystery', 'the querent herself', 'silence', 'tenacity', 'wisdom', 'science'], reversed: ['passion', 'moral or physical ardour', 'conceit', 'surface knowledge'] },
  judgement: { upright: ['change of position', 'renewal', 'outcome'], reversed: ['weakness', 'pusillanimity', 'simplicity', 'deliberation', 'decision', 'sentence'] },
  justice: { upright: ['equity', 'rightness', 'probity', 'executive'], reversed: ['legal complications', 'bigotry', 'bias', 'excessive severity'] },
  king_of_cups: { upright: ['fair man', 'man of business', 'law', 'divinity', 'responsible', 'equity', 'art and science', 'law and art', 'creative intelligence'], reversed: ['dishonest', 'double-dealing man', 'roguery', 'exaction', 'injustice', 'vice', 'scandal', 'pillage', 'considerable loss'] },
  king_of_pentacles: { upright: ['valour', 'realizing intelligence', 'success in these paths'], reversed: ['vice', 'weakness', 'ugliness', 'perversity', 'corruption', 'peril'] },
  king_of_swords: { upright: ['command', 'authority', 'militant intelligence', 'law', 'offices of the crown'], reversed: ['cruelty', 'perversity', 'barbarity', 'perfidy', 'evil intention'] },
  king_of_wands: { upright: ['dark man', 'friendly', 'countryman', 'generally married', 'honest and conscientious'], reversed: ['good', 'austere'] },
  knight_of_cups: { upright: ['arrival', 'approach', 'advances', 'proposition', 'demeanour', 'invitation', 'incitement'], reversed: ['trickery', 'artifice', 'subtlety', 'swindling', 'duplicity', 'fraud'] },
  knight_of_pentacles: { upright: ['utility', 'serviceableness', 'interest', 'responsibility'], reversed: ['inertia', 'idleness', 'stagnation', 'placidity', 'discouragement', 'carelessness'] },
  knight_of_swords: { upright: ['skill', 'bravery', 'capacity', 'defence', 'address', 'enmity', 'wrath', 'war', 'destruction', 'opposition', 'resistance', 'ruin'], reversed: ['imprudence', 'incapacity', 'extravagance'] },
  knight_of_wands: { upright: ['departure', 'absence', 'flight', 'emigration', 'a dark young man', 'friendly', 'change of residence'], reversed: ['rupture', 'division', 'interruption', 'discord'] },
  lovers: { upright: ['attraction', 'love', 'beauty', 'trials overcome'], reversed: ['failure', 'foolish designs'] },
  magician: { upright: ['skill', 'diplomacy', 'address', 'subtlety', 'sickness', 'pain', 'loss', 'disaster', 'snares of enemies', 'self-confidence', 'will', 'the querent'], reversed: ['physician', 'magus', 'mental disease', 'disgrace', 'disquiet'] },
  moon: { upright: ['hidden enemies', 'danger', 'calumny', 'darkness', 'terror', 'deception', 'occult forces', 'error'], reversed: ['instability', 'inconstancy', 'silence'] },
  nine_of_cups: { upright: ['concord', 'contentment', 'physical bien-etre', 'victory', 'success', 'advantage'], reversed: ['truth', 'loyalty', 'liberty', 'imperfections'] },
  nine_of_pentacles: { upright: ['prudence', 'safety', 'success', 'accomplishment', 'certitude', 'discernment'], reversed: ['roguery', 'deception', 'voided project', 'bad faith'] },
  nine_of_swords: { upright: ['death', 'failure', 'miscarriage', 'delay', 'deception', 'disappointment', 'despair'], reversed: ['imprisonment', 'suspicion', 'doubt', 'reasonable fear', 'shame'] },
  nine_of_wands: { upright: ['delay', 'suspension', 'adjournment'], reversed: ['obstacles', 'adversity', 'calamity'] },
  page_of_cups: { upright: ['fair young man', 'a studious youth', 'news', 'message', 'application', 'reflection', 'meditation'], reversed: ['taste', 'inclination', 'attachment', 'seduction', 'deception', 'artifice'] },
  page_of_pentacles: { upright: ['application', 'study', 'scholarship', 'rule', 'management'], reversed: ['prodigality', 'dissipation', 'liberality', 'luxury', 'unfavourable news'] },
  page_of_swords: { upright: ['authority', 'overseeing', 'secret service', 'vigilance', 'spying', 'examination'], reversed: ['what is unforeseen', 'unprepared state'] },
  page_of_wands: { upright: ['dark young man', 'faithful', 'a lover', 'an envoy', 'a postman', 'a dangerous rival'], reversed: ['anecdotes', 'announcements', 'evil news'] },
  queen_of_cups: { upright: ['good', 'fair woman', 'honest', 'devoted woman', 'loving intelligence', 'success', 'happiness', 'pleasure', 'wisdom', 'virtue'], reversed: ['good woman', 'perverse woman', 'vice', 'dishonour', 'depravity'] },
  queen_of_pentacles: { upright: ['opulence', 'generosity', 'magnificence', 'security', 'liberty'], reversed: ['evil', 'suspicion', 'suspense', 'fear', 'mistrust'] },
  queen_of_swords: { upright: ['widowhood', 'female sadness and embarrassment', 'absence', 'sterility', 'mourning', 'privation', 'separation'], reversed: ['malice', 'bigotry', 'artifice', 'prudery', 'bale', 'deceit'] },
  queen_of_wands: { upright: ['a dark woman', 'countrywoman', 'friendly', 'chaste', 'loving', 'honourable', 'love of money'], reversed: ['good', 'economical', 'obliging', 'serviceable', 'opposition', 'jealousy', 'even deceit and infidelity'] },
  seven_of_cups: { upright: ['fairy favours', 'images of reflection', 'sentiment', 'imagination'], reversed: ['desire', 'will', 'determination', 'project'] },
  seven_of_pentacles: { upright: ['business', 'barter', 'quarrels', 'ingenuity', 'purgation'], reversed: [] },
  seven_of_swords: { upright: ['design', 'attempt', 'wish', 'hope', 'confidence', 'quarrelling', 'annoyance'], reversed: ['good advice', 'counsel', 'instruction', 'slander', 'babbling'] },
  seven_of_wands: { upright: ['the vantage position', 'wordy strife', 'negotiations', 'war of trade', 'barter', 'competition'], reversed: ['perplexity', 'embarrassments', 'anxiety'] },
  six_of_cups: { upright: ['looking back', 'happiness', 'enjoyment', 'things that have vanished', 'giving new relations', 'new knowledge', 'new environment'], reversed: ['the future', 'renewal'] },
  six_of_pentacles: { upright: ['presents', 'gifts', 'present prosperity'], reversed: ['desire', 'cupidity', 'envy', 'jealousy', 'illusion'] },
  six_of_swords: { upright: ['journey by water', 'route', 'envoy', 'commissionary', 'expedient'], reversed: ['declaration', 'confession', 'publicity'] },
  six_of_wands: { upright: ['the crown of hope'], reversed: ['apprehension', 'fear', 'treachery', 'disloyalty', 'indefinite delay'] },
  star: { upright: ['loss', 'theft', 'privation', 'abandonment'], reversed: ['arrogance', 'haughtiness', 'impotence'] },
  strength: { upright: ['power', 'energy', 'action', 'courage', 'magnanimity', 'complete success and honours'], reversed: ['despotism', 'abuse if power', 'weakness', 'discord'] },
  sun: { upright: ['material happiness', 'fortunate marriage', 'contentment'], reversed: [] },
  temperance: { upright: ['economy', 'moderation', 'frugality', 'management', 'accommodation'], reversed: ['things connected with churches', 'religions', 'sects', 'the priesthood', 'disunion', 'unfortunate combinations', 'competing interests'] },
  ten_of_cups: { upright: ['contentment', 'the town'], reversed: ['indignation', 'violence'] },
  ten_of_pentacles: { upright: ['gain', 'riches', 'family matters', 'archives', 'extraction'], reversed: ['chance', 'fatality', 'loss', 'robbery', 'games of hazard', 'dowry', 'pension'] },
  ten_of_swords: { upright: ['pain', 'affliction', 'tears', 'sadness', 'desolation'], reversed: ['advantage', 'profit', 'success', 'favour', 'power and authority'] },
  ten_of_wands: { upright: ['gain', 'any kind of success', 'disguise', 'perfidy'], reversed: ['contrarieties', 'difficulties', 'intrigues'] },
  three_of_cups: { upright: ['perfection and merriment', 'happy issue', 'victory', 'fulfilment', 'solace', 'healing'], reversed: ['expedition', 'dispatch', 'achievement', 'end'] },
  three_of_pentacles: { upright: ['metier', 'trade', 'skilled labour', 'aristocracy', 'renown', 'glory'], reversed: ['mediocrity', 'puerility', 'pettiness', 'weakness'] },
  three_of_swords: { upright: ['removal', 'absence', 'delay', 'division', 'rupture', 'dispersion'], reversed: ['mental alienation', 'error', 'loss', 'distraction', 'disorder', 'confusion'] },
  three_of_wands: { upright: ['enterprise', 'effort', 'trade', 'commerce', 'discovery', 'bearing his merchandise'], reversed: ['the end of troubles', 'toil and disappointment'] },
  tower: { upright: ['misery', 'distress', 'indigence', 'adversity', 'calamity', 'disgrace', 'deception', 'ruin'], reversed: ['imprisonment', 'tyranny'] },
  two_of_cups: { upright: ['love', 'passion', 'friendship', 'affinity', 'union', 'concord', 'sympathy'], reversed: [] },
  two_of_pentacles: { upright: ['recreation and its connexions', 'agitation', 'trouble', 'embroilment'], reversed: ['enforced gaiety', 'simulated enjoyment', 'handwriting', 'composition', 'letters of exchange'] },
  two_of_swords: { upright: ['courage', 'friendship', 'affection', 'intimacy'], reversed: ['imposture', 'falsehood', 'duplicity', 'disloyalty'] },
  two_of_wands: { upright: ['riches', 'fortune', 'magnificence', 'physical suffering', 'disease', 'chagrin', 'sadness', 'mortification'], reversed: ['surprise', 'wonder', 'enchantment', 'emotion', 'trouble', 'fear'] },
  wheel_of_fortune: { upright: ['destiny', 'fortune', 'success', 'elevation', 'luck', 'felicity'], reversed: ['increase', 'abundance', 'superfluity'] },
  world: { upright: ['assured success', 'recompense', 'voyage', 'route', 'emigration', 'flight', 'change of place'], reversed: ['inertia', 'fixity', 'stagnation', 'permanence', 'ill'] },
};
export const waiteAdditional = {
  ace_of_cups: { upright: ['inflexible will', 'unalterable law'], reversed: ['unexpected change of position'] },
  ace_of_pentacles: { upright: [], reversed: [] },
  ace_of_swords: { upright: [], reversed: ['marriage broken off'] },
  ace_of_wands: { upright: ['calamities of all kinds'], reversed: ['a sign of birth'] },
  eight_of_cups: { upright: [], reversed: ['perfect satisfaction'] },
  eight_of_pentacles: { upright: ['a dark girl'], reversed: [] },
  eight_of_swords: { upright: [], reversed: ['departure of a relative'] },
  eight_of_wands: { upright: [], reversed: [] },
  five_of_cups: { upright: ['generally favourable', 'a happy marriage', 'patrimony', 'legacies', 'gifts', 'success in enterprise'], reversed: [] },
  five_of_pentacles: { upright: [], reversed: ['troubles in love'] },
  five_of_swords: { upright: [], reversed: [] },
  five_of_wands: { upright: ['success in financial speculation'], reversed: [] },
  four_of_cups: { upright: ['contrarieties'], reversed: ['presentiment'] },
  four_of_pentacles: { upright: [], reversed: ['observation', 'hindrances'] },
  four_of_swords: { upright: ['a bad card'], reversed: [] },
  four_of_wands: { upright: ['unexpected good fortune'], reversed: [] },
  king_of_cups: { upright: [], reversed: ['loss'] },
  king_of_pentacles: { upright: ['a rather dark man', 'a merchant', 'master', 'professor'], reversed: [] },
  king_of_swords: { upright: ['a lawyer', 'senator', 'doctor'], reversed: ['a bad man'] },
  king_of_wands: { upright: [], reversed: [] },
  knight_of_cups: { upright: [], reversed: ['irregularity'] },
  knight_of_pentacles: { upright: ['an useful man', 'useful discoveries'], reversed: [] },
  knight_of_swords: { upright: ['a soldier', 'man of arms', 'satellite', 'stipendiary'], reversed: ['struggle with a rival'] },
  knight_of_wands: { upright: ['a bad card', 'alienation'], reversed: ['marriage'] },
  nine_of_cups: { upright: [], reversed: ['good business'] },
  nine_of_pentacles: { upright: [], reversed: ['vain hopes'] },
  nine_of_swords: { upright: ['an ecclesiastic', 'a priest'], reversed: [] },
  nine_of_wands: { upright: ['a bad card'], reversed: [] },
  page_of_cups: { upright: ['good augury'], reversed: ['obstacles of all kinds'] },
  page_of_pentacles: { upright: ['a dark youth', 'a child'], reversed: [] },
  page_of_swords: { upright: [], reversed: ['astonishing news'] },
  page_of_wands: { upright: [], reversed: ['bad news'] },
  queen_of_cups: { upright: [], reversed: [] },
  queen_of_pentacles: { upright: ['dark woman'], reversed: ['an illness'] },
  queen_of_swords: { upright: ['a widow'], reversed: ['a bad woman'] },
  queen_of_wands: { upright: ['a good harvest'], reversed: ['goodwill towards the querent'] },
  seven_of_cups: { upright: ['fair child', 'idea', 'design', 'resolve', 'movement'], reversed: ['success'] },
  seven_of_pentacles: { upright: [], reversed: ['impatience', 'apprehension', 'suspicion'] },
  seven_of_swords: { upright: ['dark girl', 'a good card'], reversed: ['good advice', 'probably neglected'] },
  seven_of_wands: { upright: ['a dark child'], reversed: [] },
  six_of_cups: { upright: ['pleasant memories'], reversed: [] },
  six_of_pentacles: { upright: [], reversed: [] },
  six_of_swords: { upright: [], reversed: ['unfavourable issue of lawsuit'] },
  six_of_wands: { upright: [], reversed: ['fulfilment of deferred hope'] },
  ten_of_cups: { upright: [], reversed: ['sorrow', 'a serious quarrel'] },
  ten_of_pentacles: { upright: ['represents house or dwelling'], reversed: [] },
  ten_of_swords: { upright: ['imprisonment'], reversed: [] },
  ten_of_wands: { upright: ['difficulties and contradictions'], reversed: [] },
  three_of_cups: { upright: [], reversed: ['consolation', 'cure', 'end of the business'] },
  three_of_pentacles: { upright: [], reversed: [] },
  three_of_swords: { upright: [], reversed: ['a nun'] },
  three_of_wands: { upright: ['a very good card', 'collaboration will favour enterprise'], reversed: [] },
  two_of_cups: { upright: ['wealth and honour'], reversed: ['passion'] },
  two_of_pentacles: { upright: [], reversed: ['bad omen', 'ignorance', 'injustice'] },
  two_of_swords: { upright: ['gifts for a lady'], reversed: ['dealings with rogues'] },
  two_of_wands: { upright: [], reversed: [] },
};
export const foliRecurrence = {
  ace: {
    4: { natural: ['financial loss', 'separation from friends', 'love troubles', 'imprisonment'], reversed: [] },
    3: { natural: ['passing troubles', 'relieved by good news'], reversed: [] },
    2: { natural: [], reversed: [] },
  },
  eight: {
    4: { natural: [], reversed: ['undisturbed stability'] },
    3: { natural: ['new family ties', 'honourable intentions'], reversed: ['flirtation', 'dissipation and foolishness'] },
    2: { natural: ['frivolous pleasures', 'passing love fancies', 'an unlooked-for development'], reversed: [] },
  },
  king: {
    4: { natural: ['honours', 'preferment', 'good appointments'], reversed: [] },
    3: { natural: [], reversed: [] },
    2: { natural: ['co-operation in business'], reversed: [] },
  },
  nine: {
    4: { natural: ['accomplishment of unexpected events'], reversed: [] },
    3: { natural: ['health', 'wealth', 'happiness'], reversed: [] },
    2: { natural: ['prosperity and contentment', 'testamentary documents'], reversed: ['small worries'] },
  },
  queen: {
    4: { natural: [], reversed: [] },
    3: { natural: ['friendly visits'], reversed: ['scandal', 'gossip'] },
    2: { natural: ['petty confidences interchanged', 'secrets betrayed', 'a meeting between friends'], reversed: [] },
  },
  seven: {
    4: { natural: ['schemes and snares', 'contention and opposition'], reversed: [] },
    3: { natural: ['ill-health', 'remorse'], reversed: [] },
    2: { natural: ['mutual love', 'an unexpected event'], reversed: ['faithlessness', 'deceit or regret'] },
  },
  ten: {
    4: { natural: ['good fortune', 'wealth'], reversed: [] },
    3: { natural: [], reversed: [] },
    2: { natural: ['unexpected luck'], reversed: [] },
  },
};
export const waiteRecurrence = {
  natural: {
    king: { 4: 'great honour', 3: 'consultation', 2: 'minor counsel' },
    queen: { 4: 'great debate', 3: 'deception by women', 2: 'sincere friends' },
    knight: { 4: 'serious matters', 3: 'lively debate', 2: 'intimacy' },
    page: { 4: 'dangerous illness', 3: 'dispute', 2: 'disquiet' },
    ten: { 4: 'condemnation', 3: 'new condition', 2: 'change' },
    nine: { 4: 'a good friend', 3: 'success', 2: 'receipt' },
    eight: { 4: 'reverse', 3: 'marriage', 2: 'new knowledge' },
    seven: { 4: 'intrigue', 3: 'infirmity', 2: 'news' },
    six: { 4: 'abundance', 3: 'success', 2: 'irritability' },
    five: { 4: 'regularity', 3: 'determination', 2: 'vigils' },
    four: { 4: 'journey near at hand', 3: 'a subject of reflection', 2: 'insomnia' },
    three: { 4: 'progress', 3: 'unity', 2: 'calm' },
    two: { 4: 'contention', 3: 'security', 2: 'accord' },
    ace: { 4: 'favourable chance', 3: 'small success', 2: 'trickery' },
  },
  reversed: {
    king: { 4: 'celerity', 3: 'commerce', 2: 'projects' },
    queen: { 4: 'bad company', 3: 'gluttony', 2: 'work' },
    knight: { 4: 'alliance', 3: 'a duel, or personal encounter', 2: 'susceptibility' },
    page: { 4: 'privation', 3: 'idleness', 2: 'society' },
    ten: { 4: 'event, happening', 3: 'disappointment', 2: 'expectation justified' },
    nine: { 4: 'usury', 3: 'imprudence', 2: 'a small profit' },
    eight: { 4: 'error', 3: 'a spectacle', 2: 'misfortune' },
    seven: { 4: 'quarrellers', 3: 'joy', 2: 'women of no repute' },
    six: { 4: 'care', 3: 'satisfaction', 2: 'downfall' },
    five: { 4: 'order', 3: 'hesitation', 2: 'reverse' },
    four: { 4: 'walks abroad', 3: 'disquiet', 2: 'dispute' },
    three: { 4: 'great success', 3: 'serenity', 2: 'safety' },
    two: { 4: 'reconciliation', 3: 'apprehension', 2: 'mistrust' },
    ace: { 4: 'dishonour', 3: 'debauchery', 2: 'enemies' },
  },
};
