export const waiteTerms = {
  // 依 Waite《The Pictorial Key to the Tarot》（Rider 1910/1911）第三部第二、三節逐字取詞，拼字照原書（英式）。
  ace_of_cups: { upright: ['house of the true heart', 'joy', 'content', 'abode', 'nourishment', 'abundance', 'fertility', 'holy table', 'felicity hereof'], reversed: ['house of the false heart', 'mutation', 'instability', 'revolution'] },
  ace_of_pentacles: { upright: ['perfect contentment', 'felicity', 'ecstasy', 'speedy intelligence', 'gold'], reversed: ['the evil side of wealth', 'bad intelligence', 'great riches', 'comfortable material conditions'] },
  ace_of_swords: { upright: ['triumph', 'the excessive degree in everything', 'conquest', 'triumph of force', 'great force, in love as well as in hatred'], reversed: ['the same, but the results are disastrous', 'conception', 'childbirth', 'augmentation', 'multiplicity'] },
  ace_of_wands: { upright: ['creation', 'invention', 'enterprise', 'principle', 'beginning', 'source', 'birth', 'family', 'origin', 'money', 'fortune', 'inheritance'], reversed: ['fall', 'decadence', 'ruin', 'perdition', 'to perish', 'a certain clouded joy'] },
  chariot: { upright: ['succour', 'providence', 'war', 'triumph', 'presumption', 'vengeance', 'trouble'], reversed: ['riot', 'quarrel', 'dispute', 'litigation', 'defeat'] },
  death: { upright: ['end', 'mortality', 'destruction', 'corruption', 'the loss of a benefactor', 'many contrarieties', 'failure of marriage projects'], reversed: ['inertia', 'sleep', 'lethargy', 'petrifaction', 'somnambulism', 'hope destroyed'] },
  devil: { upright: ['ravage', 'violence', 'vehemence', 'extraordinary efforts', 'force', 'fatality', 'that which is predestined but is not for this reason evil'], reversed: ['evil fatality', 'weakness', 'pettiness', 'blindness'] },
  eight_of_cups: { upright: ['giving joy', 'mildness', 'timidity', 'honour', 'modesty', 'the decline of a matter'], reversed: ['great joy', 'happiness', 'feasting'] },
  eight_of_pentacles: { upright: ['work', 'employment', 'commission', 'craftsmanship', 'skill in craft and business'], reversed: ['voided ambition', 'vanity', 'cupidity', 'exaction', 'usury', 'the ingenious mind turned to cunning and intrigue'] },
  eight_of_swords: { upright: ['bad news', 'violent chagrin', 'crisis', 'censure', 'power in trammels', 'conflict', 'calumny', 'sickness'], reversed: ['disquiet', 'difficulty', 'opposition', 'accident', 'treachery', 'what is unforeseen', 'fatality'] },
  eight_of_wands: { upright: ['activity in undertakings', 'swiftness', 'great haste', 'great hope', 'the arrows of love'], reversed: ['arrows of jealousy', 'internal dispute', 'stingings of conscience', 'quarrels', 'domestic disputes'] },
  emperor: { upright: ['stability', 'power', 'protection', 'realization', 'a great person', 'aid', 'reason', 'conviction', 'authority and will'], reversed: ['benevolence', 'compassion', 'credit', 'confusion to enemies', 'obstruction', 'immaturity'] },
  empress: { upright: ['fruitfulness', 'action', 'initiative', 'length of days', 'the unknown', 'clandestine', 'difficulty', 'doubt', 'ignorance'], reversed: ['light', 'truth', 'the unravelling of involved matters', 'public rejoicings', 'vacillation'] },
  five_of_cups: { upright: ['loss', 'something remains over', 'inheritance', 'patrimony', 'transmission', 'marriage, but not without bitterness or frustration'], reversed: ['news', 'alliances', 'affinity', 'consanguinity', 'ancestry', 'return', 'false projects'] },
  five_of_pentacles: { upright: ['material trouble', 'destitution', 'love and lovers', 'wife', 'husband', 'friend', 'mistress', 'concordance', 'affinities'], reversed: ['disorder', 'chaos', 'ruin', 'discord', 'profligacy'] },
  five_of_swords: { upright: ['degradation', 'destruction', 'revocation', 'infamy', 'dishonour', 'loss'], reversed: ['the same', 'burial and obsequies'] },
  five_of_wands: { upright: ['imitation', 'sham fight', 'strenuous competition and struggle', 'the battle of life', 'gold', 'gain', 'opulence'], reversed: ['litigation', 'disputes', 'trickery', 'contradiction'] },
  fool: { upright: ['folly', 'mania', 'extravagance', 'intoxication', 'delirium', 'frenzy', 'bewrayment'], reversed: ['negligence', 'absence', 'distribution', 'carelessness', 'apathy', 'nullity', 'vanity'] },
  four_of_cups: { upright: ['weariness', 'disgust', 'aversion', 'imaginary vexations', 'blended pleasure'], reversed: ['novelty', 'presage', 'new instruction', 'new relations'] },
  four_of_pentacles: { upright: ['the surety of possessions', 'cleaving to that which one has', 'gift', 'legacy', 'inheritance'], reversed: ['suspense', 'delay', 'opposition'] },
  four_of_swords: { upright: ['vigilance', 'retreat', 'solitude', 'hermit\'s repose', 'exile', 'tomb and coffin'], reversed: ['wise administration', 'circumspection', 'economy', 'avarice', 'precaution', 'testament'] },
  four_of_wands: { upright: ['country life', 'haven of refuge', 'domestic harvest-home', 'repose', 'concord', 'harmony', 'prosperity', 'peace'], reversed: ['prosperity', 'increase', 'felicity', 'beauty', 'embellishment'] },
  hanged_man: { upright: ['wisdom', 'circumspection', 'discernment', 'trials', 'sacrifice', 'intuition', 'divination', 'prophecy'], reversed: ['selfishness', 'the crowd', 'body politic'] },
  hermit: { upright: ['prudence', 'circumspection', 'treason', 'dissimulation', 'roguery', 'corruption'], reversed: ['concealment', 'disguise', 'policy', 'fear', 'unreasoned caution'] },
  hierophant: { upright: ['marriage', 'alliance', 'captivity', 'servitude', 'mercy and goodness', 'inspiration', 'the man to whom the querent has recourse'], reversed: ['society', 'good understanding', 'concord', 'over-kindness', 'weakness'] },
  high_priestess: { upright: ['secrets', 'mystery', 'the future as yet unrevealed', 'the woman who interests the querent, if male', 'the querent herself, if female', 'silence', 'tenacity', 'wisdom', 'science'], reversed: ['passion', 'moral or physical ardour', 'conceit', 'surface knowledge'] },
  // Rider 版原文作 "total loss though lawsuit"（Wikisource 據原書轉錄），是排印錯字；1918 年 De Laurence 版作 through，這裡照改。
  judgement: { upright: ['change of position', 'renewal', 'outcome', 'total loss through lawsuit'], reversed: ['weakness', 'pusillanimity', 'simplicity', 'deliberation', 'decision', 'sentence'] },
  justice: { upright: ['equity', 'rightness', 'probity', 'executive', 'triumph of the deserving side in law'], reversed: ['law in all its departments', 'legal complications', 'bigotry', 'bias', 'excessive severity'] },
  king_of_cups: { upright: ['fair man', 'man of business', 'law', 'divinity', 'responsible', 'equity', 'art and science', 'law and art', 'creative intelligence'], reversed: ['dishonest', 'double-dealing man', 'roguery', 'exaction', 'injustice', 'vice', 'scandal', 'pillage', 'considerable loss'] },
  king_of_pentacles: { upright: ['valour', 'realizing intelligence', 'business and normal intellectual aptitude', 'mathematical gifts', 'success in these paths'], reversed: ['vice', 'weakness', 'ugliness', 'perversity', 'corruption', 'peril'] },
  king_of_swords: { upright: ['judgment', 'power', 'command', 'authority', 'militant intelligence', 'law', 'offices of the crown'], reversed: ['cruelty', 'perversity', 'barbarity', 'perfidy', 'evil intention'] },
  king_of_wands: { upright: ['dark man', 'friendly', 'countryman', 'generally married', 'honest and conscientious', 'honesty', 'news concerning an unexpected heritage'], reversed: ['good, but severe', 'austere, yet tolerant'] },
  knight_of_cups: { upright: ['arrival', 'approach', 'advances', 'proposition', 'demeanour', 'invitation', 'incitement'], reversed: ['trickery', 'artifice', 'subtlety', 'swindling', 'duplicity', 'fraud'] },
  knight_of_pentacles: { upright: ['utility', 'serviceableness', 'interest', 'responsibility', 'rectitude'], reversed: ['inertia', 'idleness', 'stagnation', 'placidity', 'discouragement', 'carelessness'] },
  knight_of_swords: { upright: ['skill', 'bravery', 'capacity', 'defence', 'address', 'enmity', 'wrath', 'war', 'destruction', 'opposition', 'resistance', 'ruin'], reversed: ['imprudence', 'incapacity', 'extravagance'] },
  knight_of_wands: { upright: ['departure', 'absence', 'flight', 'emigration', 'a dark young man', 'friendly', 'change of residence'], reversed: ['rupture', 'division', 'interruption', 'discord'] },
  lovers: { upright: ['attraction', 'love', 'beauty', 'trials overcome'], reversed: ['failure', 'foolish designs', 'marriage frustrated', 'contrarieties of all kinds'] },
  magician: { upright: ['skill', 'diplomacy', 'address', 'subtlety', 'sickness', 'pain', 'loss', 'disaster', 'snares of enemies', 'self-confidence', 'will', 'the querent, if male'], reversed: ['physician', 'magus', 'mental disease', 'disgrace', 'disquiet'] },
  moon: { upright: ['hidden enemies', 'danger', 'calumny', 'darkness', 'terror', 'deception', 'occult forces', 'error'], reversed: ['instability', 'inconstancy', 'silence', 'lesser degrees of deception and error'] },
  nine_of_cups: { upright: ['concord', 'contentment', 'physical bien-être', 'victory', 'success', 'advantage', 'satisfaction for the querent'], reversed: ['truth', 'loyalty', 'liberty', 'mistakes', 'imperfections'] },
  nine_of_pentacles: { upright: ['prudence', 'safety', 'success', 'accomplishment', 'certitude', 'discernment'], reversed: ['roguery', 'deception', 'voided project', 'bad faith'] },
  nine_of_swords: { upright: ['death', 'failure', 'miscarriage', 'delay', 'deception', 'disappointment', 'despair'], reversed: ['imprisonment', 'suspicion', 'doubt', 'reasonable fear', 'shame'] },
  nine_of_wands: { upright: ['strength in opposition', 'delay', 'suspension', 'adjournment'], reversed: ['obstacles', 'adversity', 'calamity'] },
  page_of_cups: { upright: ['fair young man', 'a studious youth', 'news', 'message', 'application', 'reflection', 'meditation'], reversed: ['taste', 'inclination', 'attachment', 'seduction', 'deception', 'artifice'] },
  page_of_pentacles: { upright: ['application', 'study', 'scholarship', 'reflection', 'news', 'messages and the bringer thereof', 'rule', 'management'], reversed: ['prodigality', 'dissipation', 'liberality', 'luxury', 'unfavourable news'] },
  page_of_swords: { upright: ['authority', 'overseeing', 'secret service', 'vigilance', 'spying', 'examination'], reversed: ['more evil side of these qualities', 'what is unforeseen', 'unprepared state', 'sickness'] },
  page_of_wands: { upright: ['dark young man', 'faithful', 'a lover', 'an envoy', 'a postman', 'a dangerous rival', 'family intelligence'], reversed: ['anecdotes', 'announcements', 'evil news', 'indecision', 'instability'] },
  queen_of_cups: { upright: ['good', 'fair woman', 'honest', 'devoted woman', 'loving intelligence', 'the gift of vision', 'success', 'happiness', 'pleasure', 'wisdom', 'virtue', 'a perfect spouse and a good mother'], reversed: ['good woman', 'distinguished woman but one not to be trusted', 'perverse woman', 'vice', 'dishonour', 'depravity'] },
  queen_of_pentacles: { upright: ['opulence', 'generosity', 'magnificence', 'security', 'liberty'], reversed: ['evil', 'suspicion', 'suspense', 'fear', 'mistrust'] },
  queen_of_swords: { upright: ['widowhood', 'female sadness and embarrassment', 'absence', 'sterility', 'mourning', 'privation', 'separation'], reversed: ['malice', 'bigotry', 'artifice', 'prudery', 'bale', 'deceit'] },
  queen_of_wands: { upright: ['a dark woman', 'countrywoman', 'friendly', 'chaste', 'loving', 'honourable', 'love of money', 'a certain success in business'], reversed: ['good', 'economical', 'obliging', 'serviceable', 'opposition', 'jealousy', 'even deceit and infidelity'] },
  seven_of_cups: { upright: ['fairy favours', 'images of reflection', 'sentiment', 'imagination'], reversed: ['desire', 'will', 'determination', 'project'] },
  seven_of_pentacles: { upright: ['money', 'business', 'barter', 'altercation', 'quarrel', 'innocence', 'ingenuity', 'purgation'], reversed: ['anxiety regarding money which it may be proposed to lend'] },
  seven_of_swords: { upright: ['design', 'attempt', 'wish', 'hope', 'confidence', 'quarrelling', 'a plan that may fail', 'annoyance'], reversed: ['good advice', 'counsel', 'instruction', 'slander', 'babbling'] },
  seven_of_wands: { upright: ['valour', 'the vantage position', 'discussion', 'wordy strife', 'negotiations', 'war of trade', 'barter', 'competition', 'success'], reversed: ['perplexity', 'embarrassments', 'anxiety', 'indecision'] },
  six_of_cups: { upright: ['the past', 'memories', 'looking back', 'happiness', 'enjoyment', 'things that have vanished', 'new relations', 'new knowledge', 'new environment'], reversed: ['the future', 'renewal', 'that which will come to pass presently'] },
  six_of_pentacles: { upright: ['presents', 'gifts', 'gratification', 'attention', 'vigilance', 'now is the accepted time', 'present prosperity'], reversed: ['desire', 'cupidity', 'envy', 'jealousy', 'illusion'] },
  six_of_swords: { upright: ['journey by water', 'route', 'way', 'envoy', 'commissionary', 'expedient'], reversed: ['declaration', 'confession', 'publicity', 'a proposal of love'] },
  six_of_wands: { upright: ['a victor triumphing', 'great news', 'expectation crowned with its own desire', 'the crown of hope'], reversed: ['apprehension', 'fear', 'treachery', 'disloyalty', 'indefinite delay'] },
  star: { upright: ['loss', 'theft', 'privation', 'abandonment', 'hope and bright prospects'], reversed: ['arrogance', 'haughtiness', 'impotence'] },
  strength: { upright: ['power', 'energy', 'action', 'courage', 'magnanimity', 'complete success and honours'], reversed: ['despotism', 'abuse of power', 'weakness', 'discord', 'disgrace'] },
  sun: { upright: ['material happiness', 'fortunate marriage', 'contentment'], reversed: ['the same in a lesser sense'] },
  temperance: { upright: ['economy', 'moderation', 'frugality', 'management', 'accommodation'], reversed: ['things connected with churches', 'religions', 'sects', 'the priesthood', 'the priest who will marry the querent', 'disunion', 'unfortunate combinations', 'competing interests'] },
  ten_of_cups: { upright: ['contentment', 'repose of the entire heart', 'perfection of human love and friendship', 'the town, village or country inhabited by the querent'], reversed: ['repose of the false heart', 'indignation', 'violence'] },
  ten_of_pentacles: { upright: ['gain', 'riches', 'family matters', 'archives', 'extraction', 'the abode of a family'], reversed: ['chance', 'fatality', 'loss', 'robbery', 'games of hazard', 'gift', 'dowry', 'pension'] },
  ten_of_swords: { upright: ['pain', 'affliction', 'tears', 'sadness', 'desolation'], reversed: ['advantage', 'profit', 'success', 'favour', 'but none of these are permanent', 'power and authority'] },
  ten_of_wands: { upright: ['oppression', 'fortune', 'gain', 'any kind of success', 'false-seeming', 'disguise', 'perfidy'], reversed: ['contrarieties', 'difficulties', 'intrigues'] },
  three_of_cups: { upright: ['perfection and merriment', 'happy issue', 'victory', 'fulfilment', 'solace', 'healing'], reversed: ['expedition', 'dispatch', 'achievement', 'end', 'excess in physical enjoyment', 'the pleasures of the senses'] },
  three_of_pentacles: { upright: ['métier', 'trade', 'skilled labour', 'nobility', 'aristocracy', 'renown', 'glory'], reversed: ['mediocrity', 'puerility', 'pettiness', 'weakness'] },
  three_of_swords: { upright: ['removal', 'absence', 'delay', 'division', 'rupture', 'dispersion'], reversed: ['mental alienation', 'error', 'loss', 'distraction', 'disorder', 'confusion'] },
  three_of_wands: { upright: ['established strength', 'enterprise', 'effort', 'trade', 'commerce', 'discovery', 'able co-operation in business'], reversed: ['the end of troubles', 'suspension or cessation of adversity', 'toil and disappointment'] },
  tower: { upright: ['misery', 'distress', 'indigence', 'adversity', 'calamity', 'disgrace', 'deception', 'ruin', 'unforeseen catastrophe'], reversed: ['the same in a lesser degree', 'oppression', 'imprisonment', 'tyranny'] },
  two_of_cups: { upright: ['love', 'passion', 'friendship', 'affinity', 'union', 'concord', 'sympathy', 'the interrelation of the sexes'], reversed: [] },
  two_of_pentacles: { upright: ['gaiety', 'recreation and its connexions', 'news and messages in writing', 'obstacles', 'agitation', 'trouble', 'embroilment'], reversed: ['enforced gaiety', 'simulated enjoyment', 'literal sense', 'handwriting', 'composition', 'letters of exchange'] },
  two_of_swords: { upright: ['conformity', 'equipoise', 'courage', 'friendship', 'concord in a state of arms', 'tenderness', 'affection', 'intimacy'], reversed: ['imposture', 'falsehood', 'duplicity', 'disloyalty'] },
  two_of_wands: { upright: ['riches', 'fortune', 'magnificence', 'physical suffering', 'disease', 'chagrin', 'sadness', 'mortification'], reversed: ['surprise', 'wonder', 'enchantment', 'emotion', 'trouble', 'fear'] },
  wheel_of_fortune: { upright: ['destiny', 'fortune', 'success', 'elevation', 'luck', 'felicity'], reversed: ['increase', 'abundance', 'superfluity'] },
  world: { upright: ['assured success', 'recompense', 'voyage', 'route', 'emigration', 'flight', 'change of place'], reversed: ['inertia', 'fixity', 'stagnation', 'permanence'] },
};
export const waiteAdditional = {
  // 第三部第四節，同樣逐字取詞；會改變意思的但書（如 but probably frustrated、if accompanied by…）一併保留。
  ace_of_cups: { upright: ['inflexible will', 'unalterable law'], reversed: ['unexpected change of position'] },
  ace_of_pentacles: { upright: ['the most favourable of all cards'], reversed: ['a share in the finding of treasure'] },
  ace_of_swords: { upright: ['great prosperity or great misery'], reversed: ['marriage broken off'] },
  ace_of_wands: { upright: ['calamities of all kinds'], reversed: ['a sign of birth'] },
  eight_of_cups: { upright: ['marriage with a fair woman'], reversed: ['perfect satisfaction'] },
  eight_of_pentacles: { upright: ['a young man in business who has relations with the querent', 'a dark girl'], reversed: ['the querent will be compromised in a matter of money-lending'] },
  eight_of_swords: { upright: ['for a woman, scandal spread in her respect'], reversed: ['departure of a relative'] },
  eight_of_wands: { upright: ['domestic disputes for a married person'], reversed: [] },
  five_of_cups: { upright: ['generally favourable', 'a happy marriage', 'patrimony', 'legacies', 'gifts', 'success in enterprise'], reversed: ['return of some relative who has not been seen for long'] },
  five_of_pentacles: { upright: ['conquest of fortune by reason'], reversed: ['troubles in love'] },
  five_of_swords: { upright: ['an attack on the fortune of the querent'], reversed: ['a sign of sorrow and mourning'] },
  five_of_wands: { upright: ['success in financial speculation'], reversed: ['quarrels may be turned to advantage'] },
  four_of_cups: { upright: ['contrarieties'], reversed: ['presentiment'] },
  four_of_pentacles: { upright: ['for a bachelor, pleasant news from a lady'], reversed: ['observation', 'hindrances'] },
  four_of_swords: { upright: ['a bad card'], reversed: ['a certain success following wise administration'] },
  four_of_wands: { upright: ['unexpected good fortune'], reversed: ['a married woman will have beautiful children'] },
  king_of_cups: { upright: ['ill-will on the part of a man of position', 'hypocrisy pretending to help'], reversed: ['loss'] },
  king_of_pentacles: { upright: ['a rather dark man', 'a merchant', 'master', 'professor'], reversed: ['an old and vicious man'] },
  king_of_swords: { upright: ['a lawyer', 'senator', 'doctor'], reversed: ['a bad man', 'a caution to put an end to a ruinous lawsuit'] },
  king_of_wands: { upright: ['generally favourable', 'a good marriage'], reversed: ['advice that should be followed'] },
  knight_of_cups: { upright: ['a visit from a friend', 'unexpected money'], reversed: ['irregularity'] },
  // 「an useful man」是原書的寫法（當時的拼法習慣），照錄不改。
  knight_of_pentacles: { upright: ['an useful man', 'useful discoveries'], reversed: ['a brave man out of employment'] },
  knight_of_swords: { upright: ['a soldier', 'man of arms', 'satellite', 'stipendiary', 'heroic action predicted for soldier'], reversed: ['dispute with an imbecile person', 'for a woman, struggle with a rival, who will be conquered'] },
  knight_of_wands: { upright: ['a bad card', 'alienation'], reversed: ['for a woman, marriage, but probably frustrated'] },
  nine_of_cups: { upright: ['of good augury for military men'], reversed: ['good business'] },
  nine_of_pentacles: { upright: ['prompt fulfilment of what is presaged by neighbouring cards'], reversed: ['vain hopes'] },
  nine_of_swords: { upright: ['an ecclesiastic', 'a priest', 'a card of bad omen'], reversed: ['good ground for suspicion against a doubtful person'] },
  nine_of_wands: { upright: ['a bad card'], reversed: [] },
  page_of_cups: { upright: ['good augury', 'a young man who is unfortunate in love'], reversed: ['obstacles of all kinds'] },
  page_of_pentacles: { upright: ['a dark youth', 'a young officer or soldier', 'a child'], reversed: ['degradation', 'pillage'] },
  page_of_swords: { upright: ['an indiscreet person will pry into the querent\'s secrets'], reversed: ['astonishing news'] },
  page_of_wands: { upright: ['young man of family in search of young lady'], reversed: ['bad news'] },
  queen_of_cups: { upright: ['a woman of equivocal character'], reversed: ['a rich marriage for a man and a distinguished one for a woman'] },
  queen_of_pentacles: { upright: ['dark woman', 'presents from a rich relative', 'rich and happy marriage for a young man'], reversed: ['an illness'] },
  queen_of_swords: { upright: ['a widow'], reversed: ['a bad woman, with ill-will towards the querent'] },
  queen_of_wands: { upright: ['a good harvest'], reversed: ['good-will towards the querent, but without the opportunity to exercise it'] },
  seven_of_cups: { upright: ['fair child', 'idea', 'design', 'resolve', 'movement'], reversed: ['success, if accompanied by the three of cups'] },
  seven_of_pentacles: { upright: ['improved position for a lady\'s future husband'], reversed: ['impatience', 'apprehension', 'suspicion'] },
  seven_of_swords: { upright: ['dark girl', 'a good card', 'a country life after a competence has been secured'], reversed: ['good advice, probably neglected'] },
  seven_of_wands: { upright: ['a dark child'], reversed: [] },
  six_of_cups: { upright: ['pleasant memories'], reversed: ['inheritance to fall in quickly'] },
  six_of_pentacles: { upright: ['the present must not be relied on'], reversed: ['a check on the querent\'s ambition'] },
  six_of_swords: { upright: ['the voyage will be pleasant'], reversed: ['unfavourable issue of lawsuit'] },
  six_of_wands: { upright: ['servants may lose the confidence of their masters', 'a young lady may be betrayed by a friend'], reversed: ['fulfilment of deferred hope'] },
  ten_of_cups: { upright: ['for a male querent, a good marriage and one beyond his expectations'], reversed: ['sorrow', 'a serious quarrel'] },
  ten_of_pentacles: { upright: ['represents house or dwelling'], reversed: ['an occasion which may be fortunate or otherwise'] },
  ten_of_swords: { upright: ['imprisonment', 'treason on the part of friends'], reversed: ['victory and consequent fortune for a soldier in war'] },
  ten_of_wands: { upright: ['difficulties and contradictions'], reversed: [] },
  three_of_cups: { upright: ['unexpected advancement for military man'], reversed: ['consolation', 'cure', 'end of the business'] },
  three_of_pentacles: { upright: ['if for a man, celebrity for his eldest son'], reversed: ['depends on neighbouring cards'] },
  three_of_swords: { upright: ['for a woman, the flight of her lover'], reversed: ['a meeting with one whom the querent has compromised', 'a nun'] },
  three_of_wands: { upright: ['a very good card', 'collaboration will favour enterprise'], reversed: [] },
  two_of_cups: { upright: ['favourable in things of pleasure and business, as well as love', 'wealth and honour'], reversed: ['passion'] },
  two_of_pentacles: { upright: ['troubles are more imaginary than real'], reversed: ['bad omen', 'ignorance', 'injustice'] },
  two_of_swords: { upright: ['gifts for a lady', 'influential protection for a man in search of help'], reversed: ['dealings with rogues'] },
  two_of_wands: { upright: ['a young lady may expect trivial disappointments'], reversed: [] },
};
export const foliRecurrence = {
  ace: {
    4: { natural: ['financial loss', 'separation from friends', 'love troubles', 'imprisonment'], reversed: [] },
    3: { natural: ['passing troubles', 'relieved by good news'], reversed: [] },
    2: { natural: [], reversed: [] },
  },
  eight: {
    4: { natural: [], reversed: ['undisturbed stability'] },
    3: { natural: ['new family ties', 'honourable intentions'], reversed: ['flirtation', 'dissipation and foolishness'] },
    2: { natural: ['frivolous pleasures', 'passing love fancies', 'an unlooked-for development'], reversed: [] },
  },
  king: {
    4: { natural: ['honours', 'preferment', 'good appointments'], reversed: [] },
    3: { natural: [], reversed: [] },
    2: { natural: ['co-operation in business'], reversed: [] },
  },
  nine: {
    4: { natural: ['accomplishment of unexpected events'], reversed: [] },
    3: { natural: ['health', 'wealth', 'happiness'], reversed: [] },
    2: { natural: ['prosperity and contentment', 'testamentary documents'], reversed: ['small worries'] },
  },
  queen: {
    4: { natural: [], reversed: [] },
    3: { natural: ['friendly visits'], reversed: ['scandal', 'gossip'] },
    2: { natural: ['petty confidences interchanged', 'secrets betrayed', 'a meeting between friends'], reversed: [] },
  },
  seven: {
    4: { natural: ['schemes and snares', 'contention and opposition'], reversed: [] },
    3: { natural: ['ill-health', 'remorse'], reversed: [] },
    2: { natural: ['mutual love', 'an unexpected event'], reversed: ['faithlessness', 'deceit or regret'] },
  },
  ten: {
    4: { natural: ['good fortune', 'wealth'], reversed: [] },
    3: { natural: [], reversed: [] },
    2: { natural: ['unexpected luck'], reversed: [] },
  },
};
export const waiteRecurrence = {
  natural: {
    king: { 4: 'great honour', 3: 'consultation', 2: 'minor counsel' },
    queen: { 4: 'great debate', 3: 'deception by women', 2: 'sincere friends' },
    knight: { 4: 'serious matters', 3: 'lively debate', 2: 'intimacy' },
    page: { 4: 'dangerous illness', 3: 'dispute', 2: 'disquiet' },
    ten: { 4: 'condemnation', 3: 'new condition', 2: 'change' },
    nine: { 4: 'a good friend', 3: 'success', 2: 'receipt' },
    eight: { 4: 'reverse', 3: 'marriage', 2: 'new knowledge' },
    seven: { 4: 'intrigue', 3: 'infirmity', 2: 'news' },
    six: { 4: 'abundance', 3: 'success', 2: 'irritability' },
    five: { 4: 'regularity', 3: 'determination', 2: 'vigils' },
    four: { 4: 'journey near at hand', 3: 'a subject of reflection', 2: 'insomnia' },
    three: { 4: 'progress', 3: 'unity', 2: 'calm' },
    two: { 4: 'contention', 3: 'security', 2: 'accord' },
    ace: { 4: 'favourable chance', 3: 'small success', 2: 'trickery' },
  },
  reversed: {
    king: { 4: 'celerity', 3: 'commerce', 2: 'projects' },
    queen: { 4: 'bad company', 3: 'gluttony', 2: 'work' },
    knight: { 4: 'alliance', 3: 'a duel, or personal encounter', 2: 'susceptibility' },
    page: { 4: 'privation', 3: 'idleness', 2: 'society' },
    ten: { 4: 'event, happening', 3: 'disappointment', 2: 'expectation justified' },
    nine: { 4: 'usury', 3: 'imprudence', 2: 'a small profit' },
    eight: { 4: 'error', 3: 'a spectacle', 2: 'misfortune' },
    seven: { 4: 'quarrellers', 3: 'joy', 2: 'women of no repute' },
    six: { 4: 'care', 3: 'satisfaction', 2: 'downfall' },
    five: { 4: 'order', 3: 'hesitation', 2: 'reverse' },
    four: { 4: 'walks abroad', 3: 'disquiet', 2: 'dispute' },
    three: { 4: 'great success', 3: 'serenity', 2: 'safety' },
    two: { 4: 'reconciliation', 3: 'apprehension', 2: 'mistrust' },
    ace: { 4: 'dishonour', 3: 'debauchery', 2: 'enemies' },
  },
};
